# 系统性金融风险建模



## 定义DSGE模型框架的变量

[定义DSGE模型框架的变量](./系统性金融风险建模_定义变量.mmd)



## 假设之于DSGE模型框架





## DSGE模型框架的各部门描述



#### 思路一：



考虑一个离散时间的、无限生命周期的经济体。

思路一

[系统性金融风险建模\_主要过程\_1](./系统性金融风险建模_主要过程_1.mmd)







