# TODO模块之居民部门H010



[TOC]



## 参考



参考：

> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.
>
> 马勇, 陈雨露, 2013. 宏观审慎政策的协调与搭配:基于中国的模拟分析[J]. 金融研究, (08): 57–69.





## 特点

居民部门以同质代表性主体代替。





## 总假设之于DSGE模型框架



- 考虑一个离散时间的、无限生命周期的经济体。
- 假设信贷市场属于标准的Dixit-Stiglitz模式





## 模块描述



