# 模块之居民部门H020


[TOC]



## 参考



参考：

> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.





## 特点

异质性代表性主体划分方式按照资金使用方式划分为：

- 借款型居民\mathbb{HB}；
- 投资和储蓄型居民\mathbb{HI}；





## 总假设之于DSGE模型框架



- 考虑一个离散时间的、无限生命周期的经济体。
- 假设信贷市场属于标准的Dixit-Stiglitz模式





## 模块描述





#### 居民部门

居民部门构成：

​	一般划分：

- 借款型居民：

- 投资和储蓄型居民：

  

  特殊角色

- 银行家；

  

其中，成员的转换：

> 参照
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]
> 的做法

居民成员中特殊角色可相互转化，每期银行家的相互转化满足泊松过程，分别以固定的退出率（转换率） $1-\lambda_{b} , \lambda_{b} \in[0,1)$， 随机退出自己岗位转为其他角色。如果退出率为0，则居民成员的角色不相互转化。

> 居民的设置参照
>
> [[方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.]]
>
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]

假设：

- 假设居民部门所有成员生存周期无限；

- 假设居民部门各成员跨期偏好折现因子$\gamma_H$一致；

- 为了保证稳态时，借款型居民是经济体的净借款方，因此设借款型居民的贴现因子应小于投资和储蓄型居民的贴现因子$\gamma_{HB}<\gamma_{HI}$。

- 居民个数为$N_{H}[t]$，其中借款型居民个数为$N_{HB}[t]$，储蓄与投资型居民个数为$N_{HI}[t]$。
  $$
  N_{H}[t]=N_{HB}[t]+N_{HI}[t]
  $$

- 假设居民成员工作于消费品中间品生产商、房地产开发商；

- 假设居民成员持有的资金全部用于消费、投资、储蓄，暨每个时期不存在闲置货币；

- 假设居民部门所有成员提供的劳动${Lab}_{H}[i,t]$是同质的，暨单位生产率是一样的，此时居民成员个体$i$提供的劳动在时期$t$，可以用劳动时长$H_{H}[i,t]$表示；



#### 借款型居民

一些文献描述借款型居民为非耐心居民。

英文全名：

Borrowing Household

变量名：

household_borrowing

数学符号：

$\Box_{HB}$

##### 行为：

- 向商业银行部门之零售贷款银行分支借款$L_{HB,t}$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,H}[t]$；

- 消费产品$C_{HB,t}$；

  

##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有消费行为对于不同的消费项目之偏好$\alpha_{H}$；



##### 模型：

###### 目标：

借款型居民部门的个体$i$的目标是最大化其效用$\mathrm{Utility}_{HB}$在当前时期$t$：

$$
\mathrm{Utility}_{HB}[i,t] :=
\max \quad \mathbb{E}_{i,t=0} 
\left[ \sum_{t=0}^{\infty} 
(\gamma_{HB})^{t} \left(
\alpha_{HB,c} \; \varepsilon_{HB,c}[t] \; \log[C_{HB,c}[i,t]] 
+ \alpha_{HB,h} \; \varepsilon_{HB,h}[t] \; \log C_{HB,h}[i,t]
- \frac{\left(H_{HB}[i,t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
 \right)
\right]
\tag{HB_goal}
$$

其中，
$\gamma_{HB}$：借款型居民跨时期折现因子；
$\alpha_{HB,c}$：借款型居民大众消费行为偏好参数；
$\varepsilon_{HB,c}[t]$：扰动项之于借款型居民之大众消费，在时期$t$；
$C_{HB,c}[i,t]$：借款型居民$i$的大众消费，在时期$t$；
$\alpha_{HB,h}$：借款型居民住房消费行为偏好参数；
$\varepsilon_{HB,h}[t]$：扰动项之于住房消费，在时期$t$；
$C_{HB,h}[i,t]$：借款型居民$i$的住房消费，在时期$t$；
$H_{HB}[i,t]$：借款型居民$i$的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；



对于借款型居民$i$的工作时长，在时期$t$，由如下成分组成：
$$
H_{HB}[i,t] := H_{HB,PI}[i,t] + H_{HB,PE}[i,t]
$$
其中，
$H_{HB,PI}[i,t]$：借款型居民$i$在消费品中间品生产商的工作时长，在时期$t$；
$H_{HB,PE}[i,t]$：借款型居民$i$在房地产开发商的工作时长，在时期$t$；





###### 约束条件：



对于银行部门之零售贷款银行分支，存在以下约束：



预算约束：
$$
C_{HB,c}[i,t] + p_{PE}[t] \; \Delta C_{HB,h}[i,t] + B_{HB,BB}[i,t-1] \; \frac{(1 + r_{b,HB}[t]) }{\pi[t]} = w_{PE}[i,t] \; h_{HB,PE}[i,t] + w_{PI}[i,t] \; h_{HB,PI}[i,t] + B_{HB,BB}[i,t]+{Trans}_{HB}[i,t]
\tag{HB_st_budget}
$$
其中，
$C_{HB,c}[i,t]$：借款型居民$i$的大众消费，在时期$t$；
$p_{PE}[t] \; \Delta C_{HB,h}[i,t]$：房地产价格$p_{PE}[t]$与借款型居民$i$的住房偿还贷款变动量$\Delta C_{HB,h}[i,t]$的乘积，在时期$t$；
$B_{HB,BB}[i,t-1] \; \left(1 + r_{b,HB}[t]\right) / \pi[t]$：借款型居民$i$偿还上一期的借款给商业银行部门于本期，以借款利率$r_{b,HB}[t]$，考虑当前总通胀率$\pi[t]$的影响；
$w_{PE}[i,t]  \; h_{HB,PE}[i,t]$：借款型居民$i$获得总收入，从房地产开发商。暨房地产开发商提供的工资率$w_{HB}[i,t]$，与在房地产开发商的工作时长$H_{HB,PE}[i,t]$的乘积，在时期$t$；
$w_{PI}[i,t] \; h_{HB,PI}[i,t]$：借款型居民$i$获得总收入，从消费品中间品生产商。暨消费品中间品生产商提供的工资率$w_{PI}[i,t]$，与在消费品中间品生产商的工作时长$H_{HB,PI}[i,t]$的乘积，在时期$t$；
$(1+r_{BB,D}[t-1]) \; D_{HB}[i,t-1] / \pi[t]$：借款型居民$i$的上一期存款$D_{HB}[i,t-1]$于本期提现以上一期的存款利率$r_{BB,D}[t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$B_{HB,BB}[i,t]$：借款型居民$i$对银行的借款，在当期$t$；
${Trans}_{HB}[i,t]$：借款型居民$i$获得的转移支付，在时期$t$；



信贷抵押约束：
$$
\left(1+r_{b,HB}[t] \right) B_{HB,BB}[i,t] \leq \theta_{HB}[t] \; \mathbb{E}_{i,t} \left[ p_{PE}[t+1] \; \pi[t+1] \; C_{HB,h}[t] \right]
\tag{HB_st_debt}
$$
其中，
$\theta_{HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；
$B_{HB,BB}[i,t]$：借款型居民$i$对银行的借款；
TODO$p_{PE}[t+1] \; \pi[t+1] \; C_{HB,h}[t]$：信贷抵押约束中，；



#### 投资和储蓄型居民

一些文献描述投资和储蓄型居民为耐心居民。

英文全名：

Investment Household

变量名：

household_investment

数学符号：

$\Box_{HI}$



##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有消费行为对于不同的消费项目之偏好$\alpha_{H}$；



##### 假设：

- 假设考虑存款有两种类型：短期存款、长期存款。用以建模存款挤兑现象；



##### 行为：

- 向银行部门的银行零售银行存款分支存款$D_{HI}[i,t]$，以存款利率$r_{D,t}$；
- 消费大众商品$C_{HI,c}[i,t]$；
- 住房消费$C_{HI,h}[i,t]$；





##### 模型：



###### 目标：



投资和储蓄型居民部门的个体$i$的目标是最大化其效用$\mathrm{Utility}_{HI}$在当前时期$t$：
$$
\mathrm{Utility}_{HI}[i,t]:=
\max \quad \mathbb{E}_{i,t=0} \left[ 
\sum_{t=0}^{\infty}
(\gamma_{HI})^{t} 
\left(
\alpha_{HI,c} \; \varepsilon_{HI,c}[t] \; \log[C_{HI,c}[i,t]] 
+ \alpha_{HI,h} \; \varepsilon_{HI,h}[t] \; \log C_{HI,h}[i,t]
- \frac{\left(H_{HI}[i,t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
\right)
\right]
\tag{HI_goal}
$$
其中，
$\gamma_{HI}$：投资和储蓄型居民跨时期折现因子；
$\alpha_{HI,c}$：投资和储蓄型居民大众消费行为偏好参数；
$\varepsilon_{HI,c}[t]$：扰动项之于投资和储蓄型居民之大众消费，在时期$t$；
$C_{HI,c}[i,t]$：投资和储蓄型居民$i$的大众消费，在时期$t$；
$\alpha_{HI,h}$：投资和储蓄型居民住房消费行为偏好参数；
$\varepsilon_{HI,h}[t]$：扰动项之于住房消费，在时期$t$；
$C_{HI,h}[i,t]$：投资和储蓄型居民$i$的住房消费，在时期$t$；
$H_{HI}[i,t]$：投资和储蓄型居民$i$的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；


对于投资和储蓄型居民$i$的工作时长，在时期$t$，由如下成分组成：
$$
H_{HI}[i,t] := H_{HI,PI}[i,t] + H_{HI,PE}[i,t]
$$
其中，
$H_{HI,PI}[i,t]$：投资和储蓄型居民$i$在消费品中间品生产商的工作时长，在时期$t$；
$H_{HI,PE}[i,t]$：投资和储蓄型居民$i$在房地产开发商的工作时长，在时期$t$；


###### 约束条件：

对于投资和储蓄型居民$i$，存在预算约束：

$$
C_{HI,c}[i,t] + p_{PE}[t] \Delta C_{HI,h}[i,t] + D_{HI}[i,t] = w_{HI}[i,t] C_{HI,h}[i,t] + (1+r_{BB,D}[t-1]) D_{HI}[i,t-1] / \pi[t] + {Trans}_{HI}[i,t])
\tag{HI_st_budget}
$$
其中，
$C_{HI,c}[i,t]$：投资和储蓄型居民$i$的大众消费，在时期$t$；
$p_{PE}[t] \; \Delta C_{HI,h}[i,t]$：住房价格$p_{PE}[t]$与投资和储蓄型居民$i$的住房偿还贷款变动量$\Delta C_{HI,h}[i,t]$的乘积，在时期$t$；
$D_{HI}[i,t]$：投资和储蓄型居民$i$在银行的储蓄；
$w_{PE}[i,t]  \; H_{HI,PE}[i,t]$：投资和储蓄型居民$i$获得总收入，从房地产开发商。暨房地产开发商提供的工资率$w_{PE}[i,t]$，与在房地产开发商的工作时长$H_{HI,PE}[i,t]$的乘积，在时期$t$；
$w_{PI}[i,t] \; H_{HI,PI}[i,t]$：投资和储蓄型居民$i$获得总收入，从消费品中间品生产商。暨消费品中间品生产商提供的工资率$w_{PI}[i,t]$，与在消费品中间品生产商的工作时长$H_{HI,PI}[i,t]$的乘积，在时期$t$；
$(1+r_{BB,D}[t-1]) \; D_{HI}[i,t-1] / \pi[t]$：投资和储蓄型居民$i$提现之存款，其存于上一期，从商业银行部门整体，以上一期的存款利率$r_{BB,D}[t-1]$，考虑当前总通胀率$\pi[t]$的影响；
${Trans}_{HI}[i,t]$：投资和储蓄型居民$i$获得的转移支付，在时期$t$；





- [ ] #### 居民部门居民类型的转换