# 模块之消费品生产商PG010



[TOC]



### 生产部门







#### 模块描述



#### 参考

















#### 消费品生产商

在一些文献中，消费品最终品生产商之作用，相当于零售商之作用。

英文全名：

Goods Producers

变量名：

producers_goods

数学符号：

$\Box_{PG}$





##### 参考



> 消费品生产商部门参考：
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.



##### 模块特点

同质代表性消费品生产商模块PG010不区分子部门。统一用只有一种产出品的完全竞争消费品生产商代表企业部门。



##### 模块接口

代表性消费品生产商之总借款量$B_{PG}[t]$由如下构成：
$$
B_{PG}[t] := B_{PG,B}[t]
$$

其中，
$B_{PG,B}[t]$：消费品生产商部门从银行部门$\mathbb{B}$获得总借款，在时期$t$；



代表性消费品生产商偿还借款量$Repay_{PG}[t]$由如下构成：
$$
Repay_{PG}[t] := Repay_{PG,B}[t]
$$
其中，
$Repay_{PG,B}[t]$：代表性消费品生产商偿还借款给银行部门$\mathbb{B}$，在时期$t$；



对于消费品生产商部门获得借款$B_{PG,B}[t]$​，从银行部门$\mathbb{B}$，由以下构成：
$$
B_{PG,B}[t] := \sum_{i=1}^{N_{\mathbb{B}}}{B_{PG,B}[i,t]}
$$
其中，
$B_{PG,B}[i,t]$：消费品生产商$\mathbb{PG}$借款从银行部门$\mathbb{B}$之个体$i$；



对于消费品生产商部门偿还借款$Repay_{PG,B}[t]$给银行部门$\mathbb{B}$，由以下构成：
$$
Repay_{PG,B}[t] := \frac{(1+r_{B,PG}[t-1])}{\pi[t]} B_{PG,B}[t-1]
= \sum_{i=1}^{N_{\mathbb{B}}}{\left(\frac{(1+r_{B,PG}[i,t-1])}{\pi[t]} \; B_{PG,B}[i,t-1]\right)}
$$
其中，
$\left(r_{B,PG}[i,t-1]+1 \right) / \pi[t]\; B_{PG,B}[i,t-1]$：消费品生产商部门偿还上一期借款$B_{PG,B}[i,t-1]$给银行部门$\mathbb{B}$之个体$i$，以其提供的贷款利率$r_{B,PG}[i,t-1]$于上一期，考虑当期物价$\pi[t]$；



支付工资给居民部门$\mathbb{H}$；



信贷抵押约束(PG_st_debt)；



##### 构成：

- 消费品生产商；

  





##### 假设：

与许多描述同质代表性生产商行为的文献一样，假设生产部门之消费品生产商$i \in \{1,\cdots,N_{PG}\}$具有如下特点：

- 众多消费品生产商$i \in \{1,\cdots,N_{PG}\}$具有同质性，暨不考虑生产商之间的规模、生产产品的种类、生产商之间的其它特性的差异；
- 众多消费品生产商$i \in \{1,\cdots,N_{PG}\}$连续分布于某个区间$[0,1]$。因此在不考虑但各生产商的情况下，我们直接以单个典型消费品生产商作为全体消费品生产商的代表；
- 假设众多消费品生产商之间不考虑互相竞争的详细过程；
- 设定消费品生产商的生产函数形式为典型的Cobb-Douglas生产函数形式；
- 假设生产出来的消费品生产品是单一种类的同质性的产品；
- 假设生产出来的消费品生产品作为商品，能够在当期销售其总量$Y_{PG}[t]$且不留下存货；
- 假设生产出来进入销售环节的商品以单价$p_{PG}=1$，销售所得总收入为$Q_{PG}[t]$；

- 假设消费品生产部门只考虑国内贸易，不考虑对外贸易商品；



##### 行为：

同质性代表性消费品生产商具有如下行为：

- 寻求利润最大化$Profit_{PC}[t]$；

- 获取劳动力要素投入，从居民部门$\mathbb{H}$；

- 获取资本要素投入，从资本累积渠道：

  - 从自身累积资本；
  - 融资资本：
    - 从银行部门$\mathbb{B}$信贷$B_{PG,B}[t]$；
    - TODO从资本市场融资；
    - TODO从政府部门$\mathbb{G}$融资$B_{PG,G}[t]$；
    - 其它；
  
- 通过获取的生产要素生产同质性的产品，总量为$Y_{PG}$；

- 销售所有产品给居民部门$\mathbb{H}$，并且获得总收入$Q_{PG}[t]$；

- 缴纳税收$\tau_{PG}[t]$给政府部门；

- 消费品生产商存在信贷约束；

- 支付工资给居民部门$\mathbb{H}$；

- 偿还借款：

  - 偿还上一期的借款给银行部门$\mathbb{B}$；

    





##### 描述：

由于众多消费品生产商其生产消费品之间是充分竞争的。为了方便起见，以一个代表性生产商表示生产商部门。



消费品生产商资本$K_{PG}[t]$累积过程，呈现一个时变形式：
$$
K_{PG}[t] = (1-\delta_{PG}) \; K_{PG}[t-1] + I_{PG}[t] - Repay_{PG}[t]
$$

其中，
$K_{PG}[t]$：代表性消费品生产商之资本；
$\delta_{PG}$：折旧率之于代表性消费品生产商之资本；
$I_{PG}[t]$：表示代表性消费品生产商之投资量；
$Repay_{PG}[t]$：代表性消费品生产商偿还借款量；





在消费品生产商之资本要素投入方面，已经说明代表性消费品生产商之投资量$I_{PG}[t]$来源，其中包含信贷$B_{PG}[t]$：
$$
I_{PG}[t] = B_{PG}[t]
$$
其中，
$B_{PG}[t]$：消费品生产商借款总量，在时期$t$；








##### 目标：



> 借鉴
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.



消费品生产商部门$\mathbb{PG}$之目标是最大化当期利润$Profit_{PG}[t]$：
$$
Profit_{PG}[t] := 
\max_{B_{PG,B},Lab_{PG}[t],w_{H}[t]} \quad
\left(
\begin{array}{c}
Q_{PG}[t] - w_{H}[t] \; Lab_{PG}[t] \\
+ \Delta K_{PG}[t] \\
- \tau[t]
\end{array}
\right)
\tag{PG_goal}
$$

其中，
$Q_{PG}[t]$：消费品生产商产出销售总收入；
$w_{H}[t] \; Lab_{PG}[t]$：消费品生产商支付工资给居民部门；
$\Delta K_{PG}[t]$：消费品生产商资本变动量，默认表示当期与上一期变动量；
$\tau[t]$：消费品生产商缴纳税收；





##### 约束条件：



消费品生产商主要面临的约束条件有：

- 生产产出；
- 销售约束；
- 信贷抵押约束；





生产产出：

消费品生产商之生产函数$F_{PG}[\cdot]$服从Cobb-Douglas生产函数形式：
$$
Y_{PG}[t] = F_{PG}[TFP_{PG}[t],K_{PG}[t],Lab_{PG}[t]] := TFP_{PG}[t] \; (K_{PG}[t])^{\alpha_{PG}} \; (Lab_{PG}[t])^{1-\alpha_{PG}} \\
\tag{PG_st_product}
$$
其中，
$TFP_{PG}[t]$：消费品领域生产的全要素生产率（技术）在时期$t$；
$K_{PG}[t]$ ：消费品生产商$i$的资本要素；
$Lab_{PG}[t]$：消费品生产商$i$的劳动要素；
$\alpha_{PG}$：消费品生产商各生产要素的替代指数；



假定全要素生产率 $TFP_{PG}[t]$ 服从如下形式的一阶自回归AR(1)过程：
$$
\log TFP_{PG}[t] = \rho_{TFP,PG} \log TFP_{PG}[t-1] + \varepsilon_{TFP,PG}[t]
$$

其中，
$\rho_{TFP,PG}$：消费品生产商的全要素生产率$TFP_{PG}[t]$对应的自回归过程的回归系数；
$\varepsilon_{TFP,PG}[t]$：消费品生产商的全要素生产率对$TFP_{PG}[t]$应的自回归过程的扰动项；



销售约束：

消费品生产商部门销售尽全部的所生产的产品给居民部门，获得收入$Q_{PG}[t]$：
$$
p_{PG} \; Y_{PG}[t] = Q_{PG}[t] = C_{H}[t]
$$







信贷抵押约束：

> 借鉴
>
> 林琳, 曹勇, 肖寒, 2016. 中国式影子银行下的金融系统脆弱性[J]. 经济学(季刊), (03 vo 15): 1113–1136.

消费品生产商抵押固定资产在银行部门$\mathbb{B}$贷款中，存在信贷抵押约束
$$
\begin{array}{l}
\text{for each sector} \text{ in } \mathbb{B} \text{ : }
\\
\left(1+r_{B,PG}[i,t] \right) \; B_{PG,B}[i,t] \leq \phi_{B,PG}[i,t] \; K_{PG}[t]
\tag{PG_st_debt}
\end{array}
$$
其中，
$\left(1+r_{B,PG}[i,t] \right) \; B_{PG,BB}[i,t]$：消费品生产商部门可以借到的贷款量，从银行部门之个体$i$；
$\phi_{B,PG}[i,t]$：银行部门之个体$i$针对消费品生产商给定的贷款抵押资产限制率，暨其为厂商提供的贷款不能超过其资本总额的限制比例；
$K_{PG}[t]$：消费品生产商资本；







