- [ ] # 模块之商业银行BB020



[TOC]





## 参考

> 借鉴
>
> 沈姗姗, 2019. 基于DSGE模型的宏观审慎政策与货币政策调控框架研究[J]. 金融经济学研究, (01 vo 34): 28–42.
>
> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.
>
> 
>
> 





## 特点



所有商业银行具有同质性，用多主体表示；

有助于描述银行间市场；




## 模块描述





##### 划分：

商业银行部门各银行机构按照职能划分为：

- 银行批发部门；
- 银行存款部门；
- 银行贷款部门；





##### 行为：



- 银行批发部门：
  - 
- 银行存款部门：
- 银行贷款部门：



对于传统商业银行部门，包括两类资产：传统贷款、从影子银行购买的资管产品。



