- [ ] # 模块之消费品生产商PG010



[TOC]





## 模块描述



- [ ] #### 参考

> 





#### 特点

同质代表性消费品生产商模块PG010不区分子部门。统一用只有一种产出品的完全竞争消费品生产商代表企业部门。



#### 消费品生产商

在一些文献中，消费品最终品生产商之作用，相当于零售商之作用。

英文全名：

Goods Producers

变量名：

producers_goods

数学符号：

$\Box_{PG}$



##### 假设

- 



##### 行为：

- 消费品生产部门通过外部融资、雇佣劳动生产最终产品，以提供居民部门消费，同时支付工资、利息。其外部融资方式主要为从商业银行和影子银行获得。





##### 构成：

- 消费品生产商；

  



##### 分类：

无。



##### 假设：

与许多描述同质代表性生产商行为的文献一样，假设生产部门之消费品生产商$i \in \{1,\cdots,N_{\mathbb{PG}}\}$具有如下特点：

- 众多消费品生产商$i \in \{1,\cdots,N_{\mathbb{PG}}\}$具有同质性，暨不考虑厂商之间的规模、生产产品的种类、厂商之间的其它特性的差异；
- 众多消费品生产商$i \in \{1,\cdots,N_{\mathbb{PG}}\}$连续分布于某个区间$[0,1]$。因此在不考虑但各厂商的情况下，我们直接以单个典型消费品生产商作为全体消费品生产商的代表；
- 假设生产消费品中间品的厂商之间不考虑互相竞争的详细过程；
- 设定生产商的生产函数形式为典型的Cobb-Douglas生产函数形式；
- 假设生产出来的消费品生产品是单一种类的同质性的产品；
- 假设生产出来的消费品生产品作为商品，能够在当期销售以单价$p_{PG}=1$，且不留下存货；

此外，我们假设：

- 假设消费品生产部门只考虑国内贸易，不考虑对外贸易消费商品；



##### 行为：

同质性代表性消费品生产商具有如下行为：

- 寻求利润最大化${Profit}_{PC}[t]$；
- 获取劳动力要素投入，从居民部门；
- 获取资本要素投入，从资本累积渠道：

  - 从自身累积资本；
  - 融资资本，从金融中介机构：
    - 商业银行部门$\mathbb{BB}$；
    - 影子银行部门$\mathbb{BS}$；
    - TODO资本市场融资；
    - 政府部门$\mathbb{G}$；
    - 其它；
- 通过获取的生产要素生产同质性的产品，总量为$Y_{PG}$；
- 销售所有产品
- 消费品中间品厂商制定最优价格或者调整价格以某种机制；
- 消费品中间品生产商存在信贷约束；





##### 描述：

由于众多消费品生产商其生产消费品之间是充分竞争的。为了方便起见，以一个代表性厂商表示厂商部门。





##### 目标：

消费品生产商部门$\mathbb{PG}$之目标是当期利润最大化：

$$
{Profit}_{PC}[t] := 
\max_{K,{Lab}} \quad
\left(
\begin{gather}
Y_{PG}[t] - w_{PE}[i,t] \; {Lab}_{PG}[t] \\
- \left(r_{BB,PG}+1 \right) \; B_{PG,BB}[i,t] \\

\end{gather}
\right)
\tag{PG_goal}
$$



##### 约束条件：

生产产出：



消费品生产商之生产函数$F_{PG}[\cdot]$服从Cobb-Douglas生产函数形式：
$$
Y_{PG}[t] = F_{PG}[{TFP}_{PG}[t],K_{PG}[t],{Lab}_{PG}[t]] := {TFP}_{PG}[t] \; (K_{PG}[t])^{\alpha_{PG}} \; ({Lab}_{PG}[t])^{1-\alpha_{PG}}
\tag{PG_st_product}
$$
其中，
${TFP}_{PG}[t]$：消费品领域生产的全要素生产率（技术）在时期$t$；
$K_{PG}[t]$ ：消费品生产商$i$的资本要素；
${Lab}_{PG}[t]$：消费品生产商$i$的劳动要素；
$\alpha_{PG}$：消费品生产商各生产要素的替代指数；



假定全要素生产率 ${TFP}_{PG}[t]$ 服从如下形式的一阶自回归AR(1)过程：
$$
\log {TFP}_{PG}[t] = \rho_{A,PI} \ln {TFP}_{PG}[t-1] + \varepsilon_{A,PI}[t]
$$

其中，
$\rho_{A,PI}$：消费品中间品生产商的全要素生产率${TFP}_{PG}[t]$对应的自回归过程的回归系数；
$\varepsilon_{A,PI}[t]$：消费品中间品生产商的全要素生产率对${TFP}_{PG}[t]$应的自回归过程的扰动项；





资金流约束：
$$

$$

资本$K_{PG}[t]$累积过程，呈现一个时变形式：
$$
K_{PG}[t] = (1-\delta_{PG}) \; K_{PG}[t-1] + I_{PG}[t]
$$


其中，
$K_{PG}[t]$：代表性消费品生产商之资本；
$\delta_{PG}$：折旧率之于代表性消费品生产商之资本；
$I_{PG}[t]$：表示代表性消费品生产商之投资量；





代表性消费品生产商之投资量$I_{PG}[t]$由如下组成：
$$
I_{PG}[t] = B_{PG,BB}[i,t] + B_{PG,BS}[j,t]
$$
其中，













