# TODO模块之银行间市场BI010



[TOC]





### 银行间市场



#### 参考

> 方意, 2016. 系统性风险的传染渠道与度量研究——兼论宏观审慎政策实施[J]. 管理世界, (08): 32-57,187.
>
> 方意, 黄丽灵, 2019. 系统性风险、抛售博弈与宏观审慎政策[J]. 经济研究, (09 vo 54): 41–55.
>
> 方意, 2017. 中国银行业系统性风险研究——宏观审慎视角下的三个压力测试[J]. 经济理论与经济管理, (02): 48–66.
>
> 方意, 郑子文, 2016. 系统性风险在银行间的传染路径研究——基于持有共同资产网络模型[J]. 国际金融研究, (06): 61–72.
>
> 张萌, 2015. 货币国际化视角下的系统性风险传导机制与监管策略研究[D]. 云南大学.
>
> 





#### 模块假设：

在这里，划分一个时期$t$至$t+1$之间之时期$\Delta t$。假设在一个$\Delta t$期间，银行间市场经历一轮传染冲击。







#### 特点





所有商业银行具有同质性，用多主体表示；

有助于描述银行间市场；




#### 模块描述









英文全名：

Interbank market

变量名：

bank_inter

数学符号：

$\Box_{BI}$



银行间市场考虑银行间市场之间的作用关系；

其中包括描述以下时期，银行间市场交易的资产负债关系构成的网络结构。

其中，时期包括：

- 正常时期；
- 发生危机造成的传染的时期；



银行间市场按照交易行为划分

- 银行间同业拆借；





借鉴

> 张萌, 2015. 货币国际化视角下的系统性风险传导机制与监管策略研究[D]. 云南大学.
>
> 方意, 2016. 系统性风险的传染渠道与度量研究——兼论宏观审慎政策实施[J]. 管理世界, (08): 32-57,187.



TODO「可能需要修改其方法之修辞」其采用矩阵法分析风险传导在空间维度上的变化；



对于银行间市场，我们构建由$N_{BB}$个商业银行$i,i \in \{1,\cdots,N_{BB}\}$构成的矩阵$X_{BI}[t]$，来描述银行间市场交易行为的网络：
$$
X_{BI}[t]:=\begin{pmatrix}
x_{1,1}[t] & \cdots & x_{1,j}[t] & \cdots & x_{1,N_{BB}}[t] \\
\vdots & \ddots & \vdots & \cdots & \vdots \\
x_{i,1}[t] & \cdots & x_{i,j}[t] & \cdots & x_{i,N_{BB}}[t] \\
\vdots & \therefore & \vdots & \ddots & \vdots \\
x_{N_{BB},1}[t] & \cdots & x_{N_{BB},j}[t] & \cdots & x_{N_{BB},N_{BB}}[t]
\end{pmatrix}
$$

其中，
矩阵$X_{BI}[t]$：表示时期$t$，银行间市场交易行为的网络；
元素$x_{i,j}[t]$：表示时期$t$，银行$i$对银行$j$之间的信息；



作为外延，当我们研究银行间资产负债关系的时候，可以构建相应的资产负债网络，定义如下：


$$
A_{BI}[t]:=\begin{pmatrix}
a_{1,1}[t] & \cdots & a_{1,j}[t] & \cdots & a_{1,N_{BB}}[t] \\
\vdots & \ddots & \vdots & \cdots & \vdots \\
a_{i,1}[t] & \cdots & a_{i,j}[t] & \cdots & a_{i,N_{BB}}[t] \\
\vdots & \therefore & \vdots & \ddots & \vdots \\
a_{N_{BB},1}[t] & \cdots & a_{N_{BB},j}[t] & \cdots & a_{N_{BB},N_{BB}}[t]
\end{pmatrix}
$$

其中，
矩阵$A_{BI}[t]$：表示时期$t$，银行间市场形成的资产负债表；
元素$a_{i,j}[t]$：表示时期$t$，银行$i$对银行$j$的同业资产占所有银行总同业资产比率，或银行$j$对银行$i$的同业负债占所有银行总同业负债比率。定义如下：
$$
a_{i,j}[t] := \frac{{Asset}_{BI}[i,j,t]}{{Asset}_{BI}[t]}
$$


根据

> 方意, 2016. 系统性风险的传染渠道与度量研究——兼论宏观审慎政策实施[J]. 管理世界, (08): 32-57,187.

构建一个银行间市场风险传染机制。



由于在一个$\Delta t$期间，银行间市场经历一轮传染冲击。我们划分一轮传染冲击$\Delta t$期间内为银行间市场风险传染之小时期$\tau,\tau \in {0,\cdots,N_{\tau}}$。接下来阐述模型在时间轴$\tau$的作用；





假设银行$i$在时期$t=0$遭受资产损失冲击${Asset}_{BB,Loss}[i,t]$；





~~对于单个商业银行$i$，有如下行为：~~

- ~~商业银行$i$从常规渠道获得资本，其融资来源：~~

  - ~~自有资本$K_{BB}[i,t]$；~~
  - ~~接受投资和储蓄型居民部门$\mathbb{HI}$整体存款资金$D_{HI}[\cdot,i,t]$至商业银行$i$；~~
  - ~~商业银行提供资金$D_{HI}[\cdot,i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需；~~
  - ~~银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$在拆借市场于时期$t$；~~

- ~~提供贷款服务：~~

  - ~~商业银行$i$提供贷款资本贷给消费品生产部门（非金融机构）：~~

    - ~~商业银行$i$提供当期贷款$L_{BB,PG}[i,t]$给消费品生产商部门$\mathbb{PG}$，并且需要考虑贷款审查成本；~~
    - ~~商业银行$i$收回上一期贷款$L_{BB,PG}[i,t-1]$，其贷给消费品生产商部门$\mathbb{PG}$，并且需要考虑利息；~~
  - ~~商业银行$i$提供贷款给借款型居民部门：~~

    - ~~商业银行$i$提供贷款$L_{BB,H}[i,t]$给借款型居民部门之居民$\mathbb{HB}$于当期$t$，以利率$r_{BB,HB}[i,t]$；~~

    - ~~商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,H}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$，从借款型居民部门之居民$\mathbb{HB}_{j}$；~~

- ~~支付管理费用${Manage}_{BB}[i,t]$；~~

- ~~股利分红$Dv_{BB}[i,t]$；~~

- ~~现有面临监管要求：~~

  - ~~贷存比监管$\check{\theta}_{{LDR}}[i,t]$：~~

    ~~不满足规定贷存比要求对应的惩罚函数$Pun_{{LDR}}[i,t,gap_[i,t]]$；~~

  - ~~资本充足率监管$\check{\phi}_{CAR}[i,t]$：~~

    ~~不满足规定资本充足率要求对应的惩罚函数$Pun_{CAR}[i,t]$；~~











