# 模块之商业银行BB010


[TOC]







## 参考

> 
>
> 





- [ ] ## 特点



所有商业银行具有同质性，用一个代表性主体表示；




## 模块描述



> 借鉴
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.
>
> Fève P, Moura A, Pierrard O, 2019. Shadow Banking and Financial Regulation: A Small-Scale DSGE Perspective[J]. Journal of Economic Dynamics and Control, 101: 130–144. DOI:10.1016/j.jedc.2019.02.001.



##### 行为：

- [ ] 对于单个商业银行部门$BB$，有如下行为：


- 从常规渠道获得资本，其融资来源：

  - 自有资本$K_{BB}[t]$更新自上一时期；

  - 获得资金，通过居民部门整体存款资金$D_{H}[t]$至商业银行；

  - 银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BB,BB}[i,j,t]$于时期$t$；

    > 由于银行部门同业拆借在该模块属于部门内部行为，因此不考虑详细同业拆借细节，只关注该行为造成的影响：如成本、稳定性等。

- 偿还借款：

  - 向居民部门

- 提供贷款服务：

  - 将资本贷给生产部门（非金融机构）；

  - 商业银行$i$提供贷款$B_{BB,HB}[i,j,t]$给居民部门之居民$H_j$于时间$t$，以利率$r_{BB,H}[t]$；

    