- [ ] # 模块之商业银行BB120



[TOC]







## 参考

> 
>
> 





- [ ] ## 特点



所有商业银行具有同质性，用多主体表示；

有助于描述银行间市场；




## 模块描述



> 借鉴
>
> 



英文全名：

Commercial Bank

变量名：

bank_commercial

数学符号：

$\Box_{BB}$



##### 整体商业银行部门部门划分：

单个商业银行按照职能部门划分为：

- 银行批发部门；
- 银行存款部门；
- 银行贷款部门；





我国整体商业银行部门按照资本规模划分：

- 五大银行；
- 其它上市银行；
- 未上市银行；





##### 行为：



对于单个商业银行$i$，有如下行为：

- 商业银行$i$从常规渠道获得资本，其融资来源：

  - 自有资本$K_{BB}[i,t]$；
  - 居民部门整体存款资金$D_{H}[i,\cdot,t]$至商业银行$i$；
  - 提供资金$D_{H}[\cdot,i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供居民部门$H$提取上一期存款所需；
  - 银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$于时期$t$；

- 提供贷款服务：

  - 商业银行$i$提供贷款资本贷给生产部门（非金融机构）：
    - 贷款$L_{BB,PG}[t]$给消费品生产商部门$\mathbb{PG}$，在当期；
    - 商业银行$i$收回上一期贷给消费品生产商部门$\mathbb{P}$之中间生产商$\mathbb{PI}$之贷款$TODO$，从消费品中间品生产商$\mathbb{PI}_{j}$；
    - 贷款$L_{BB,PE}[t]$给房地产开发商部门$\mathbb{PE}$，在当期；
    - 商业银行$i$收回上一期贷给房地产开发商部门$\mathbb{PE}$之贷款$L_{BB,PE}[t-1] \; (1+r_{BB,PE}[i,t-1]) / \pi[t]$；

  - 商业银行$i$提供贷款给居民部门：

    - 商业银行$i$提供贷款$L_{BB,H}[i,j,t]$给居民部门之居民$H_j$于当期$t$，以利率$r_{BB,HB}[i,t]$；

    - 商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,HB}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$，从借款型居民部门之居民$\mathbb{HB}_{j}$；

- - [ ] 开展影子银行业务：

  
  - 为影子银行部门提供资金；
  
- 股利分红$Dv_{BB}[t]$；

  



- [ ] 对于传统商业银行部门，包括两类资产：传统贷款、从影子银行购买的资管产品。









