- [ ] # 模块之商业银行BB030



[TOC]





## 参考

> 借鉴
>
> 王擎, 田娇, 2016. 银行资本监管与系统性金融风险传递——基于DSGE模型的分析[J]. 中国社会科学, 000(03): 99–122.
>
> 
>
> 





## 特点



所有商业银行具有同质性，用多主体表示；

有助于描述银行间市场；




## 模块描述





### 划分：

商业银行部门各银行机构按照规模和在银行间市场的债务情况划分为：

- 资金净拆出银行（大银行、资本充裕）；

- 资金净拆入银行（小银行、资本短缺）；





### 行为：



- 各种类型银行之共同行为：

  - 融资：

    - 居民部门整体存款资金$D_{H}[\cdot,t]$至商业银行$i$；
    - 自有资本$K_{BB}[t]$跨期变更从常规渠道获得资本；

  - 返回存款：

    - 返还上一期存款本息$(1+r_{BB,HI}[t-1]) D_{H}[i,t-1] / \pi[t]$给家庭部门；

      

  - 支付给银行家一定报酬$$；

  - 

  - 追求综合效用$Utility_{BB}[t]$最大化：

    - 利润最大化；
    - ……；

    > 股利分红行为似乎不符合国情？





- 资金净拆出银行：

  以商业银行中，单个银行为代表性主体，资金净拆出银行之行为：

  - 融资：
    - 同业拆借，通过同业拆借渠道给商业银行贷款；

    

  

- 资金净拆入银行：

  以商业银行中，单个银行为代表性主体，资金净拆入银行之行为：

  - 融资：
    - 同业拆借，通过同业拆借渠道向其它商业银行借款；

  - 发放贷款：

    - 发放贷款$B_{H}[t]$给非金融机构（生产部门）用于投资；

  - 收回贷款：

    - 收回贷款之于上一借贷期贷出$B_{H}[t-1] \; (1+r_{BB,P}) / \pi[t]$从生产部门（非金融机构）；

    

  



### 分析：







