- [ ] # 模块之商业银行BB010



[TOC]





## 参考

> 
>
> 





- [ ] ## 特点



所有商业银行具有同质性，用多主体表示；

有助于描述银行间市场；




## 模块描述



> 借鉴
>
> 



##### 划分：

商业银行部门各银行机构按照规模和在银行间市场的债务情况划分为：

- 资金净拆出银行；


- 资金净拆入银行；





##### 行为：



资金净拆出银行：

以商业银行中，单个银行为代表性主体，资金净拆出银行之行为：

- 接受存款$D_{H}[t]$来自家庭部门，于当前时期；
- 返回存款：
  - 返还上一期存款$D_{H}[t-1]$给家庭部门；
- 发放贷款：
  - 发放贷款给非金融机构（生产部门）用于投资；
- 收回贷款：
  - 收回上一借贷期贷款从生产部门（非金融机构）；
- 同业拆借
  - 通过同业拆借渠道给商业银行贷款；
  - 通过同业拆借渠道向其它商业银行借款；
- 股利分红；
- 支付给银行家一定报酬；

- 自有资本$K_{BB}[t]$跨期变更从常规渠道获得资本：

  



对于传统商业银行部门，包括两类资产：传统贷款、从影子银行购买的资管产品。



