# 模块之居民部门H020


[TOC]



### 居民部门



#### 参考

> 居民部门的设置参照
>
> [[方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.]]
>
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]



#### 模块特点

异质性代表性主体划分方式按照资金使用方式划分为：

- 借款型居民$\mathbb{HB}$；
- 投资和储蓄型居民$\mathbb{HI}$；



#### 模块接口



对于居民部门之消费需求$C_{H}[t]$由以下构成：

$$
C_{H}[t] := \sum_{P}{\left( C_{H,P}[t] \right)}
$$

其中，
$C_{H,departments}[t]$：居民部门需求对于生产部门各部门；

上述表达式对于居民部门各子部门同样有效。





对于居民部门$\mathbb{H}$之住房消费需求$C_{H,PG}[t]$，有如下表达式：
$$
C_{H,PE}[t] := p_{PE}[t] \; \Delta C_{H,PE}[t]
$$

其中，
$p_{PE}[t] \; \Delta C_{H,PE}[t]$：房地产价格$p_{PE}[t]$与居民部门的住房偿还贷款变动量$\Delta C_{H,PE}[t]$的乘积，在时期$t$；

上述表达式对于居民部门各子部门同样有效。





对于居民部门$\mathbb{H}$之消费效用${Uti}_{H,C}[t]$，可进行进一步定义；
$$
{Uti}_{H,C}[t] := \sum_{P}{\left( \alpha_{H,P} \; \varepsilon_{H,P}[t] \; \log[C_{H,P}[t]] \right)}
$$

其中，
$\alpha_{H,P}$：居民部门$\mathbb{H}$对于生产部门$\mathbb{P}$之消费行为偏好参数；
$\varepsilon_{H,P}[t]$：扰动项之于居民部门$\mathbb{H}$对于生产部门$\mathbb{P}$之消费，在时期$t$；
$C_{H,P}[t]$：居民部门$\mathbb{H}$对于生产部门$\mathbb{P}$之消费，在时期$t$；

上述表达式对于居民部门各子部门同样有效。





对于居民部门$\mathbb{H}$之工作时长${Hour}_{H}[t]$，在时期$t$，由如下部分组成：
$$
Hour_{H}[t] := \sum_{P}{\left( Hour_{H,P}[t] \right)}
$$

其中，
$Hour_{H,P}[t]$：居民部门$\mathbb{H}$在生产部门$\mathbb{P}$的工作时长，在时期$t$；

上述表达式对于居民部门各子部门同样有效。







定义居民部门$\mathbb{H}$获得总收入$Income_{H}[t]$，在时期$t$，由如下部分组成：
$$
Income_{H}[t] := \sum_{P}{\left( w_{P}[t] \; {Hour}_{H,P}[t] \right)}
$$

其中，
$w_{P}[t]  \; {Hour}_{H,P}[t]$：居民部门$\mathbb{H}$获得总收入，从生产部门$\mathbb{P}$。暨该生产部门提供的工资率$w_{P}[t]$，与该居民部门在该生产部门工作时长${Hour}_{H,P}[t]$之乘积，在时期$t$；

上述表达式对于居民部门各子部门同样有效。















#### 部门构成：

一般划分：

- 借款型居民：

- 投资和储蓄型居民：

  

特殊角色：

- 银行家；

  



#### 部门假设：

- 假设居民部门所有成员生存周期无限；

- 假设居民部门各成员跨期偏好折现因子$\gamma_H$一致；

- 为了保证稳态时，借款型居民是经济体的净借款方，因此设借款型居民的贴现因子应小于投资和储蓄型居民的贴现因子$\gamma_{HB}<\gamma_{HI}$。

- 居民个数占比为$\theta_{H,N}[t]$，其中借款型居民个数占比为$\theta_{HB,N}[t]$，储蓄与投资型居民个数占比为$\theta_{HI,N}[t]$。则有如下关系式：
  $$
  \theta_{H,N}[t] := \theta_{HB,N}[t] + \theta_{HI,N}[t]
  $$

- 假设居民成员工作于生产商部门各子部门；

- 假设居民成员持有的资金全部用于消费、投资、储蓄，暨每个时期不存在闲置货币；

- 假设居民部门所有成员提供的劳动${Lab}_{H}[t]$是同质的，暨单位生产率是一样的，此时居民提供的劳动在时期$t$，可以用劳动时长${Hour}_{H}[t]$表示；



#### 借款型居民

一些文献描述借款型居民为非耐心居民。

英文全名：

Borrowing Household

变量名：

household_borrowing

数学符号：

$\Box_{HB}$





##### 行为：

- 向商业银行部门之个体$i$借款$B_{HB,BB}[i,t]$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,HB}[i,t]$；

- 向商业银行部门之个体$i$还款$B_{HB,BB}[i,t]$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,HB}[i,t]$；

- 消费需求$C_{HB}[t]$；

  

##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有消费行为对于不同的消费项目之偏好$\alpha_{H}$；



##### 模型：

###### 目标：

借款型居民部门之目标是最大化其效用${Utility}_{HB}$在当前时期$t$：

$$
{Utility}_{HB}[t] :=
\max _{{Uti}_{HB,C}[t],{Hour}_{HB}[t]}
\quad \mathbb{E}_{t=0} 
\left[ \sum_{t=0}^{\infty} 
(\gamma_{HB})^{t} \left(
{Uti}_{HB,C}[t]
- \frac{\left(Hour_{HB}[t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
 \right)
\right]
\tag{HB_goal}
$$

其中，
$\gamma_{HB}$：借款型居民跨时期折现因子；
${Uti}_{HB,C}[t]$：借款型居民之消费效用；
$Hour_{HB}[t]$：借款型居民的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；







###### 约束条件：



对于借款型居民，存在以下约束：



预算约束：
$$
C_{HB}[t] + B_{HB,BB}[i,t-1] \; \frac{(1 + r_{BB,HB}[i,t]) }{\pi[t]} \leq {Income}_{HB}[t] + B_{HB,BB}[i,t] + {Trans}_{HB}[t]
\tag{HB_st_budget}
$$
其中，
$C_{HB}[t]$：借款型居民之消费需求，在时期$t$；
$B_{HB,BB}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$：借款型居民偿还上一期的借款给商业银行部门于本期，以借款利率$r_{BB,HB}[i,t]$，考虑当前总通胀率$\pi[t]$的影响；
$Income_{HB}[t]$：借款型居民当期总收入；
$B_{HB,BB}[i,t-1] \; (1+r_{BB,HB}[i,t-1]) / \pi[t]$：借款型居民之上一期借款$B_{HB,BB}[i,t-1]$于本期偿还，以上一期的商业银行$i$设定的贷款利率$r_{BB,HI}[i,t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$B_{HB,BB}[i,t]$：借款型居民对银行的借款，在当期$t$；
${Trans}_{HB}[t]$：借款型居民获得的转移支付，在时期$t$；



~~对于借款型居民消费在房地产方面，存在信贷抵押约束：~~
$$
\left(1+r_{BB,HB}[i,t] \right) B_{HB,BB}[i,t] \leq \theta_{BB,HB}[t] \; \mathbb{E}_{t} \left[ p_{PE}[t+1] \; \pi[t+1] \; C_{HB,PE}[t] \right]
\tag{HB_st_debt}
$$
~~其中，~~
~~$\theta_{BB,HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{BB,HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；~~
~~$B_{HB,BB}[i,t]$：借款型居民对银行的借款；~~
~~TODO$p_{PE}[t+1] \; \pi[t+1] \; C_{HB,PE}[t]$：信贷抵押约束中，；~~





#### 投资和储蓄型居民

一些文献描述投资和储蓄型居民为耐心居民。

英文全名：

Investment Household

变量名：

household_investment

数学符号：

$\Box_{HI}$



##### 基本设定：



- [ ] 投资和储蓄型居民的存款需求$D_{HI}[t]$有两种类型：短期存款、长期存款。用以建模存款挤兑现象。

$$
D_{HI}[t] := D_{HI,s}[t] + D_{HI,l}[t]
$$

其中，
$D_{H,s}[t]$：居民部门短期存款；
$D_{H,l}[t]$：居民部门长期存款；




##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有消费行为对于不同的消费项目之偏好$\alpha_{H}$；



##### 行为：

- 向商业银行部门个体$i$存款$D_{HI}[t]$，以商业银行$i$提供的存款利率$r_{BB,HI}[i,t]$；

- 向商业银行部门个体$i$取款$D_{HI}[t]$，以商业银行$i$提供的存款利率$r_{BB,HI}[i,t]$；

- 消费需求$C_{HI}[t]$；

  



##### 模型：



###### 目标：



投资和储蓄型居民部门的个体$i$的目标是最大化其效用${Utility}_{HI}[t]$在当前时期$t$：
$$
{Utility}_{HI}[t]:=
\max \quad \mathbb{E}_{t=0} \left[ 
\sum_{t=0}^{\infty}
(\gamma_{HI})^{t} 
\left(
{Uti}_{HI,C}[t]
- \frac{\left({Hour}_{HI}[t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
\right)
\right]
\tag{HI_goal}
$$
其中，
$\gamma_{HI}$：投资和储蓄型居民跨时期折现因子；
${Uti}_{HI,C}[t]$：投资和储蓄型居民之消费效用；
${Hour}_{HI}[t]$：投资和储蓄型居民的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；




###### 约束条件：

对于投资和储蓄型居民，存在以下约束：



预算约束：
$$
C_{HI}[t] + D_{HI}[t] \leq {Income}_{HI}[t] + \frac{(1+r_{BB,HI}[i,t-1])}{\pi[t]} \; D_{HI}[i,t-1] + {Trans}_{HI}[t]
\tag{HI_st_budget}
$$
其中，
$C_{HI}[t]$：投资和储蓄型居民之消费需求，在时期$t$；
$D_{HI}[t]$：投资和储蓄型居民在银行的储蓄；
$Income_{HI}[t]$：投资和储蓄型居民当期总收入；
$(1+r_{BB,HI}[i,t-1]) \; D_{HI}[i,t-1] / \pi[t]$：投资和储蓄型居民提现存于上一期的存款，从商业银行$i$，以上一期的存款利率$r_{BB,HI}[i,t-1]$，考虑当前总通胀率$\pi[t]$的影响；
${Trans}_{HI}[t]$：投资和储蓄型居民获得的转移支付，在时期$t$；





#### 居民部门居民类型的转换



- [ ] 居民部门$\mathbb{H}$两类居民的转换



~~其中，银行家成员的转换：~~

> ~~参照~~
> ~~[[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]~~
> ~~的做法~~

~~居民成员中特殊角色可相互转化，每期银行家的相互转化满足泊松过程，分别以固定的退出率（转换率） $1-\lambda_{b} , \lambda_{b} \in[0,1)$， 随机退出自己岗位转为其他角色。如果退出率为0，则居民成员的角色不相互转化。~~



