# TODO模块之多主体商业银行BB120



[TOC]





### 商业银行部门



#### 参考

> 
>
> 





#### 特点



所有商业银行具有同质性，用多主体表示；

有助于描述银行间市场；






#### 模块描述



> 借鉴
>
> 



英文全名：

Commercial Bank

变量名：

bank_commercial

数学符号：

$\Box_{BB}$



##### 整体商业银行部门部门划分：

单个商业银行按照职能部门划分为：

- 银行批发部门；
- 银行存款部门；
- 银行贷款部门；





我国整体商业银行部门按照资本规模划分：

- 五大银行；
- 其它上市银行；
- 未上市银行；





#### 行为：



对于单个商业银行$i$，有如下行为：

- 商业银行$i$从常规渠道获得资本，其融资来源：

  - 自有资本$K_{BB}[i,t]$；
  - 接受投资和储蓄型居民部门$\mathbb{HI}$整体存款资金$D_{HI}[\cdot,i,t]$至商业银行$i$；
  - 商业银行提供资金$D_{HI}[\cdot,i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需；
  - 银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$在拆借市场于时期$t$；

- 提供贷款服务：

  - 商业银行$i$提供贷款资本贷给消费品生产部门（非金融机构）：

    - 商业银行$i$提供当期贷款$L_{BB,PG}[i,t]$给消费品生产商部门$\mathbb{PG}$，并且需要考虑贷款审查成本；
    - 商业银行$i$收回上一期贷款$L_{BB,PG}[i,t-1]$，其贷给消费品生产商部门$\mathbb{PG}$，并且需要考虑利息；
  - 商业银行$i$提供贷款给借款型居民部门：

    - 商业银行$i$提供贷款$L_{BB,H}[i,t]$给借款型居民部门之居民$\mathbb{HB}$于当期$t$，以利率$r_{BB,HB}[i,t]$；

    - 商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,H}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$，从借款型居民部门之居民$\mathbb{HB}_{j}$；

- 支付管理费用${Manage}_{BB}[i,t]$；

- 股利分红$Dv_{BB}[i,t]$；

- 现有面临监管要求：

  - 贷存比监管$\check{\theta}_{{LDR}}[i,t]$：

    不满足规定贷存比要求对应的惩罚函数$Pun_{{LDR}}[i,t,gap_[i,t]]$；

  - 资本充足率监管$\check{\phi}_{CAR}[i,t]$：

    不满足规定资本充足率要求对应的惩罚函数$Pun_{CAR}[i,t]$；









