# 模块之房地产开发商PE010


[TOC]







## 参考

> 房地产开发商部分参考
>
> [[郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产开发商的DSGE模型分析[J]. 南方经济, (08): 29–46.]]
>
> 





## 特点








## 模块描述



#### 房地产开发商TODO

TODO

英文全名：

Real Estate Producers

变量名：

producers_estate

数学符号：

$\Box_{PE}$





##### 行为：

- 从商业银行获得贷款；
- 从影子银行部门获得融资；
- 采用资本、劳动、土地开发建设房地产；



> 本部分参考
>
> [[郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产开发商的DSGE模型分析[J]. 南方经济, (08): 29–46.]]
>
> 



##### 模型：

房地产开发商部门的生产函数$F_{PE}$符合规模报酬不变的特性。

对于整个房地产开发商部门来说，其生产函数$F_{PE}[\cdot]$：

$$
Y_{PE}[t] = F_{PE}[\mathrm{TFP}_{PE}[t],K_{PE}[t],La_{PE}[t],H_{PE}[t]] := \mathrm{TFP}_{PE}[t] \; (K_{PE}[t-1])^{\alpha_{PE,K}} (La_{PE}[t])^{\alpha_{PE,L}} (H_{PE}[t-1])^{\alpha_{PE,H}}
$$

其中，
$Y_{PE}[t]$：房地产开发商的最终产出；
$\mathrm{TFP}_{PE}[t]$：房地产开发商的全要素生产率；
$K_{PE}[t-1]$：房地产开发商之资本存量，在上一时期；
$H_{PE}[t-1]$：房地产存量，在上一时期；
$La_{PE}[t]$：房地产商投入的劳动力要素；
$H_{PE}[t-1]$：房地产商投入的房地产商品存量，在上一时期；
$\alpha_{PE,K}$：房地产开发商投入资本要素所占的替代指数；
$\alpha_{PE,L}$：房地产开发商投入劳动要素所占的替代指数；
$\alpha_{PE,H}$：房地产开发商投入房地产要素所占的替代指数；

其中，替代指数满足

$$
\alpha_{PE,K}+\alpha_{PE,L}+\alpha_{PE,H}=1​
$$





###### 目标：


整体商地产开发商部门之目标在于最大化其消费：

$$
\max \mathbb{E}_{t} \sum_{t=0}^{\infty} \gamma_{PE} \; \ln C_{PE}[t]
$$

其中，
$C_{PE}[t]$：房地产开发商之消费；
$\gamma_{PE}$：贴现因子，$0<\gamma_{PE}<1$ 。



###### 约束条件：

房地产开发商所受现金流的约束条件如下:

$$
Y_{PE}[t] + B_{BB,PE}[t] + B_{BS,PE}[t] = C_{PE}[t] + p_{PE}[t] \; \left(H_{PE}[t] - H_{PE}[t-1]\right) + w_{PE}[t] \; La_{PE}[t] + B_{BB,PE}[t-1] \; \frac{(1+r_{BB,PE}[t-1])}{\pi[t]} + B_{BS,PE}[t-1] \; \frac{(1+r_{BS,PE}[t-1])}{\pi[t]} + I_{PE}[t]
$$

TODO理解和替换相关变量

其中，
$Y_{PE}[t]$：房地产开发商的产出；
$B_{BB,PE}[t]$：房地产开发商从商业银行借款，在时期$t$；
$r_{BB,PE}[t]$：商业银行向房地产开发商的贷款利率；
$p_{PE}[t]$：房地产价格：
$B_{BS,PE}[t]$：房地产开发商向影子银行获取的贷款的数量；
$r_{BS,PE}[t]$：影子银行向房地产开发商的贷款利率；
$I_{PE}[t]$：房地产开发商的投资；
$\left(H_{PE}[t]-H_{PE}[t-1]\right)$：房地产流量，在当期的时候；
$w_{PE}[t]$：房地产开发商提供的支付单位工资，暨工资率，在时期$t$；
$La_{PE}[t]$：房地产商的劳动力资源要素，在时期$t$，体现为房地产开发商提供的工资率；

房地产开发企业总体信贷规模为 $B_{PE}[t] := SH_{}[t]+B_{BB,PE}[t]$。

房地产开发商的投资 $I_{PE}[t]$ 与资本存量 $K_{PE}[t]^{h}$ 之间存在如下关系:

$$
(K_{PE}[t+1])^{h}=I_{PE}[t]+(1-\delta_{PE}) (K_{PE}[t])^{h}
$$

该式表示的是房地产开发商资本存量的积累情况, $\delta_{PE}$ 表示资本折旧率。

> 本文借鉴
>
> [[Christensen I, Dib A, 2008. The Financial Accelerator in an Estimated New Keynesian Model[J]. Review of Economic Dynamics, 11(1): 155–178. DOI:[10.1016/j.red.2007.04.006](https://doi.org/10.1016/j.red.2007.04.006).]]
>
> [[Iacoviello M, 2005. House Prices, Borrowing Constraints, and Monetary Policy in the Business Cycle[J]. American Economic Review, 95(3): 739–764. DOI:[10.1257/0002828054201477](https://doi.org/10.1257/0002828054201477).]]
>
> 的研究，引入信贷约束机制

对于商业银行来说，由于存在信贷约束机制。通过引入信贷约束机制，房地产开发商将其持有的房地产抵押给商业银行获得抵押贷款，但是其所获得的抵押贷款的数量取决于其还款期抵押品的预期价值。假设 $\theta_{PE} \in (0,1)$ 为房地产开发商信贷约束比例，需满足:

$$
B_{BB,PE}[t] \leq \theta_{PE} \frac{\mathbb{E}_{t} \left[p_{PE}[t+1] \; H_{PE}[t] \; \pi[t+1]\right]}{r_{BB,PE}[t]}
$$

其中，
$\theta_{PE}$：为房地产开发商信贷约束比例；
$B_{BB,PE}[t]$：房地产开发商从商业银行借款，在时期$t$；
$r_{BB,PE}[t]$：商业银行向房地产开发商的贷款利率；
$H_{PE}[t]$：房地产部门整体存量，在当期的时候；














