# 模块之消费品生产商PG020


[TOC]



## 特点

异质代表性消费品生产商模块PG020按照功能划分消费品生产商为：

- 消费品最终品生产商；
- 消费品中间品生产商；
- 消费品资本品生产商；



## 说明

生产部门通过外部融资或者购买资本、雇佣劳动生产最终产品，以提供居民部门消费，同时支付工资、利息。其外部融资方式主要为从商业银行和影子银行获得。生产最终产品的过程涉及到生产中间品、生产资本品。引入资本品生产商，用以引入资本调整成本，以相对方便处理的形式。





## 构成：

消费品生产商；

- 生产中间品的厂商；
- 生产最终品的厂商；
- 资本品生产商；



## 模块描述





#### 消费品最终品生产商

在一些文献中，消费品最终品生产商之作用，相当于零售商之作用。

英文全名：

Final Goods Producers

变量名：

producers_final

数学符号：

$\Box_{PF}$



##### 假设

- 假设生产消费品最终品的厂商之间是充分竞争的；



##### 行为：

- 接收中间品生产商生产有差别的中间产品，组装生产出无差别的有竞争性质的最终品。





##### 模型：



###### 决策目标：

最大化利润，在给定消费品最终品价格$p_{PF}[t]$和中间品价格$p_{PI}[i,t]$时：
$$
\mathrm{Profit}_{PF}[t] := \max _{Y_{PI}[i,t]} p_{PF}[t] Y_{PF}[t] - \int_{0}^{1} p_{PI}[i, t] Y_{PI}[i, t] \; \mathbb{d} i
$$



其中，
$Y_{PF}[t]$：消费品最终品产量；



###### 约束条件：

$$
Y_{PF}[t] := \left(\int_{0}^{1} (Y_{PI}[i,t])^{\frac{\alpha_{PF} - 1}{\alpha_{PF}}} \; \mathbb{d} i\right)^{\frac{\alpha_{PF}}{\alpha_{PF}-1}}
$$

其中，
$\alpha_{PF}$：替代指数，暨消费品最终品生产商对于不同的由消费品中间品生产商生产的产品的替代指数；

由上述式子可列出拉格朗日函数，通过一阶条件，求得消费品中间品生产商$i$的产出需求$Y_{PI}[i, t]$：
$$
Y_{PI}[i, t] = \left(\frac{p_{PF}[t]}{p_{PI}[i, t]} \right)^{\alpha_{PF}} Y_{PF}[t]
$$



#### 消费品中间品生产商：

英文全名：

Intermediate Goods Producers

变量名：

producers_intermediate

数学符号：

$\Box_{PI}$



##### 假设：

- 假设生产消费品中间品的厂商之间不考虑互相竞争的详细过程；
- 假设生产消费品中间品的厂商的产品是同种类的，具有要素替代性；
- 假设经济中存在一系列连续的消费品中间品生产商$i \in [0,1]$连续统，意味着每一个消费品中间品生产商对该消费品中间品市场的影响都是无穷小的；
- 假设消费品中间品生产商的定价规则遵循Calvo的定价机制。
- 假设每一期从未参与消费品中间品生产商随机抽取比例为 $1-\theta_{PI,p}$数量的厂商参与重新定价；
- 假设消费品中间品生产商$j$参与定价一次$\tilde {P}_{PI}[j,t]$之后，之后不再参与被随机抽取，暨之后不能最优地重新定价；
- 假设未能参与重新定价的消费品中间品生产商的价格根据过去的通胀水平确定其指数化了的价格；
- 假设所有参与重新定价的消费品中间品生产商厂商 $j \in \mathbb{PI_{1}}$  都选择同样的价格 $\tilde{P}_{PI}[t] \equiv \tilde{P}_{PI}[j,t]$；



##### 行为：

- 一个消费品中间品生产商$i$生产$Y_{PI}[i,t]$单位的产品$i$在$t$期，以供最终厂商打包生产最终品。这里的不同的产品$i$是有差别的；

- 获取劳动力要素投入，从居民部门；

- 获取资本要素投入，从资本累积渠道：

  - 从资本品生产商$\mathbb{PK}$购买资本；
  - 融资资本，从金融中介机构：
    - 商业银行部门；
    - 影子银行部门；

- 消费品中间品厂商制定最优价格或者调整价格以某种机制；

- 消费品中间品生产商存在信贷约束；

  

  - [ ] 信贷约束：

  $$
  b_{t} \leq m E_{t}\left(q_{t+1} h_{t} \pi_{t+1} / R_{t}\right)
  $$

  





##### 模型：



> 根据
>
> [[Calvo G A, 1983. Staggered prices in a utility-maximizing framework[J]. Journal of Monetary Economics, 12(3): 383–398.]]
>
> 设定中间厂商定价机制。



> 详细的推导过程跳转
>
> [推导消费品中间品生产商较详细的过程](./../详细推导过程/推导消费品中间品生产商.mmd)
>
> 。

假设消费品中间品生产商的个体$i_{PI}$构成的集合为$\mathbb{PI}$，数量为$N_{PI}$。

为了简化分析，在这里，假设消费品中间品厂商的定价机制遵循Calvo定价机制。在第$t$期，随机以一定数量比例$(1 - \theta_{PI,p})$选择生产商$j \in \mathbb{PI_{1}}$，它们在本期参与制定价格为$\tilde{P}_{PI}[j,t]$。假设所有参与重新定价的消费品中间品生产商厂商$j$都选择同样的价格 $\tilde{P}_{PI}[t] \equiv \tilde{P}_{PI}[j,t]$。在当期，其未被选中能够参与制定最优价格之其余厂商个体$k$，构成厂商集合$\mathbb{PI_{2}}$，此时有$k \in \mathbb{PI_{2}}$。未被选中能够参与制定最优价格的厂商$k$则调整价格，其调整价格以总通货膨胀率为基准。

此时中间品生产商的最优化问题中，即包含最大化收益，也包含最小化成本问题，因此分析时考虑分为两个阶段决策。

消费品中间品生产商决策目标分为两阶段：

1. 所有的消费品中间品厂商最小化其总成本；
1. 消费品中间品生产商其可以参与制定价格的，最大化其实际预期贴现利润；





阶段1：最小化总成本。

所有的消费品中间品生产商$i$最小化其总成本$TC_{PI}$，在时期$t$。

$$
{TC}_{PI}[i,t] := \min _{{Lab}_{PI}[i,t] , K_{PI}[i,t]}  w_{PI}[t] \; {Lab}_{PI}[i,t] + r_{PK,PI}[t] \; K_{PI}[i,t]
$$
其中，
$w_{PI}[t]$：消费品中间品生产商对居民支付单位工资（工资率），在时期$t$；
${Lab}_{PI}[i,t]$：消费品中间品生产商$i$的劳动力要素，在时期$t$；
$r_{PK,PI}[t]$：消费品中间品生产商的消耗单位资本租金率，在时期$t$；
$K_{PI}[i,t]$：消费品中间品生产商$i$的资本，在时期$t$；

- [ ] 这里$K_{PI}[i,t]$的生成方式包括：

  - 向资本品生产商购买资本，以价格$p_{PK}[t]$；

    





对于整个消费品中间品生产商部门而言，
$$
{TC}_{PI}[t] := \sum_{i=1}^{N_{PF}} {TC}_{PI}[i,t]
$$




最小化成本问题对应约束条件：

消费品中间品生产商之生产函数$F_{PI}[\cdot]$
$$
Y_{PI}[i,t] = F_{PI}[\mathrm{TFP}_{PI}[t],K_{PI}[i,t],{Lab}_{PI}[i,t]] := \mathrm{TFP}_{PI}[t] \; (K_{PI}[i,t])^{\alpha_{PI}} \; ({Lab}_{PI}[i,t])^{1-\alpha_{PI}}
$$
其中，
$\mathrm{TFP}_{PI}[t]$：消费品领域生产的全要素生产率（技术）在时期$t$；
$K_{PI}[i,t]$ ：消费品中间品生产商$i$的资本要素；
${Lab}_{PI}[i,t]$：消费品中间品生产商$i$的劳动要素；
$\alpha_{PI}$：消费品中间品生产商各生产要素的替代指数；

~~$\Phi$：消费品中间品生产商的固定生产成本。在稳态条件下，其值被设定为产生0利润；~~

假定全要素生产率 $\mathrm{TFP}_{PI}[t]$ 服从如下形式的一阶自回归AR(1)过程：
$$
\ln \mathrm{TFP}_{PI}[t] = \rho_{A,PI} \ln \mathrm{TFP}_{PI}[t-1] + \varepsilon_{A,PI}[t]
$$

其中，
$\rho_{A,PI}$：消费品中间品生产商的全要素生产率$\mathrm{TFP}_{PI}[t]$对应的自回归过程的回归系数；
$\varepsilon_{A,PI}[t]$：消费品中间品生产商的全要素生产率对$\mathrm{TFP}_{PI}[t]$应的自回归过程的扰动项；



由最优化问题的一阶条件可以得出资本$K_{PI}[i,t]$和劳动${Lab}_{PI}[i,t]$的表达式，然后代入最小化总成本表达式、约束条件，即可得消费品中间品生产商$i$的实际总成本$TC_{PI}[t]$，然后可以得到消费品中间品生产商$i$共有的实际边际成本$MC_{PI}[t]$：
$$
MC_{PI}[t]
:= \frac{TC_{PI}[t]}{Y_{PI}[t]}
= \left( 1-\alpha_{PI} \right)^{\alpha_{PI} -1} \; (\alpha_{PI})^{-\alpha_{PI}} \; \frac{(w_{PI}[t])^{1-\alpha_{PI}} \; (r_{PK,PI}[t])^{\alpha_{PI}}}{\mathrm{TFP}_{PI}[t]}
$$







阶段2：制定最优价格以最大化总利润。

基于时期$t$，参与制定最优价格的消费品中间品生产商$j \in \mathbb{PI_{1}}$，通过制定最优价格最大化其实际预期贴现利润在时期$t_{s}$，暨在时期$t+t_{s}, \quad t_{s} \in [t,\infty)$。

另外，未能参与制定最优价格$\tilde{P}_{PI}[j,t]$之消费品中间品生产商$k \in \mathbb{PI_{2}}$根据过去的通货膨率$\pi[t-1]$确定其指数化价格为
$$
p_{PI}[k,t]=(\pi[t-1])^{\chi_{p}} \; p_{PI}[i,t-1]
$$
其中，
$\chi_{p} \in[0,1]$ ：指数化程度参数；
$\pi[\cdot]$：通货膨胀率于特定时期，其定义为
$$
\pi[t] := \frac{P[t]}{P[t-1]}
$$

其中，
$P[\cdot]$：表示物价于特定时期；



因为对于未参与定价的消费品中间品生产商$k$，价格之调整以总通货膨胀率为基准，所以消费品最终品生产商的定价规则为
$$
p_{PF}[t] = \theta_{PI,p} \; \left( (\pi[t+t_{h}-1])^{\chi_{p}} \; p_{PF}[t-1] \right)   + (1-\theta_{PI,p}) \; p_{PI}[j,t]
$$

由于我们采用的Calvo定价规则，假设了在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取所占比例为 $(1-\theta_{PI,p})$数量的厂商参与重新定价。此时意味着在时期$t$，被随机抽取中参与重新定价的厂商的数量占比为$(1 - \theta_{PI,p})$。

假设消费品中间品生产商$j$参与定价一次$\tilde{P}_{PI}[j,t]$之后，之后不再参与被随机抽取，暨之后不能最优地重新定价，从而该消费品中间品生产商$j$的价格$p_{PI}[j,t+t_{s}]$在时期$t+t_{s} \quad t_{s} \in [t,\infty)$为

$$
p_{PI}[j,t+t_{s}] = \prod_{t_{h}=1}^{t_{s}} 
\left(
	(\pi[t+t_{h}-1])^{\chi_{p}} 
\right)	
\; \tilde{P}_{PI}[j,t]
$$

消费品中间品生产商面临的最大化问题是：

$$
\begin{align*}
& \max _{\tilde{P}_{PI}[j,t]} \mathrm{Profit}_{PI}[j,t] \\
:= & \max _{\tilde{P}_{PI}[j,t]} 
\mathbb{E}_{t} \sum_{t_{s}=0}^{\infty}
\left(
(\gamma_{PI})^{t_{s}} \; (\theta_{PI,p})^{t_{s}}
\; \left(\frac{p_{PF}[t+t_{s}]}{		
			\prod_{t_{h}=1}^{t_{s}} 
      \left(
      (\pi[t+t_{h}-1])^{\chi_{p}} 
      \right)	
			\; \tilde{P}_{PI}[j,t]
    } \right)^{\alpha_{PF}} Y_{PF}[t+t_{s}]
	\;
	\left(
		\prod_{t_{h}=1}^{t_{s}} 
		\left(
		(\pi[t+t_{h}-1])^{\chi_{p}} 
		\right)	
		\; \tilde{P}_{PI}[j,t]
		- MC_{PI}[t + t_{s}]
	\right)
\right)
\end{align*}
\tag{PG_goal}
$$

其中，
$\gamma_{PI}$：消费品中间品生产商之效用贴现因子；
$\theta_{PI,p}$：在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取一定数量的厂商以参与重新定价，剩余仍未被抽取中以参与重新定价的厂商数量所占的比例；
$\alpha_{PF}$：消费品中间品生产商不同的产品的替代弹性；


上述最优化问题对应的约束条件是消费品中间品生产商$i$的产量需求：

$$
\text { s. t. } 
\quad Y_{PI}[i,t+t_{s}] = 
\left(
	\prod_{t_{h}=1}^{t_{s}} \left( (\pi[t + t_{h} - 1])^{\chi_{p}} \right) \frac{\tilde{P}_{PI}[t]}{p_{PF}[t+t_{s}]}
\right)^{-\alpha_{PF}} 
\; Y_{PF}[t+t_{s}]
$$

产量需求的约束意味着消费品中间品生产商将在每一期中生产该期价格下所需求的全部产品。

最优化问题对应的一阶条件：
$$
\tilde{P}_{PI}[t] =
\frac{\alpha_{PF}}{\alpha_{PF}-1} 
\frac
{
\mathbb{E}_{t} 
\sum \limits_{t_{s}=0}^{\infty}
	\left(
		\left(\gamma_{PI} \; \theta_{PI,p} \right)^{t_{s}} \; p_{PF}[t+t_{s}] \; MC_{PI}[t+t_{s}] \; Y_{PF}[i, t+t_{s}]
	\right)
}
{
\mathbb{E}_{t} \sum \limits_{t_{s}=0}^{\infty}
	\left(
		\left(\gamma_{PI} \; \theta_{PI,p} \right)^{t_{s}} 
		\; \prod \limits_{t_{h}=1}^{t_{s}} 
			\left(  
				(\pi[t+t_{h}-1])^{\chi_{p}} 
			\right)  
		\; Y_{PI}[i, t+t_{s}]
	\right)
}
$$

其中，
$MC_{PI}[t+t_{s]}$：消费品中间品生产商的实际边际成本。

根据消费品中间品生产商的产量$Y_{PI}[i,t]$与$Y_{PF}[t]$的关系
$$
Y_{PI}[i, t] = \left(\frac{p_{PI}[i, t]}{p_{PF}[t]} \right)^{-\alpha_{PF}} Y_{PF}[t]
$$
，然后采用Uhlig提出的对数线性化的方法，经过推导，可得消费品中间品生产商之价格水平的时变表达式

$$
(p_{PF}[t])^{1-\alpha_{PF}}
= \theta_{PI,p} \; \left((\pi[t-1])^{\chi_{p}} \; P[t-1] \right)^{1-\alpha_{PF}} + (1-\theta_{PI,p}) \; \left(\tilde{P}_{PI}[t]\right)^{1-\alpha_{PF}}
$$

通过对数线性化上面两个式子，并采用差分方法消除对未来期望值的无穷加总项，经过推导，最终可以得到如下形式的混合型新凯恩斯菲利普斯曲线（hybrid NKPC）

$$
\hat{\pi}[t] =
\frac{\gamma_{PI}}{1+\gamma_{PI} \;\chi_{p}} \mathbb{E}_{t} \; \hat{\pi}[t+1]
+
\frac{\chi_{p}}{1+\gamma_{PI} \; \chi_{p}} \; \hat{\pi}[t-1]
+
\frac
{
\left( 1-\theta_{PI,p} \right) \; \left( 1-\gamma_{PI} \theta_{PI,p} \right)
}{
\theta_{PI,p}\left(1+\gamma_{PI} \theta_{PI,p}\right)
} 
\; \hat{MC}_{PI}[t]
$$

其中，
$\hat{\Box}$：上标带尖冒号表示相应变量偏离比例相对于其其稳态值；

特别地，当 $\chi_{p}=0$ 时，上式变成前瞻型的新凯恩斯菲利普斯曲线( forward-looking NKPC)。通过引入混合性的菲利普斯曲线,有利于更好地对真实的通货膨胀过程及其动态机制进行刻画。





> 资本品生产商的建模描述主要参考
>
> [[马勇, 2013. 植入金融因素的DSGE模型与宏观审慎货币政策规则[J]. 世界经济, (07 vo 36): 68–92.]]
>
> 













#### 资本品生产商

英文全名：

Capital Goods Producers

变量名：

producers_capital

数学符号：

$\Box_{PK}$



> 资本品生产商的建模描述主要参考
>
> [[马勇, 2013. 植入金融因素的DSGE模型与宏观审慎货币政策规则[J]. 世界经济, (07 vo 36): 68–92.]]
>
> 其中，(马勇, 2013)参考了
>
> [[Faia E, Monacelli T, 2007. Optimal Interest Rate Rules, Asset Prices, and Credit Frictions[J]. Journal of Economic Dynamics and Control, 31(10): 3228–3254. DOI:[10.1016/j.jedc.2006.11.006](https://doi.org/10.1016/j.jedc.2006.11.006).]]









##### 引入原因

引入资本品生产商，用以引入资本调整成本，以相对方便处理的形式。





##### 行为：

- 具有竞争性的生产资本品生产商$i$利用投资和现有资本存量生产新的资本品，这样的生产将耗费一定的物质转换成本。
- 资本品生产商获取资本渠道：
  - 金融中介机构：
    - 商业银行部门；
    - 影子银行部门；
  - 外部融资：
    - 通过证券市场融资；







##### 模型：

设定生产函数形式为CRS（具有一次齐次假设的）生产函数$F_{PK}$为

$$
F_{PK}\left[\frac{I_{PI}[t]}{K_{PI}[t]}\right]K_{PI}[t]
$$

则对应的时变的资本累积时变方程为

$$
K_{PK}[t+1]=(1-\delta_{PK}) K_{PK}[t]+F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right] K_{PK}[t]
\tag{PK_K}
$$

决策目标：

资本生产部门的决策问题：

$$
\max _{I_{PK}[t]} \quad p_{PK}[t] \; F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right] \; K_{PK}[t]-p_{PF}[t] \; I_{PK}[t]
\tag{PK_goal}
$$

其中一阶条件：

$$
p_{PK}[t] \; {F_{PK}}^{\prime} \left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]=p_{PF}[t]
$$

全要素生产率$\mathrm{TFP}_{PK}[t]$服从AR(1)过程：

$$
\ln \mathrm{TFP}_{PK}[t]=\rho_{A,PK} \ln \mathrm{TFP}_{PK}[t-1] + \varepsilon_{A,PK}[t]
$$

其中，$\varepsilon_{A,PK}[t]$ 服从标准差为$\sigma_{A,PK}$的i.i.d.冲击。

相邻时期持有单位资本的名义总回报率$r_{PK,n}[t]$的计算如下，

$$
\begin{align*}
r_{PK,n}[t] & := r_{PK,PI}[t] + p_{PF}[t] \; 
\frac
{
	\partial K_{PK}[t+1]
}{
	\partial K_{PK}[t]
}
\\
& = r_{PK,PI}[t] + p_{PF}[t] \left((1-\delta_{PK}) - F_{PK} \left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]   \; \frac{I_{PK}[t]}{K_{PK}[t]}+F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]\right)
\end{align*}
$$

- [ ] TODO：如何求得均衡条件？


在均衡条件下，相邻时期持有单位资本的实际总回报率$r_{PK,e}[t]$将与银行向资本品生产商贷款获得的实际总回报相等 :

$$
\frac{r_{PK,n}[t+1]}{p_{PK}[t]} \equiv \frac{r_{PK,e}[t+1]}{\pi[t+1]}
$$



























