# 模块之消费品生产商PG020


[TOC]







### 消费品生产商部门

消费品生产商由消费品中间品生产商、消费品最终品生产商构成。为了简化分析消费品生产商，我们将其合并说明。



#### 参考

生产部门融资部分参考：

> 郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产商的DSGE模型分析[J]. 南方经济, (08): 29–46.







#### 模块特点

按照功能划分消费品生产商为以下异质性代表生产商：

- 消费品最终品生产商；
- 消费品中间品生产商；
- 消费品资本品生产商；

定价机制采用被广泛采用的Calvo定价机制；






#### 模块接口



设定全要素生产率（技术）要素：
$$
{TFP}_{PI}[t] := {TFP}_{PG}[t]
$$
设定资本要素：
$$
K_{PI}[i,t] := K_{PG}[i,t]
$$
设定劳动要素：
$$
{Lab}_{PI}[i,t] := {Lab}_{PG}[i,t]
$$
设定生产要素替代指数：
$$
\alpha_{PI} := \alpha_{PG}
$$
设定全要素生产率${TFP}_{PI}[t]​服从的AR(1)过程的随机因子的下标：
$$
\Box_{{TFP},PI} := \Box_{{TFP},PG}
$$


设定工资率：
$$
w_{PI}[t] := w_{PG}[t]
$$


设定资本品生产商$\mathbb{PK}$信贷$B_{PK,B}[t]$，从银行部门$\mathbb{B}$为：
$$
B_{PK,B}[t] := \sum_{j=1}^{N_{B}}{B_{PK,B}[j,t]}
$$
其中，
$B_{PK,B}[j,t]$：资本品生产商$\mathbb{PK}$信贷从银行$j$；



#### 部门假设：

- 假设消费品厂商部门生产的产品在同一时期内都能被消费掉，即无库存；

- 假定对数形式的全要素生产率${TFP}_{\Box}[t]$服从AR(1)过程；

- 资本市场、劳动力市场是完全竞争的。则在消费品中间品生产商中的每一个都将接受给定的工资和资本租金水平；

- TODO

- 在资本品生产部门中，资本品生产商具有竞争性；

  

  





> 关于生产部门的划分，直接参考：

相关构成：

~~企业家：~~

- ~~英文全名：Entrepreneurs；~~
- ~~变量名：entrepreneurs；~~
- ~~数学符号：$\Box_{E}$；~~
- ~~行为：；~~
- ~~目标：~~
- ~~满足的约束条件：~~







##### 构成

消费品生产商；

- 生产中间品的厂商；
- 生产最终品的厂商；
- 资本品生产商；







##### 参考：

消费品中间品生产商构建部分：

> [[马勇, 2013. 植入金融因素的DSGE模型与宏观审慎货币政策规则[J]. 世界经济, (07 vo 36): 68–92.]]
>
> [[马勇, 陈雨露, 2013. 宏观审慎政策的协调与搭配:基于中国的模拟分析[J]. 金融研究, (08): 57–69.]]
>
> 



#### 部门行为

生产部门的行为：

- 生产部门通过外部融资或者购买资本、雇佣劳动生产最终产品；
- 销售最终产品以提供居民部门消费，同时获得销售收入；
- 同时支付工资给居民部门；
- 其外部融资方式主要为从银行部门获得。生产最终产品的过程涉及到生产中间品、生产资本品。







#### 消费品最终品生产商

在一些文献中，消费品最终品生产商之作用，相当于零售商之作用。

英文全名：

Final Goods Producers

变量名：

producers_final

数学符号：

$\Box_{PF}$



##### 假设

- 假设生产消费品最终品的厂商之间是充分竞争的；



##### 行为：

- 接收中间品生产商生产有差别的中间产品，组装生产出无差别的有竞争性质的最终品。

  





##### 模型：



###### 决策目标：

最大化利润，在给定消费品最终品价格$p_{PF}[t]$和中间品价格$p_{PI}[i,t]$时：
$$
{Profit}_{PF}[t] := \max _{Y_{PI}[i,t]} p_{PF}[t] Y_{PF}[t] - \int_{0}^{1} p_{PI}[i, t] Y_{PI}[i, t] \; \mathbb{d} i
\tag{PF_goal}
$$



其中，
$Y_{PF}[t]$：消费品最终品产量；

满足的约束条件：
$$
Y_{PF}[t] := \left(\int_{0}^{1} (Y_{PI}[i,t])^{\frac{\alpha_{PF} - 1}{\alpha_{PF}}} \; \mathbb{d} i\right)^{\frac{\alpha_{PF}}{\alpha_{PF}-1}}
\tag{PF_st}
$$

其中，
$\alpha_{PF}$：替代指数，暨消费品最终品生产商对于不同的由消费品中间品生产商生产的产品的替代指数；

由上述式子可列出拉格朗日函数，通过一阶条件，求得消费品中间品生产商$i$的产出需求$Y_{PI}[i, t]$：
$$
Y_{PI}[i, t] = \left(\frac{p_{PF}[t]}{p_{PI}[i, t]} \right)^{\alpha_{PF}} Y_{PF}[t]
$$



#### 消费品中间品生产商：

英文全名：

Intermediate Goods Producers

变量名：

producers_intermediate

数学符号：

$\Box_{PI}$



##### 假设：

- 假设生产消费品中间品的厂商之间不考虑互相竞争的详细过程；
- 假设生产消费品中间品的厂商的产品是同种类的，具有要素替代性；
- 假设经济中存在一系列连续的消费品中间品生产商$i \in [0,1]$连续统，意味着每一个消费品中间品生产商对该消费品中间品市场的影响都是无穷小的；
- 假设消费品中间品生产商的定价规则遵循Calvo的定价机制。
- 假设每一期从未参与消费品中间品生产商随机抽取比例为 $1-\theta_{PI,p}$数量的厂商参与重新定价；
- 假设消费品中间品生产商$j$参与定价一次$\tilde {P}_{PI}[j,t]$之后，之后不再参与被随机抽取，暨之后不能最优地重新定价；
- 假设未能参与重新定价的消费品中间品生产商的价格根据过去的通胀水平确定其指数化了的价格；
- 假设所有参与重新定价的消费品中间品生产商厂商 $j \in \mathbb{PI_{1}}$  都选择同样的价格 $\tilde{P}_{PI}[t] \equiv \tilde{P}_{PI}[j,t]$；



##### 行为：

- 一个消费品中间品生产商$i$生产$Y_{PI}[i,t]$单位的产品$i$在$t$期，以供最终厂商打包生产最终品。这里的不同的产品$i$是有差别的；

- 获取劳动力要素，从居民部门$\mathbb{H}$；

- 获取资本要素投入，获取渠道为：

  - 自身资本积累；
  - 从资本品生产商$\mathbb{PK}$购买资本；

- 消费品中间品厂商制定最优价格或者调整价格以某种机制；

- 消费品中间品生产商存在信贷约束；

  

  TODO信贷约束：

  $$
  B_{PI,BB}[t] \leq \phi_{BB,PI} E_{t}\left[q_{t+1} h_{t} \pi_{t+1} / R_{t}\right]
  $$

  



##### 模型：



> 根据
>
> [[Calvo G A, 1983. Staggered prices in a utility-maximizing framework[J]. Journal of Monetary Economics, 12(3): 383–398.]]
>
> 设定中间厂商定价机制。



> 详细的推导过程跳转：
>
> [推导消费品中间品生产商较详细的过程](./../详细推导过程/推导消费品中间品生产商.mmd)
>
> 。

假设消费品中间品生产商的个体$i_{PI}$构成的集合为$\mathbb{PI}$，数量为$N_{PI}$。

为了简化分析，在这里，假设消费品中间品厂商的定价机制遵循Calvo定价机制。在第$t$期，随机以一定数量比例$(1 - \theta_{PI,p})$选择生产商$j \in \mathbb{PI_{1}}$，它们在本期参与制定价格为$\tilde{P}_{PI}[j,t]$。假设所有参与重新定价的消费品中间品生产商厂商$j$都选择同样的价格 $\tilde{P}_{PI}[t] \equiv \tilde{P}_{PI}[j,t]$。在当期，其未被选中能够参与制定最优价格之其余厂商个体$k$，构成厂商集合$\mathbb{PI_{2}}$，此时有$k \in \mathbb{PI_{2}}$。未被选中能够参与制定最优价格的厂商$k$则调整价格，其调整价格以总通货膨胀率为基准。

此时中间品生产商的最优化问题中，即包含最大化收益，也包含最小化成本问题，因此分析时考虑分为两个阶段决策。

消费品中间品生产商决策目标分为两阶段：

1. 所有的消费品中间品厂商最小化其总成本；
1. 消费品中间品生产商其可以参与制定价格的，最大化其实际预期贴现利润；





阶段1：最小化总成本。

所有的消费品中间品生产商$i$最小化其总成本$TC_{PI}$，在时期$t$。

$$
{TC}_{PI}[i,t] := \min _{{Lab}_{PI}[i,t] , K_{PI}[i,t]}  w_{PI}[t] \; {Lab}_{PI}[i,t] + r_{PK,PI}[t] \; K_{PI}[i,t]
\tag{PI_goal_010}
$$
其中，
$w_{PI}[t]$：消费品中间品生产商对居民支付单位工资（工资率），在时期$t$；
${Lab}_{PI}[i,t]$：消费品中间品生产商$i$的劳动力要素，在时期$t$；
$r_{PK,PI}[t]$：消费品中间品生产商的消耗单位资本租金率，在时期$t$；
$K_{PI}[i,t]$：消费品中间品生产商$i$的资本，在时期$t$；

这里$K_{PI}[i,t]$的生成方式是：

- 上一期资本折旧累积$(1-\delta_{PI}) \; K_{PI}[i,t-1]$；
- TODO向资本品生产商购买资本$B_{PK}[t]$，以价格$p_{PK}[t]$；



因此，中间品生产商$i$之资本$K_{PI}[i,t]$累积方程表示为：
$$
K_{PI}[i,t] = (1-\delta_{PI}) \; K_{PI}[i,t-1] + K_{PK}[i,t]
\tag{PI_st_K}
$$

其中，
$$
\sum_{i=1}^{N_{PI}}{B_{PI}[i,t]} = B_{PK}[t]
$$


对于整个消费品中间品生产商部门而言，
$$
{TC}_{PI}[t] := \sum_{i=1}^{N_{PF}} {TC}_{PI}[i,t]
$$



###### 约束条件：

最小化成本问题对应约束条件：



生产函数：

消费品中间品生产商之生产函数$F_{PI}[\cdot]$
$$
Y_{PI}[i,t] = F_{PI}[{TFP}_{PI}[t],K_{PI}[i,t],{Lab}_{PI}[i,t]] := {TFP}_{PI}[t] \; (K_{PI}[i,t])^{\alpha_{PI}} \; ({Lab}_{PI}[i,t])^{1-\alpha_{PI}}
$$
其中，
${TFP}_{PI}[t]$：消费品领域生产的全要素生产率（技术）在时期$t$；
$K_{PI}[i,t]$ ：消费品中间品生产商$i$的资本要素；
${Lab}_{PI}[i,t]$：消费品中间品生产商$i$的劳动要素；
$\alpha_{PI}$：消费品中间品生产商各生产要素的替代指数；

假定全要素生产率 ${TFP}_{PI}[t]$ 服从如下形式的一阶自回归AR(1)过程：
$$
\log {TFP}_{PI}[t] = \rho_{{TFP},PI} \log {TFP}_{PI}[t-1] + \varepsilon_{{TFP},PI}[t]
$$

其中，
$\rho_{{TFP},PI}$：消费品中间品生产商的全要素生产率${TFP}_{PI}[t]$对应的自回归过程的回归系数；
$\varepsilon_{{TFP},PI}[t]$：消费品中间品生产商的全要素生产率对${TFP}_{PI}[t]$应的自回归过程的扰动项；



由最优化问题的一阶条件可以得出资本$K_{PI}[i,t]$和劳动${Lab}_{PI}[i,t]$的表达式，然后代入最小化总成本表达式、约束条件，即可得消费品中间品生产商$i$的实际总成本$TC_{PI}[t]$，然后可以得到消费品中间品生产商$i$共有的实际边际成本$MC_{PI}[t]$：
$$
MC_{PI}[t]
:= \frac{TC_{PI}[t]}{Y_{PI}[t]}
= \left( 1-\alpha_{PI} \right)^{\alpha_{PI} -1} \; (\alpha_{PI})^{-\alpha_{PI}} \; \frac{(w_{PI}[t])^{1-\alpha_{PI}} \; (r_{PK,PI}[t])^{\alpha_{PI}}}{{TFP}_{PI}[t]}
$$





> 企业收支平衡约束
> 借鉴：
> 林琳, 曹勇, 肖寒, 2016. 中国式影子银行下的金融系统脆弱性[J]. 经济学(季刊), (03 vo 15): 1113–1136.

TODO消费品中间品生产商应满足收支平衡约束：
  $$
  Y_{PI}[t] + K_{PK}[t]=I_{t}+C_{t}^{f}+W_{t} N_{t}+\frac{R_{t-1}^{l} L_{t-1}}{\pi_{t}}+\frac{R_{t-1}^{s} S_{t-1}}{\pi_{t}}
  $$





阶段2：制定最优价格以最大化总利润。

基于时期$t$，参与制定最优价格的消费品中间品生产商$j \in \mathbb{PI_{1}}$，通过制定最优价格最大化其实际预期贴现利润在时期$t_{s}$，暨在时期$t+t_{s}, \quad t_{s} \in [t,\infty)$。

另外，未能参与制定最优价格$\tilde{P}_{PI}[j,t]$之消费品中间品生产商$k \in \mathbb{PI_{2}}$根据过去的通货膨胀率$\pi[t-1]$确定其指数化价格为
$$
p_{PI}[k,t]=(\pi[t-1])^{\chi_{p}} \; p_{PI}[j,t-1]
$$
其中，
$\chi_{p} \in[0,1]$ ：指数化程度参数；
$\pi[\cdot]$：通货膨胀率于特定时期，其定义为
$$
\pi[t] := \frac{P[t]}{P[t-1]}
$$

其中，
$P[\cdot]$：表示物价于特定时期；



因为对于未参与定价的消费品中间品生产商$k$，价格之调整以总通货膨胀率为基准，所以消费品最终品生产商的定价规则为
$$
p_{PF}[t] = \theta_{PI,p} \; \left( (\pi[t+t_{h}-1])^{\chi_{p}} \; p_{PF}[t-1] \right)   + (1-\theta_{PI,p}) \; p_{PI}[j,t]
$$

由于我们采用的Calvo定价规则，假设了在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取所占比例为 $(1-\theta_{PI,p})$数量的厂商参与重新定价。此时意味着在时期$t$，被随机抽取中参与重新定价的厂商的数量占比为$(1 - \theta_{PI,p})$。

假设消费品中间品生产商$j$参与定价一次$\tilde{P}_{PI}[j,t]$之后，之后不再参与被随机抽取，暨之后不能最优地重新定价，从而该消费品中间品生产商$j$的价格$p_{PI}[j,t+t_{s}]$在时期$t+t_{s} \quad t_{s} \in [t,\infty)$为

$$
p_{PI}[j,t+t_{s}] = \prod_{t_{h}=1}^{t_{s}} 
\left(
	(\pi[t+t_{h}-1])^{\chi_{p}} 
\right)	
\; \tilde{P}_{PI}[j,t]
$$

消费品中间品生产商个体$j$面临的最大化问题是：

$$
\begin{align*}
& \max _{\tilde{P}_{PI}[j,t]} {Profit}_{PI}[j,t] \\
:= & \max _{\tilde{P}_{PI}[j,t]} 
\mathbb{E}_{t} \sum_{t_{s}=0}^{\infty}
\left(
(\gamma_{PI})^{t_{s}} \; (\theta_{PI,p})^{t_{s}}
\; \left(\frac{p_{PF}[t+t_{s}]}{		
			\prod_{t_{h}=1}^{t_{s}} 
      \left(
      (\pi[t+t_{h}-1])^{\chi_{p}} 
      \right)	
			\; \tilde{P}_{PI}[j,t]
    } \right)^{\alpha_{PF}} Y_{PF}[t+t_{s}]
	\;
	\left(
		\prod_{t_{h}=1}^{t_{s}} 
		\left(
		(\pi[t+t_{h}-1])^{\chi_{p}} 
		\right)	
		\; \tilde{P}_{PI}[j,t]
		- MC_{PI}[t + t_{s}]
	\right)
\right)
\end{align*}
\tag{PG_goal}
$$

其中，
$\gamma_{PI}$：消费品中间品生产商之效用贴现因子；
$\theta_{PI,p}$：在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取一定数量的厂商以参与重新定价，剩余仍未被抽取中以参与重新定价的厂商数量所占的比例；
$\alpha_{PF}$：消费品中间品生产商不同的产品的替代弹性；


上述最优化问题对应的约束条件是消费品中间品生产商$i$的产量需求：

$$
\text { s. t. } 
\quad Y_{PI}[i,t+t_{s}] = 
\left(
	\prod_{t_{h}=1}^{t_{s}} \left( (\pi[t + t_{h} - 1])^{\chi_{p}} \right) \frac{\tilde{P}_{PI}[t]}{p_{PF}[t+t_{s}]}
\right)^{-\alpha_{PF}} 
\; Y_{PF}[t+t_{s}]
$$

产量需求的约束意味着消费品中间品生产商将在每一期中生产该期价格下所需求的全部产品。

最优化问题对应的一阶条件：
$$
\tilde{P}_{PI}[t] =
\frac{\alpha_{PF}}{\alpha_{PF}-1} 
\frac
{
\mathbb{E}_{t} 
\sum \limits_{t_{s}=0}^{\infty}
	\left(
		\left(\gamma_{PI} \; \theta_{PI,p} \right)^{t_{s}} \; p_{PF}[t+t_{s}] \; MC_{PI}[t+t_{s}] \; Y_{PF}[i, t+t_{s}]
	\right)
}
{
\mathbb{E}_{t} \sum \limits_{t_{s}=0}^{\infty}
	\left(
		\left(\gamma_{PI} \; \theta_{PI,p} \right)^{t_{s}} 
		\; \prod \limits_{t_{h}=1}^{t_{s}} 
			\left(  
				(\pi[t+t_{h}-1])^{\chi_{p}} 
			\right)  
		\; Y_{PI}[i, t+t_{s}]
	\right)
}
$$

其中，
$MC_{PI}[t+t_{s]}$：消费品中间品生产商的实际边际成本。

根据消费品中间品生产商的产量$Y_{PI}[i,t]$与$Y_{PF}[t]$的关系
$$
Y_{PI}[i, t] = \left(\frac{p_{PI}[i, t]}{p_{PF}[t]} \right)^{-\alpha_{PF}} Y_{PF}[t]
$$
，然后采用Uhlig提出的对数线性化的方法，经过推导，可得消费品中间品生产商之价格水平的时变表达式

$$
(p_{PF}[t])^{1-\alpha_{PF}}
= \theta_{PI,p} \; \left((\pi[t-1])^{\chi_{p}} \; P[t-1] \right)^{1-\alpha_{PF}} + (1-\theta_{PI,p}) \; \left(\tilde{P}_{PI}[t]\right)^{1-\alpha_{PF}}
$$

通过对数线性化上面两个式子，并采用差分方法消除对未来期望值的无穷加总项，经过推导，最终可以得到如下形式的混合型新凯恩斯菲利普斯曲线（hybrid NKPC）

$$
\hat{\pi}[t] =
\frac{\gamma_{PI}}{1+\gamma_{PI} \;\chi_{p}} \mathbb{E}_{t} \; \hat{\pi}[t+1]
+
\frac{\chi_{p}}{1+\gamma_{PI} \; \chi_{p}} \; \hat{\pi}[t-1]
+
\frac
{
\left( 1-\theta_{PI,p} \right) \; \left( 1-\gamma_{PI} \; \theta_{PI,p} \right)
}{
\theta_{PI,p}\left(1+\gamma_{PI} \; \theta_{PI,p}\right)
} 
\; \hat{MC}_{PI}[t]
$$

其中，
$\hat{\Box}$：上标带尖冒号表示相应变量偏离比例相对于其其稳态值；

特别地，当 $\chi_{p}=0$ 时，上式变成前瞻型的新凯恩斯菲利普斯曲线( forward-looking NKPC)。通过引入混合性的菲利普斯曲线,有利于更好地对真实的通货膨胀过程及其动态机制进行刻画。















#### TODO资本品生产商


英文全名：

Capital Goods Producers

变量名：

producers_capital

数学符号：

$\Box_{PK}$



>资本品生产商的建模描述主要参考
>
>[[马勇, 2013. 植入金融因素的DSGE模型与宏观审慎货币政策规则[J]. 世界经济, (07 vo 36): 68–92.]]
>
>其中，(马勇, 2013)参考了
>
>[[Faia E, Monacelli T, 2007. Optimal Interest Rate Rules, Asset Prices, and Credit Frictions[J]. Journal of Economic Dynamics and Control, 31(10): 3228–3254. DOI:[10.1016/j.jedc.2006.11.006](https://doi.org/10.1016/j.jedc.2006.11.006).]]



##### 引入原因

引入资本品生产商，用以引入资本调整成本，以相对方便处理的形式。



##### 行为：

- 具有竞争性的生产资本品生产商$i$利用投资和现有资本存量生产新的资本品，这样的生产将耗费一定的物质转换成本。
- 资本品生产商获取资本渠道：
  - 金融中介机构：
    - 银行部门；
  - 外部融资：
    - 通过证券市场融资；







##### 模型：



资本品生产商作为经济系统中投资的重要一个代表，其资本投资获取渠道如下：

- 信贷融资比例$\phi_{CF,PK}$，信贷总规模$CF_{PK}[t] = \phi_{CF,PK}[t] \; p_{PK}[t] \; L_{PK}[t]$；
  - 从政府信贷占比$\phi_{CF,G}[t]$，对应信贷规模$\phi_{CF,G}[t] \; \phi_{CF,PK}[t] \; p_{PK}[t] \; L_{PK}[t]=B_{G}[t]$；
  - 商业银行部门信贷占比$\phi_{CF,BB}[t]$，对应信贷规模$\phi_{CF,PK}[t] \; \phi_{CF,BB}[t] \; p_{PK}[t] \; L_{PK}[t] = B_{PK,BB}[t]$；
  - 影子银行部门信贷占比$\phi_{CF,BS}[t]$，对应信贷规模$\phi_{CF,PK}[t] \; \phi_{CF,BS}[t] \; p_{PK}[t] \; L_{PK}[t] = B_{PK,BS}[t]$；

- 股票市场融资项目比例$(1-\phi_{CF,PK})$，对应信贷规模$D F_{PK}[t]=(1-\phi_{CF,PK}[t]) \; p_{PK}[t] \; L_{PK}[t]$；



银行存款的贷存比：
$$
d_{BB}[t] := \frac{deposit_{BB}[t]}{credit_{BB}[t]}
$$
资本比率：
$$
k_{BB}[t] := 1-d_{BB}[t] = \frac{credit_{BB}[t] - deposit_{BB}[t]}{credit_{BB}[t]} = \frac{equity_{BB}[t]}{credit_{BB}[t]}
$$


项目回报：
$$
\bar{R}=R_t^p+\varepsilon_t
$$




###### 目标：

资本生产部门的决策问题：

$$
{Profit}_{PK}[t] := \max _{I_{PK}[t]} \quad p_{PK}[t] \; F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right] \; K_{PK}[t]-p_{PF}[t] \; I_{PK}[t]
$$





###### 约束条件：

设定资本调整成本方程（capital adjustment cost function）$F_{PK}$形式为CRS（具有一次齐次假设的）：
$$
F_{PK}\left[\frac{I_{PI}[t]}{K_{PI}[t]}\right] \; K_{PI}[t]
$$

> 根据（Gertler,2007）（Mimir,2010）等人研究，

设定为：
$$
F_{PK}\left[\frac{I_{PI}[t]}{K_{PI}[t]}\right] := \frac{I_{PI}[t]}{K_{PI}[t]} - \frac{\eta_{PK}}{2}\left(\frac{I_{PI}[t]}{K_{PI}[t]}-\delta_{PK}\right)^{2}
$$
其中，
$\eta_{PK}$：资本调整成本参数；
$\delta_{PK}$：资本品折旧率；

则对应的时变的资本累积方程为
$$
K_{PK}[t+1]=(1-\delta_{PK}) K_{PK}[t]+F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right] K_{PK}[t]
$$



###### 求解：

其中一阶条件：
$$
p_{PK}[t] \; {F_{PK}}^{\prime} \left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]=p_{PF}[t]
$$

全要素生产率${TFP}_{PK}[t]$服从AR(1)过程：

$$
\log {TFP}_{PK}[t]=\rho_{{TFP},PK} \log {TFP}_{PK}[t-1] + \varepsilon_{{TFP},PK}[t]
$$

其中，$\varepsilon_{{TFP},PK}[t]$ 服从标准差为$\sigma_{{TFP},PK}$的i.i.d.冲击。

相邻时期持有单位资本的名义总回报率$r_{PK,n}[t]$的计算如下，

$$
\begin{align*}
r_{PK,n}[t] & := r_{PK,PI}[t] + p_{PF}[t] \; 
\frac
{
	\partial \; K_{PK}[t+1]
}{
	\partial \; K_{PK}[t]
}
\\
& = r_{PK,PI}[t] + p_{PF}[t] \left((1-\delta_{PK}) - F_{PK} \left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]   \; \frac{I_{PK}[t]}{K_{PK}[t]}+F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]\right)
\end{align*}
$$

> TODO：如何求得均衡条件？

在均衡条件下，相邻时期持有单位资本的实际总回报率$r_{PK,e}[t]$将与银行从其贷款获得的实际总回报相等 :

$$
\frac{r_{PK,n}[t+1]}{p_{PK}[t]} \equiv \frac{r_{PK,e}[t+1]}{\pi[t+1]}
$$































