# 系统性金融风险建模



## 定义DSGE模型框架之全局的变量和参数



### TODO定义变量之数学符号



#### 标记：

$\bar{\Box}$：上标带横线号表示相关变量之稳态值；

$\hat{\Box}$：上标带尖冒号表示相关变量偏离比例相对于其稳态值；

$\tilde{\Box}$：上标带波浪号表示相关变量的特殊状态（具体情况具体定义）。例如，可以表示经济体的目标需求量和供应量；

$\check{\Box}$：上标带倒尖冒号表示相关变量锚定值。例如，在监管约束中，表示目标监管值；

$\Box_{\Box}[\cdot]$：符号的主要部分表示各种变量的主体部分，符号的下标表示主体的类别，方括号内的部分表示自变量；

其中，

$\Box_{\Box}[i,t]$：表示个体$i$的某个变量，在时期$t$；

$\Box_{\Box}[t]$：表示加总的个体$i$在某部门的某个变量，在时期$t$；

$\Box_{\Box}[i]$：表示个体$i$的某个变量，可以不包含时期信息；

$\Box_{\Box}$：表示参数，无个体和时期信息；

$\mathcal{Pr}$：表示概率；

$“:=”$：表示定义；



#### 主体：

$\Box_{H}$：整体居民部门；

- $\mathbb{H}$：集合，由整体居民部门个体构成；
- $N_{H}$：数量之于居民个体；
- $\theta_{H}$：数量占比之于居民部门类型；




$\Box_{P}$：整体生产部门；

- $\mathbb{P}$：集合，由整体生产部门个体构成；



$\Box_{HB}$：借款型居民；

- $i_{HB}$：单个个体之于借款型居民。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{HB}$：集合，由借款型居民个体构成；
- $N_{HB}$：数量之于借款型居民个体；



$\Box_{HI}$：投资和储蓄型居民；

- $i_{HI}$：单个个体之于投资和储蓄型居民。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{HI}$：集合，由投资和储蓄型居民个体构成；
- $N_{HI}$：数量之于投资和储蓄型居民个体；





$\Box_{PF}$：消费品最终品生产商；

- $i_{PF}$：单个个体之于消费品最终品生产商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PF}$：集合，由消费品最终品生产商个体构成；
- $N_{PF}$：数量之于消费品最终品生产商个体；



$\Box_{PI}$：消费品中间品生产商；

- $i_{PI}$：单个个体之于消费品中间品生产商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PI}$：集合，由消费品中间品生产商个体构成；
- ~~$N_{PI}$：数量之于消费品中间品生产商个体；~~
- $i_{PI,1}$：可以参与制定最优价格的单个个体之于消费品中间品生产商，在当期的时候。在已作出说明的情况下，可以用$j$表示；
- $\mathbb{PI_{1}}$：集合，由可以参与制定最优价格的消费品中间品生产商个体构成，在当期的时候；
- ~~$N_{PI,1}$：数量之于可以参与制定最优价格的消费品中间品生产商个体，在当期的时候；~~
- $i_{PI,2}$：不能参与制定最优价格的单个个体之于消费品中间品生产商，在当期的时候。在已作出说明的情况下，可以用$k$表示；
- $\mathbb{PI_{2}}$：集合，由不能参与制定最优价格的消费品中间品生产商个体构成，在当期的时候；
- ~~$N_{PI,2}$：数量之于不能参与制定最优价格的消费品中间品生产商个体，在当期的时候；~~






$\Box_{PK}$：资本品生产商；

- $i_{PK}$：单个个体之于资本品生产商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PK}$：集合，由资本品生产商个体构成；
- $N_{PK}$：数量之于资本品生产商个体；







$\Box_{PE}$：房地产开发商；

- $i_{PE}$：单个个体之于房地产开发商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PE}$：集合，由房地产开发商个体构成；
- $N_{PE}$：数量之于房地产开发商个体；





$\Box_{BB}$：商业银行；

- $i_{BB}$：单个个体之于商业银行。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{BB}$：集合，由商业银行个体构成；
- $N_{BB}$：数量之于商业银行个体；





$\Box_{BI}$：商业银行间市场（银行间市场）；

商业银行间市场，由$N_{BB}$个商业银行$i,i \in \{1,\cdots,N_{BB}\}$构成的矩阵$X_{BI}[t]$，来描述银行间市场交易行为的网络：
$$
X_{BI}[t]:=\begin{pmatrix}
x_{1,1}[t] & \cdots & x_{1,j}[t] & \cdots & x_{1,N_{BB}}[t] \\
\vdots & \ddots & \vdots & \cdots & \vdots \\
x_{i,1}[t] & \cdots & x_{i,j}[t] & \cdots & x_{i,N_{BB}}[t] \\
\vdots & \therefore & \vdots & \ddots & \vdots \\
x_{N_{BB},1}[t] & \cdots & x_{N_{BB},j}[t] & \cdots & x_{N_{BB},N_{BB}}[t]
\end{pmatrix}
$$

其中，
矩阵$X_{BI}[t]$：表示时期$t$，银行间市场交易行为的网络；
元素$x_{i,j}[t]$：表示时期$t$，银行$i$对银行$j$之间的信息；

$X_{BI}[t]$的具体信息根据实际情况而定。





#### 状态：



##### 损失：

${Loss}_{\Box}[i,t]$：部门$\Box$个体$i$之损失金额，在时期$t$；



##### 破产：

${Bankrupt}_{\Box}[i,t]$：部门$\Box$个体$i$之破产状态，在时期$t$；







#### 消费：

$C_{\Box}[i,t]$：个体$i$消费，在时期$t$；

$C_{\Box}[t]$：加总所有个体的消费，在时期$t$；

其中，各下标表示含义如下：

- $C_{HB}[t]$：借款型居民之消费需求，在时期$t$；
- $C_{HB,PG}[t]$：借款型居民之消费品消费，在时期$t$；
- $C_{HB,PE}[t]$：借款型居民之房地产消费，在时期$t$；
- $C_{HI}[t]$：投资和储蓄型居民之消费需求，在时期$t$；
- $C_{HI,PG}[t]$：投资与储蓄型居民之消费品消费，在时期$t$；
- $C_{HI,PE}[t]$：投资与储蓄型居民之房地产消费，在时期$t$；







#### 收入：



$Income_{H}[t]$：居民部门$\mathbb{H}$当期总收入；



#### 工资率：

$w_{\Box}[i,t]$：居民获得的单位工资，暨工资率。同时也是生产商支付给居民的单位工资，在时期$t$；

其中，各下标含义表示如下：

- $w_{PG}[t]$：消费品中间品生产商支付单位工资给居民，在时期$t$；
- $w_{PE}[t]$：房地产开发商支付单位工资给居民部门，在时期$t$；



#### 转移支付：

${Trans}_{\Box}[i,t]$：居民获得的转移支付，在时期$t$；



#### 股利分红：

$Dv_{BB}[i,t]$：商业银行$i$之股利分红；

$\theta_{BB,Dv}[i,t]$：商业银行$i$的当期分红策略（所得经营利润之分红比例）；



#### 管理费用：

${Manage}_{BB}[i,t]$：商业银行$i$支付给管理部门的工资；





#### 劳动时长：



$Hour_{\Box}[i,t]$：个体$i$工作时长，在时期$t$；

$Hour_{\Box}[t]$：加总个体居民工作时长，在时期$t$；

其中，各下标表示含义如下：

- ${Hour}_{H}[t]$：居民部门$H$之个体$i \in \{ \mathbb{HB}, \mathbb{HI} \}$之工作时长，在时期$t$；

- $Hour_{H,P}[i,t]$：居民部门$H$之个体$i \in \{ \mathbb{HB}, \mathbb{HI} \}$，在生产部门$\mathbb{P}$之子部门之一$\mathbb{P} = \{ \mathbb{PG}, \mathbb{PE} \}$之工作时长，在时期$t$；













#### 通货膨胀：

$\pi[t]$：通货膨胀率，在时期$t$；

定义为
$$
\pi[t] := \frac{P[t]}{P[t-1]}
$$

其中，
$P[t]$：表示物价，在时期$t$；





#### 生产函数：



$F_{\Box}$：生产函数；

其中，各下标表示含义如下：

- $F_{PG}[{TFP}_{PG}[t],K_{PG}[t],{Lab}_{PG}[t]]$：消费品生产商的生产函数；

- $F_{PI}[{TFP}_{PI}[t],K_{PI}[i,t],{Lab}_{PI}[i,t]]$：消费品中间品生产商的生产函数；
- $F_{PK}$：资本品生产商的资本生产函数；
- $F_{PE}[{TFP}_{PE}[t],K_{PE}[t],{Lab}_{PE}[t],H_{PE}[t]]$：房地产开发商的生产函数；



#### 产出：

$Y_{\Box}[\cdot]$：产出；

其中，各下标含义表示如下：

- $Y_{PF}[t]$：消费品最终品产量，在时期$t$；

- $Y_{PE}[t]$：房地产开发商的产出，在时期$t$；

- $Y_{PI}[i, t]$：消费品中间品生产商$i$的产出需求，在时期$t$；

  

#### 全要素生产率：

$TFP[\cdot]$：全要素生产率；

其中，各下标含义表示如下：

- ${TFP}_{PI}[t]$：消费品中间品生产商的全要素生产率，在时期$t$；

- ${TFP}_{PK}[t]$：资本生产部门的全要素生产率，在时期$t$；

- ${TFP}_{PE}[t]$：房地产开发商的全要素生产率，在时期$t$；






#### 资本：

$K_{\Box}[i,t]$：各部门个体$i$之资本要素，在时期$t$；

$K_{\Box}[t]$：各部门总体之资本要素，在时期$t$；

其中，各下标含义表示如下：

- $K_{PE}[t]$：房地产开发商整体之资本存量，在时期$t$；
- $K_{PI}[i,t]$：消费品中间品生产商$i$的资本，在时期$t$；
- $K_{PK}[t]$：资本品生产商整体之资本，在时期$t$；
- $K_{BB}[t]$：商业银行部门整体之自有资本，在时期$t$；



$r_{PK,PI}[t]$：消费品中间品生产商的消耗单位资本租金率，在时期$t$。该费率制定者是资本品生产商；



${Lab}_{\Box}[t]$：生产部门整体获取劳动要素，从居民部门整体，于时期$t$；

其中，各下标含义表示如下：

- ${Lab}_{P}[t]$：生产部门$\mathbb{P}$之子部门整体$P \in \{ \mathbb{PG}, \mathbb{PI}, \mathbb{PE} \}$投入劳动要素，于时期$t$；
- ${Lab}_{P,H}[t]$：生产部门$\mathbb{P}$之子部门整体$P \in \{ \mathbb{PG}, \mathbb{PI}, \mathbb{PE} \}$投入劳动要素，其劳动力从居民部门$\mathbb{H}$之子部门$H = \{\mathbb{HB}, \mathbb{HI} \}$之一获取，于时期$t$；
- 







$I_{\Box}[\cdot]$：投资；

其中，各下标含义表示如下：

- $I_{PE}[t]$：房地产开发商的投资，在时期$t$；





#### 价格：

$p_{\Box}[\cdot]$：消费者接受的价格；

其中，各下标含义表示如下：

- $p_{PE}[t]$：住房价格，在时期$t$；
- 



$p_{\Box}[\cdot]$：生产部门个体制定或者调整的价格；

其中，各下标含义表示如下：

- $p_{PF}[t]$：消费品最终品的价格，在时期$t$；
- $p_{PI}[j,t]$：价格，其由具有制定价格能力的消费品中间品生产商$j$制定；
- $\tilde{P}_{PI}[t]$：相同的价格之消费品中间品生产商总体制定的，于定价阶段，在时期$t$；
- $p_{PE}[t]$：房地产价格，在时期$t$；
- $p_{PK}[t]$：资本品生产部门制定的资本出售价格，在时期$t$；





#### 储蓄：

$D_{\Box}[i,t]$：个体$i$在银行的储蓄；

其中，各下标表示含义如下：

- 居民部门个体$j$存款资金$D_{H}[j,i,t]$至商业银行$i$；

- $D_{H,s}[\Box]$：居民部门短期存款；

- $D_{H,l}[\Box]$：居民部门长期存款；

  

$r_{BB,HI}[i,t]$：银行提供存款利率以供居民部门存款；








$\tilde{D}_{BB,H}[i,t]$：银行$i$计划接受来自居民部门的储蓄量；



#### 资产负债表：



##### 资产：

${Asset}_{\Box}$：资产；

其中，各下标表示含义如下：

${Asset}_{p,q}[t]$：部门$p$之拥有部门$q$之资产，在时期$t$；

${Asset}_{p,q}[i,j,t]$：部门$p$之个体$i$，其拥有来自部门$q$之个体$j$之资产，在时期$t$；

举例：

${Asset}_{BB,HB}[i,j,t]$：商业银行部门$\mathbb{BB}$之商业银行个体$\mathbb{BB}_i$，其拥有贷给借款型居民部门$\mathbb{HB}$之个体$\mathbb{HB}_i$之资产，在时期$t$；

资产有时候也用$A_{\Box}$表示；



损失：

${Loss}_{BB,A}[i,t]$：假设银行$i$在时期$t$遭受资产损失冲击；

${Asset}_{BB,Loss}[i,t]$：假设银行$i$在时期$t$遭受资产损失冲击；



##### 负债：

${Liability}_{\Box}$：负债；

其中，各下标表示含义如下：

${Liability}_{p,q}[t]$：部门$p$之拥有部门$q$之负债，在时期$t$；

${Liability}_{p,q}[i,j,t]$：部门$p$之个体$i$，其拥有来自部门$q$之个体$j$之负债，在时期$t$；

举例：

${Liability}_{PE,BB}[i,j,t]$：房地产商部门$\mathbb{PE}$之房地产商个体$\mathbb{PE}_i$，其拥有负债，来自商业银行部门$\mathbb{BB}$之个体$\mathbb{BB}_i$之贷款，在时期$t$；



##### 资本：

${Equity}_{\Box}$：权益（资本）；

其中，各下标表示含义如下：

${Equity}_{BB}[i,t]$：商业银行$i$权益，在时期$t$；













#### 借贷：



$B_{\Box}[j,i,t]$：部门个体$j$从部门$i$获取的借款；

$B_{\Box}[i,t]$：部门整体从部门$i$获取的借款；

$B_{\Box}[t]$：部门整体从部门$i$获取的借款；

其中，各下标表示含义如下：

- $B_{HB,BB}[t]$：借款型居民部门从商业银行$i$借款，在时期$t$；

- $B_{PG,B}[t]$：消费品生产商部门从银行部门$\mathbb{B}$获得总借款，在时期$t$；

- $B_{PG,BB}[i,t]$：消费品生产商部门从银行部门$\mathbb{B}$之商业银行$i$借款，在时期$t$；

- $B_{PG,BS}[j,t]$：消费品生产商部门从银行部门$\mathbb{B}$之影子银行$j$借款，在时期$t$；

- $B_{PK,B}[t]$：资本品生产商部门从银行部门$\mathbb{B}$获得总借款，在时期$t$；

- $B_{PK,BB}[i,t]$：资本品生产商部门从银行部门$\mathbb{B}$之商业银行$i$借款，在时期$t$；

- $B_{PK,BS}[j,t]$：资本品生产商部门从银行部门$\mathbb{B}$之影子银行$j$借款，在时期$t$；

- $B_{PG,B}[t]$：房地产开发商部门从银行部门$\mathbb{B}$获得总借款，在时期$t$；

- $B_{PE,BB}[t]$：房地产开发商部门从银行部门$\mathbb{B}$之商业银行$i$借款，在时期$t$；

- $B_{PE,BS}[j,t]$：消费品生产商部门从银行部门$\mathbb{B}$之影子银行$j$借款，在时期$t$；

- $B_{BB,G}[i,t]$：商业银行$i$获取政府部门之中央银行$\mathbb{G}$贴现获得借款资金$B_{BB,G}[i,t]$，于当期；

  



$Repay_{\Box}[t]$：部门偿还借款量；

其中，各下标表示含义如下：

- $Repay_{PG}[t]$：代表性消费品生产商偿还总借款量，在时期$t$；

- $Repay_{PG,B}[t]$：代表性消费品生产商偿还借款量给银行部门$\mathbb{B}$，在时期$t$；

  





#### 粘性成本：

${Adj}_{BB,A}\left[{ABS}_{BS}[t],L_{BB,BK}[t]\right]$：同期信贷资产调整成本函数；



${LR}_{BB}[i,t]$：商业银行$i$之杠杆率；



${ABS}_{BS}[j,i,t]$：商业银行$i$购买影子银行$j$提供的资管产品，在时期$t$；





#### 投资：



$I_\Box$：投资；

$I_{PK}$：资本品生产商的资本投资量；

$I_{PG}[t]$：表示代表性消费品生产商之投资量；





#### 违约：

$\mathcal{Pr}_{def,\Box}[t]$：违约概率，在时期$t$；

其中，各下标表示含义如下：

$\mathcal{Pr}_{def,BS}[j,i,t]$：影子银行$j$对商业银行$i$之违约概率，在时期$t$；

$\mathcal{Pr}_{def,PG}[i,t]$：消费品生产商部门对商业银行个体$i$之违约概率，在时期$t$；



#### 利率：



$r_{\Box}[\cdot]$：利率；

其中，各下标表示含义如下：

$r_{macro}[t]$：宏观的无风险利率；

$r_{BB,HB}[i,t]$：商业银行$i$对借款型居民部门的贷款利率，暨借款型居民从商业银行借款利率；

$r_{BB,HI}[i,t]$：居民部门存款于商业银行$i$，商业银行提供的存款利率；

$r_{BB,PK}[i,t]$：商业银行$i$对资本品生产商的贷款利率，暨资本品生产商对商业银行借款利率；

$r_{BB,PG}[i,t]$：商业银行$i$对消费品生产商的贷款利率，暨消费品生产商对商业银行借款利率；

$r_{BB,P}[i,t]$：商业银行$i$对生产部门的贷款利率，暨生产部门对商业银行借款利率；

$r_{BB,HB}[i,t]$：商业银行$i$对借款型居民的贷款利率，暨借款型居民对商业银行借款利率；





#### 监管要求：



##### 资本充足率：

$\check{\phi}_{CAR}$：商业银行资本充足率（Capital Adequacy Ratio）要求；

$Pun_{CAR}[i,t,gap_[i,t]]$：不满足规定资本充足率要求对应的惩罚函数；



##### 贷存比：

$\check{\theta}_{CAR,BB}[t]$：商业银行贷存比要求（Loan-to-Deposit Ratio）；

$Pun_{{LDR}}[i,t,gap_[i,t]]$：不满足规定贷存比要求对应的惩罚函数；



##### 存款准备金：

$\Box_{DR}$：商业银行存款准备金要求（Deposit Reserve）；

$\check{\theta}_{DR}$：商业银行存款准备金率要求；



~~$\theta_{LTV}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{LTV}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；~~







#### 随机过程变量：







##### 自回归过程：

$\varepsilon_{\Box}[t]$：自回归过程的扰动项；

其中，各下标表示含义如下：

$\varepsilon_{{TFP},\Box}[t]$：扰动项之于自回归过程之于生产部门各子部门之全要素生产率${TFP}_{\Box}[t]$，在时期$t$；

$\varepsilon_{{TFP},PI}[t]$：扰动项之于自回归过程之于生产部门之消费品生产商之中间品生产商之全要素生产率${TFP}_{PI}[t]$，在时期$t$；

$\varepsilon_{H,c}[t]$：扰动项之于居民部门之消费品消费，在时期$t$；

$\varepsilon_{H,h}[t]$：扰动项之于居民部门之住房消费，在时期$t$；

$\varepsilon_{{TFP},PK}[t]$：扰动项之于自回归过程之于生产部门之资本品生产商之全要素生产率${TFP}_{PK}[t]$，在时期$t$；

$\varepsilon_{c_{BB,P}}[t]$：扰动项之于自回归过程之于商业银行为贷款给企业付出审查成本率$c_{BB,P}[t]$，在时期$t$；

$\varepsilon_{BB,K}[t]$：商业银行资本金融冲击随机变量；





##### 自回归系数：


$\rho_{\Box}$：自回归过程的回归系数；

其中，各下标表示含义如下：

- $\rho_{{TFP},\Box}$：生产部门各子部门的全要素生产率${TFP}_{\Box}[t]$对应的自回归过程的回归系数；
- $\rho_{{TFP},PI}$：消费品中间品生产商的全要素生产率${TFP}_{PI}[t]$对应的自回归过程的回归系数；
- $\rho_{H,c}[t]$：扰动项之于居民部门之消费品消费，在时期$t$；
- $\rho_{H,h}[t]$：扰动项之于居民部门之住房消费，在时期$t$；
- $\rho_{{TFP},PK}$：消费品中间品生产商的全要素生产率${TFP}_{PK}[t]$对应的自回归过程的回归系数；
- $\rho_{c_{BB,P}}$：商业银行为贷款给企业付出审查成本率$c_{BB,P}[t]$对应的自回归过程的回归系数；



##### 扰动变量标准差：

$\sigma_{\Box}$：扰动变量对应的标准差，当其扰动项服从正态分布时；

其中，各下标含义表示如下：

- $\sigma_{{TFP},PI}$：标准差之于扰动项之于消费品中间品生产商的生产技术，其服从正态分布；
- $\sigma_{H,c}[t]$：标准差之于扰动项之于居民部门之消费品消费，在时期$t$；
- $\sigma_{H,h}[t]$：标准差之于扰动项之于居民部门之住房消费，在时期$t$；
- $\sigma_{{TFP},PK}[t]$：标准差之于扰动项之于自回归过程之于生产部门之资本品生产商之全要素生产率${TFP}_{PK}[t]$，在时期$t$；
- $\sigma_{c_{BB,P}}[t]$：标准差之于扰动项之于自回归过程之于商业银行为贷款给企业付出审查成本率$c_{BB,P}[t]$，在时期$t$；







#### 折旧：

$\delta$：折旧率：

其中，各下标表示含义如下：

- $\delta_{PG}$：折旧率之于代表性消费品生产商之资本；
- $\delta_{PK}$：折旧率之于资本品生产商之资本品；
- $\delta_{PI}$：折旧率之于消费品中间品生产商之资本；
- $\delta_{PE}$：折旧率之于房地产商之商品；
- $\delta_{BB}$：折旧率之于商业银行资本；





#### 常见参数和变量



##### 角色转换率：

$λ_{\Box}$：居民成员角色中转换为普通居民的转换率（满足泊松过程）；

其中，各下标表示含义如下：

- ~~下标为$e$：企业家转换为普通居民的转换率；~~
- ~~下标为$b$：银行家转换为普通居民的转换率；~~



##### 跨期贴现因子：

$\gamma_{\Box}$：效用的跨期贴现因子；

其中，各下标表示含义如下：

- $\gamma_{HB}$：借款型居民之效用贴现因子；
- $\gamma_{HI}$：投资于储蓄型居民之效用贴现因子；
- $\gamma_{PI}$：消费品中间品生产商之效用贴现因子；
- $\gamma_{PE}$：房地产开发商之效用贴现因子；





##### 偏好：

$\alpha_{\Box}$：替代指数、偏好参数；

其中，各下标表示含义如下：

- $\alpha_{HB,PG}$：消费型居民消费品消费行为偏好参数；
- $\alpha_{HI,PG}$：投资和储蓄型居民消费品消费行为偏好参数；
- $\alpha_{HB,PE}$：消费型居民住房消费行为偏好参数；
- $\alpha_{HI,PE}$：投资和储蓄型居民住房消费行为偏好参数；
- $\alpha_{PF}$：替代指数。消费品最终品生产商对于不同的由消费品中间品生产商生产的产品的替代指数；
- $\alpha_{PI}$：消费品中间品生产商的替代指数；
- $\alpha_{PE,K}$：房地产开发商投入资本要素所占的替代指数；
- $\alpha_{PE,{Lab}}$：房地产开发商投入劳动要素所占的替代指数；
- $\alpha_{PE,H}$：房地产开发商投入房地产要素所占的替代指数；





##### 指数化程度参数：

$\chi_{p} \in[0,1]$ ：指数化程度参数，其为消费品中间品厂商为确定化其指数化价格所需；



##### 比例：

$\theta_{\Box}$：比例；

其中，各下标表示含义如下：

- $\theta_{PI,p}$：在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取一定数量的厂商以参与重新定价，剩余仍未被抽取中以参与重新定价的厂商数量所占的比例；

- $\theta_{BB,PE}[t]$：房地产开发商信贷约束比例；

- $\theta_{BB,HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{BB,HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；

  

~~$\Phi$：消费品中间品生产商的固定生产成本。在稳态条件下，其值被设定为产生0利润；~~



##### TODO权重：

$\omega_{\Box}$：权重；

其中，各下标表示含义如下：













##### 信贷约束比例：

其中，各下标表示含义如下：

$\phi_{PG}[t]$：消费品生产商的贷款抵押资产限制率，暨商业银行为厂商提供的贷款不能超过其资本总额的限制比例，其服从AR(1)过程；

- ：商业银行部门向消费品中间品生产商贷款规定的信贷约束比例；





##### 监管成本：

$c_{BB,P}$：商业银行审查贷款用于生产部门之企业，存在单位贷款供给成本率；





##### 需求弹性：

$\xi_{P,BB}$：表示生产部门对商业银行$i$的借款需求弹性，衡量商业银行$i$的垄断程度；

$\xi_{H,BB}$：借款型居民对商业银行$i$的借款需求弹性，衡量商业银行$i$的垄断程度；










##  假设之于DSGE模型框架

假定

TODO



