# 系统性金融风险建模

> 系统性金融风险建模之方案\_010


[TOC]



## 总假设之于DSGE模型框架



**方案011**以方案010为基准，添加如下部门：

- 房地产开发商部门；
- 影子银行部门；





- 考虑一个离散时间的、无限生命周期的经济体。
- 假设信贷市场属于标准的Dixit-Stiglitz模式；
- 假定劳动力市场始终保持需求和供给均衡；



## DSGE模型框架之调用模块




| 部门         | 模块                                                         | 备注 |
| ------------ | ------------------------------------------------------------ | ---- |
| 居民部门     | [模块之居民部门H020](../模型框架模块/模块之居民部门H020.mmd) |      |
| 消费品生产商 | [模块之消费品生产商PG010](../模型框架模块/模块之消费品生产商PG010.mmd) |      |
| 房地产开发商 | [模块之房地产开发商PE010](../模型框架模块/模块之房地产开发商PE010.mmd) |      |
| 商业银行部门 | [模块之商业银行BB120](../模型框架模块/模块之商业银行BB120.mmd) |      |
| 影子银行部门 | [模块之影子银行BS120](../模型框架模块/模块之影子银行BS120.mmd) |      |
| 广义政府部门 | [模块之广义政府部门G010](../模型框架模块/模块之广义政府部门G010.mmd) |      |
|              |                                                              |      |
|              |                                                              |      |

  






## DSGE模型框架之各部门描述





### 居民部门



#### 参考

> 居民部门的设置参照
>
> [[方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.]]
>
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]



#### 模块特点

异质性代表性主体划分方式按照资金使用方式划分为：

- 借款型居民$\mathbb{HB}$；
- 投资和储蓄型居民$\mathbb{HI}$；



#### 模块接口



对于居民部门之消费需求$C_{H}[t]$由以下构成：

$$
C_{H}[t] := C_{H,PG}[t] + C_{H,PE}[t]
$$

其中，
$C_{H,PG}[t]$：居民部门之需求对于消费大众商品；
$C_{H,PE}[t]$：居民部门之需求对于住房消费；

上述表达式对于居民部门各子部门同样有效。





对于居民部门$\mathbb{H}$之住房消费需求$C_{H,PG}[t]$，有如下表达式：
$$
C_{H,PE}[t] := p_{PE}[t] \; \Delta C_{H,PE}[t]
$$

其中，
$p_{PE}[t] \; \Delta C_{H,PE}[t]$：房地产价格$p_{PE}[t]$与居民部门的住房偿还贷款变动量$\Delta C_{H,PE}[t]$的乘积，在时期$t$；

上述表达式对于居民部门各子部门同样有效。





对于居民部门$\mathbb{H}$之消费效用$Uti_{H,C}[t]$，由如下部分组成：
$$
Uti_{H,C}[t] := 
\alpha_{H,PG} \; \varepsilon_{H,PG}[t] \; \log[C_{H,PG}[t]] 
+ \alpha_{H,PE} \; \varepsilon_{H,PE}[t] \; \log C_{H,PE}[t]
$$

其中，
$\alpha_{H,PG}$：居民部门消费品消费行为偏好参数；
$\varepsilon_{H,PG}[t]$：扰动项之于居民部门之消费品消费，在时期$t$；
$C_{H,PG}[t]$：居民部门之消费品消费，在时期$t$；
$\alpha_{H,PE}$：居民部门之住房消费行为偏好参数；
$\varepsilon_{H,PE}[t]$：扰动项之于住房消费，在时期$t$；
$C_{H,PE}[t]$：居民部门之住房消费，在时期$t$；

上述表达式对于居民部门各子部门同样有效。





对于居民部门$\mathbb{H}$之工作时长$Hour_{H}[t]$，在时期$t$，由如下部分组成：
$$
Hour_{H}[t] := Hour_{H,PG}[t] + Hour_{H,PE}[t]
$$

其中，
$Hour_{H,PG}[t]$：居民部门在消费品中间品生产商的工作时长，在时期$t$；
$Hour_{H,PE}[t]$：居民部门在房地产开发商的工作时长，在时期$t$；

上述表达式对于居民部门各子部门同样有效。







定义居民部门$\mathbb{H}$获得总收入$Income_{H}[t]$为：
$$
Income_{H}[t] := w_{PG}[t] \; Hour_{H,PG}[t] + w_{PE}[t] \; Hour_{H,PE}[t]
$$

其中，
$w_{PG}[t] \; Hour_{H,PG}[t]$：居民部门获得总收入，从生产部门之消费品生产商部门。暨消费品生产商提供的工资率$w_{PG}[t]$，与在消费品生产商的工作时长$Hour_{HB,PG}[t]$的乘积，在时期$t$；
$w_{PE}[t]  \; Hour_{H,PE}[t]$：居民部门获得总收入，从生产部门之房地产开发商。暨房地产开发商提供的工资率$w_{PE}[t]$，与在房地产开发商的工作时长$Hour_{HB,PE}[t]$的乘积，在时期$t$；

上述表达式对于居民部门各子部门同样有效。















#### 部门构成：

一般划分：

- 借款型居民：

- 投资和储蓄型居民：

  

特殊角色：

- 银行家；

  



#### 部门假设：

- 假设居民部门所有成员生存周期无限；

- 假设居民部门各成员跨期偏好折现因子$\gamma_H$一致；

- 为了保证稳态时，借款型居民是经济体的净借款方，因此设借款型居民的贴现因子应小于投资和储蓄型居民的贴现因子$\gamma_{HB}<\gamma_{HI}$。

- 居民个数占比为$\theta_{H,N}[t]$，其中借款型居民个数占比为$\theta_{HB,N}[t]$，储蓄与投资型居民个数占比为$\theta_{HI,N}[t]$。则有如下关系式：
  $$
  \theta_{H,N}[t] := \theta_{HB,N}[t] + \theta_{HI,N}[t]
  $$

- 假设居民成员全部工作于生产商部门各子部门；

- 假设居民成员持有的资金全部用于消费、投资、储蓄，暨每个时期不存在闲置货币；

- 假设居民部门所有成员提供的劳动$Lab_{H}[t]$是同质的，暨单位生产率是一样的，此时居民提供的劳动在时期$t$，可以用劳动时长$Hour_{H}[t]$表示；



#### 借款型居民

一些文献描述借款型居民为非耐心居民，投资和储蓄型居民为耐心居民。

英文全名：

Borrowing Household

变量名：

household_borrowing

数学符号：

$\Box_{HB}$





##### 行为：

- 向商业银行部门之个体$i$借款$B_{HB,BB}[i,t]$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,HB}[i,t]$；

- 向商业银行部门之个体$i$还款$B_{HB,BB}[i,t]$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,HB}[i,t]$；

- 消费需求$C_{HB}[t]$；

  

##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有消费行为对于不同的消费项目之偏好$\alpha_{H}$；



##### 模型：

###### 目标：

借款型居民部门之目标是最大化其效用$Utility_{HB}$在当前时期$t$：

$$
Utility_{HB}[t] :=
\max _{Uti_{HB,C}[t],Hour_{HB}[t]}
\quad \mathbb{E}_{t=0} 
\left[ \sum_{t=0}^{\infty} 
(\gamma_{HB})^{t} \left(
Uti_{HB,C}[t]
- \frac{\left(Hour_{HB}[t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
 \right)
\right]
\tag{HB_goal}
$$

其中，
$\gamma_{HB}$：借款型居民跨时期折现因子；
$Uti_{HB,C}[t]$：借款型居民之消费效用；
$Hour_{HB}[t]$：借款型居民的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；







###### 约束条件：



对于借款型居民，存在以下约束：



预算约束：
$$
C_{HB}[t] + B_{HB,BB}[i,t-1] \; \frac{(1 + r_{BB,HB}[i,t]) }{\pi[t]} \leq Income_{HB}[t] + B_{HB,BB}[i,t] + Trans_{HB}[t]
\tag{HB_st_budget}
$$
其中，
$C_{HB}[t]$：借款型居民之消费需求，在时期$t$；
$B_{HB,BB}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$：借款型居民偿还上一期的借款给商业银行部门于本期，以借款利率$r_{BB,HB}[i,t]$，考虑当前总通胀率$\pi[t]$的影响；
$Income_{HB}[t]$：借款型居民当期总收入；
$B_{HB,BB}[i,t-1] \; (1+r_{BB,HB}[i,t-1]) / \pi[t]$：借款型居民之上一期借款$B_{HB,BB}[i,t-1]$于本期偿还，以上一期的商业银行$i$设定的贷款利率$r_{BB,HI}[i,t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$B_{HB,BB}[i,t]$：借款型居民对银行的借款，在当期$t$；
$Trans_{HB}[t]$：借款型居民获得的转移支付，在时期$t$；



~~对于借款型居民消费在房地产方面，存在信贷抵押约束：~~
$$
\left(1+r_{BB,HB}[i,t] \right) B_{HB,BB}[i,t] \leq \theta_{BB,HB}[t] \; \mathbb{E}_{t} \left[ p_{PE}[t+1] \; \pi[t+1] \; C_{HB,PE}[t] \right]
\tag{HB_st_debt}
$$
~~其中，~~
~~$\theta_{BB,HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{BB,HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；~~
~~$B_{HB,BB}[i,t]$：借款型居民对银行的借款；~~
~~TODO$p_{PE}[t+1] \; \pi[t+1] \; C_{HB,PE}[t]$：信贷抵押约束中，；~~





#### 投资和储蓄型居民

一些文献描述投资和储蓄型居民为耐心居民。

英文全名：

Investment Household

变量名：

household_investment

数学符号：

$\Box_{HI}$



##### 基本设定：



TODO投资和储蓄型居民的存款需求$D_{HI}[t]$有两种类型：短期存款、长期存款。两类存款作用是研究存款挤兑现象。

$$
D_{HI}[t] := D_{HI,s}[t] + D_{HI,l}[t]
$$

其中，
$D_{H,s}[t]$：居民部门短期存款；
$D_{H,l}[t]$：居民部门长期存款；




##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有消费行为对于不同的消费项目之偏好$\alpha_{H}$；



##### 假设：

TODO假设考虑存款有两种类型：短期存款、长期存款。用以建模存款挤兑现象；



##### 行为：

- 向商业银行部门个体$i$存款$D_{HI}[t]$，以商业银行$i$提供的存款利率$r_{BB,HI}[i,t]$；

- 向商业银行部门个体$i$取款$D_{HI}[t]$，以商业银行$i$提供的存款利率$r_{BB,HI}[i,t]$；

- 消费需求$C_{HI}[t]$；

  



##### 模型：



###### 目标：



投资和储蓄型居民部门的个体$i$的目标是最大化其效用$Utility_{HI}[t]$在当前时期$t$：
$$
Utility_{HI}[t]:=
\max \quad \mathbb{E}_{t=0} \left[ 
\sum_{t=0}^{\infty}
(\gamma_{HI})^{t} 
\left(
Uti_{HI,C}[t]
- \frac{\left(Hour_{HI}[t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
\right)
\right]
\tag{HI_goal}
$$
其中，
$\gamma_{HI}$：投资和储蓄型居民跨时期折现因子；
$Uti_{HI,C}[t]$：投资和储蓄型居民之消费效用；
$Hour_{HI}[t]$：投资和储蓄型居民的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；




###### 约束条件：

对于投资和储蓄型居民，存在以下约束：



预算约束：
$$
C_{HI}[t] + D_{HI}[t] \leq Income_{HI}[t] + \frac{(1+r_{BB,HI}[i,t-1])}{\pi[t]} \; D_{HI}[i,t-1] + Trans_{HI}[t]
\tag{HI_st_budget}
$$
其中，
$C_{HI}[t]$：投资和储蓄型居民之消费需求，在时期$t$；
$D_{HI}[t]$：投资和储蓄型居民在银行的储蓄；
$Income_{HI}[t]$：投资和储蓄型居民当期总收入；
$(1+r_{BB,HI}[i,t-1]) \; D_{HI}[i,t-1] / \pi[t]$：投资和储蓄型居民提现存于上一期的存款，从商业银行$i$，以上一期的存款利率$r_{BB,HI}[i,t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$Trans_{HI}[t]$：投资和储蓄型居民获得的转移支付，在时期$t$；





#### 居民部门居民类型的转换



TODO居民部门$\mathbb{H}$两类居民的转换



~~其中，银行家成员的转换：~~

> ~~参照~~
> ~~[[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]~~
> ~~的做法~~

~~居民成员中特殊角色可相互转化，每期银行家的相互转化满足泊松过程，分别以固定的退出率（转换率） $1-\lambda_{b} , \lambda_{b} \in[0,1)$， 随机退出自己岗位转为其他角色。如果退出率为0，则居民成员的角色不相互转化。~~





### 生产部门



#### TODO参考

> 





#### 特点

同质代表性消费品生产商模块PG010不区分子部门。统一用只有一种产出品的完全竞争消费品生产商代表企业部门。











#### 消费品生产商

在一些文献中，消费品最终品生产商之作用，相当于零售商之作用。

英文全名：

Goods Producers

变量名：

producers_goods

数学符号：

$\Box_{PG}$





##### 参考



> 消费品生产商部门参考：
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.



##### 模块特点

同质代表性消费品生产商模块PG010不区分子部门。统一用只有一种产出品的完全竞争消费品生产商代表企业部门。



##### 模块接口

代表性消费品生产商之总借款量$B_{PG}[t]$由如下构成：
$$
B_{PG}[t] := B_{PG,B}[t]
$$

其中，
$B_{PG,B}[t]$：消费品生产商部门从银行部门$\mathbb{B}$获得总借款，在时期$t$；



对于消费品生产商部门获得借款$B_{PG,B}[t]$，从银行部门$\mathbb{B}$之各个商业银行个体$i$、各个影子银行个体$j$，由以下构成：
$$
B_{PG,B}[t] := \sum_{i=1}^{N_{\mathbb{BB}}}{B_{PG,BB}[i,t]} + \sum_{j=1}^{N_{\mathbb{BS}}}{B_{PG,BS}[j,t]}
$$
其中，
$B_{PG,BB}[i,t]$：消费品生产商$\mathbb{PG}$借款从商业银行个体$i$；
$B_{PG,BS}[j,t]$：消费品生产商$\mathbb{PG}$借款从影子银行个体$j$；





代表性消费品生产商偿还借款量$Repay_{PG}[t]$由如下构成：
$$
Repay_{PG}[t] := Repay_{PG,B}[t]
$$
其中，
$Repay_{PG,B}[t]$：代表性消费品生产商偿还借款给银行部门$\mathbb{B}$，在时期$t$；





对于消费品生产商部门偿还借款$Repay_{PG,B}[t]$给银行部门$\mathbb{B}$之各个商业银行个体$i$、各个影子银行个体$j$，由以下构成：
$$
Repay_{PG,B}[t] := 
\sum_{i=1}^{N_{\mathbb{BB}}}{\left(\frac{(1+r_{BB,PG}[i,t])}{\pi[t]} \; B_{PG,BB}[i,t]\right)} 
+ \sum_{j=1}^{N_{\mathbb{BS}}}{\left(\frac{(1+r_{BS,PG}[j,t])}{\pi[t]} \; B_{PG,BS}[j,t]\right)}
$$
其中，
$\left(r_{BB,PG}[i,t-1]+1 \right) / \pi[t]\; B_{PG,BB}[i,t-1]$：消费品生产商部门偿还上一期借款$B_{PG,BB}[i,t-1]$给商业银行部门$\mathbb{BB}$之个体$i$，以其提供的贷款利率$r_{BB,PG}[i,t-1]$于上一期，考虑当期物价$\pi[t]$；
$\left(r_{BS,PG}[j,t-1]+1 \right) / \pi[t]\; B_{PG,BS}[j,t-1]$：消费品生产商部门偿还上一期借款$B_{PG,BS}[i,t-1]$给影子银行部门$\mathbb{BS}$之个体$j$，以其提供的贷款利率$r_{BS,PG}[j,t-1]$于上一期，考虑当期物价$\pi[t]$；





支付工资给居民部门$\mathbb{H}$；



信贷抵押约束(PG_st_debt)；



##### 构成：

- 消费品生产商；

  





##### 假设：

与许多描述同质代表性生产商行为的文献一样，假设生产部门之消费品生产商$i \in \{1,\cdots,N_{PG}\}$具有如下特点：

- 众多消费品生产商$i \in \{1,\cdots,N_{PG}\}$具有同质性，暨不考虑生产商之间的规模、生产产品的种类、生产商之间的其它特性的差异；
- 众多消费品生产商$i \in \{1,\cdots,N_{PG}\}$连续分布于某个区间$[0,1]$。因此在不考虑但各生产商的情况下，我们直接以单个典型消费品生产商作为全体消费品生产商的代表；
- 假设众多消费品生产商之间不考虑互相竞争的详细过程；
- 设定消费品生产商的生产函数形式为典型的Cobb-Douglas生产函数形式；
- 假设生产出来的消费品生产品是单一种类的同质性的产品；
- 假设生产出来的消费品生产品作为商品，能够在当期销售其总量$Y_{PG}[t]$且不留下存货；
- 假设生产出来进入销售环节的商品以单价$p_{PG}=1$，销售所得总收入为$Q_{PG}[t]$；

- 假设消费品生产部门只考虑国内贸易，不考虑对外贸易商品；



##### 行为：

同质性代表性消费品生产商具有如下行为：

- 寻求利润最大化$Profit_{PC}[t]$；

- 获取劳动力要素投入，从居民部门$\mathbb{H}$；

- 获取资本要素投入，从资本累积渠道：

  - 从自身累积资本；
  - 融资资本：
    - 从银行部门$\mathbb{B}$信贷$B_{PG,B}[t]$；
    - TODO从资本市场融资；
    - TODO从政府部门$\mathbb{G}$融资$B_{PG,G}[t]$；
    - 其它；

- 通过获取的生产要素生产同质性的产品，总量为$Y_{PG}$；

- 销售所有产品给居民部门$\mathbb{H}$，并且获得总收入$Q_{PG}[t]$；

- 缴纳税收$\tau_{PG}[t]$给政府部门；

- 消费品生产商存在信贷约束；

- 支付工资给居民部门$\mathbb{H}$；

- 偿还借款：

  - 偿还上一期的借款给银行部门$\mathbb{B}$；

    





##### 描述：

由于众多消费品生产商其生产消费品之间是充分竞争的。为了方便起见，以一个代表性生产商表示生产商部门。



消费品生产商资本$K_{PG}[t]$累积过程，呈现一个时变形式：
$$
K_{PG}[t] = (1-\delta_{PG}) \; K_{PG}[t-1] + I_{PG}[t] - Repay_{PG}[t]
$$

其中，
$K_{PG}[t]$：代表性消费品生产商之资本；
$\delta_{PG}$：折旧率之于代表性消费品生产商之资本；
$I_{PG}[t]$：表示代表性消费品生产商之投资量；
$Repay_{PG}[t]$：代表性消费品生产商偿还借款量；





在消费品生产商之资本要素投入方面，已经说明代表性消费品生产商之投资量$I_{PG}[t]$来源，其中包含信贷$B_{PG}[t]$：
$$
I_{PG}[t] = B_{PG}[t]
$$
其中，
$B_{PG}[t]$：消费品生产商借款总量，在时期$t$；








##### 目标：



> 借鉴
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.



消费品生产商部门$\mathbb{PG}$之目标是最大化当期利润$Profit_{PG}[t]$：
$$
Profit_{PG}[t] := 
\max_{B_{PG,B},Lab_{PG}[t],w_{H}[t]} \quad
\left(
\begin{array}{c}
Q_{PG}[t] - w_{H}[t] \; Lab_{PG}[t] \\
+ \Delta K_{PG}[t] \\
- \tau[t]
\end{array}
\right)
\tag{PG_goal}
$$

其中，
$Q_{PG}[t]$：消费品生产商产出销售总收入；
$w_{H}[t] \; Lab_{PG}[t]$：消费品生产商支付工资给居民部门；
$\Delta K_{PG}[t]$：消费品生产商资本变动量，默认表示当期与上一期变动量；
$\tau[t]$：消费品生产商缴纳税收；





##### 约束条件：



消费品生产商主要面临的约束条件有：

- 生产产出；
- 销售约束；
- 信贷抵押约束；





生产产出：

消费品生产商之生产函数$F_{PG}[\cdot]$服从Cobb-Douglas生产函数形式：
$$
Y_{PG}[t] = F_{PG}[TFP_{PG}[t],K_{PG}[t],Lab_{PG}[t]] := TFP_{PG}[t] \; (K_{PG}[t])^{\alpha_{PG}} \; (Lab_{PG}[t])^{1-\alpha_{PG}} \\
\tag{PG_st_product}
$$
其中，
$TFP_{PG}[t]$：消费品领域生产的全要素生产率（技术）在时期$t$；
$K_{PG}[t]$ ：消费品生产商$i$的资本要素；
$Lab_{PG}[t]$：消费品生产商$i$的劳动要素；
$\alpha_{PG}$：消费品生产商各生产要素的替代指数；



假定全要素生产率 $TFP_{PG}[t]$ 服从如下形式的一阶自回归AR(1)过程：
$$
\log TFP_{PG}[t] = \rho_{TFP,PG} \log TFP_{PG}[t-1] + \varepsilon_{TFP,PG}[t]
$$

其中，
$\rho_{TFP,PG}$：消费品生产商的全要素生产率$TFP_{PG}[t]$对应的自回归过程的回归系数；
$\varepsilon_{TFP,PG}[t]$：消费品生产商的全要素生产率对$TFP_{PG}[t]$应的自回归过程的扰动项；



销售约束：

消费品生产商部门销售尽全部的所生产的产品给居民部门，获得收入$Q_{PG}[t]$：
$$
p_{PG} \; Y_{PG}[t] = Q_{PG}[t] = C_{H}[t]
$$







信贷抵押约束：

> 借鉴
>
> 林琳, 曹勇, 肖寒, 2016. 中国式影子银行下的金融系统脆弱性[J]. 经济学(季刊), (03 vo 15): 1113–1136.

消费品生产商抵押固定资产在银行部门$\mathbb{B}$贷款中，存在信贷抵押约束
$$
\begin{array}{l}
\left(1+r_{BB,PG}[i,t] \right) \; B_{PG,BB}[i,t] \leq \phi_{BB,PG}[i,t] \; K_{PG}[t]
\\
\left(1+r_{BS,PG}[j,t] \right) \; B_{PG,BS}[j,t] \leq \phi_{BS,PG}[j,t] \; K_{PG}[t]
\tag{PG_st_debt}
\end{array}
$$
其中，
$\left(1+r_{BB,PG}[i,t] \right) \; B_{PG,BB}[i,t]$：消费品生产商部门可以借到的贷款量，从商业银行部门之个体$i$；
$\phi_{BB,PG}[i,t]$：商业银行部门之个体$i$针对消费品生产商给定的贷款抵押资产限制率，暨其为厂商提供的贷款不能超过其资本总额的限制比例；
$\left(1+r_{BS,PG}[j,t] \right) \; B_{PG,BS}[i,t]$：消费品生产商部门可以借到的贷款量，从影子银行部门之个体$j$；
$\phi_{BS,PG}[j,t]$：影子银行部门之个体$j$针对消费品生产商给定的贷款抵押资产限制率，暨其为厂商提供的贷款不能超过其资本总额的限制比例；
$K_{PG}[t]$：消费品生产商资本；







### 房地产开发商部门TODO

TODO

英文全名：

Real Estate Producers

变量名：

producers_estate

数学符号：

$\Box_{PE}$





##### 行为：

- 从商业银行获得贷款；
- 从影子银行部门获得融资；
- 采用资本、劳动、土地开发建设房地产；



> 房地产开发商部分参考
>
> [[郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产开发商的DSGE模型分析[J]. 南方经济, (08): 29–46.]]
>
> 



##### 模型：

房地产开发商部门的生产函数$F_{PE}$符合规模报酬不变的特性。

对于整个房地产开发商部门来说，其生产函数$F_{PE}[\cdot]$：

$$
Y_{PE}[t] = F_{PE}[TFP_{PE}[t],K_{PE}[t],Lab_{PE}[t],H_{PE}[t]] := TFP_{PE}[t] \; (K_{PE}[t-1])^{\alpha_{PE,K}} (Lab_{PE}[t])^{\alpha_{PE,Lab}} (H_{PE}[t-1])^{\alpha_{PE,H}}
$$

其中，
$Y_{PE}[t]$：房地产开发商的最终产出；
$TFP_{PE}[t]$：房地产开发商的全要素生产率；
$K_{PE}[t-1]$：房地产开发商之资本存量，在上一时期；
$H_{PE}[t-1]$：房地产存量，在上一时期；
$Lab_{PE}[t]$：房地产商投入的劳动力要素；
$H_{PE}[t-1]$：房地产商投入的房地产商品存量，在上一时期；
$\alpha_{PE,K}$：房地产开发商投入资本要素所占的替代指数；
$\alpha_{PE,Lab}$：房地产开发商投入劳动要素所占的替代指数；
$\alpha_{PE,H}$：房地产开发商投入房地产要素所占的替代指数；

其中，满足

$$
\alpha_{PE,K}+\alpha_{PE,Lab}+\alpha_{PE,H}=1​
$$



###### 目标：


整体商地产开发商部门之目标在于最大化其消费：

$$
\max \mathbb{E}_{t} \sum_{t=0}^{\infty} \gamma_{PE} \; \log C_{PE}[t]
$$

其中，
$C_{PE}[t]$：房地产开发商之消费；
$\gamma_{PE}$：贴现因子，$0<\gamma_{PE}<1$ 。



###### 约束条件：

房地产开发商所受资金流的约束条件如下:

$$
Y_{PE}[t] + B_{PE,BB}[t] + B_{BS,PE}[t] = C_{PE}[t] + p_{PE}[t] \; \left(H_{PE}[t] - H_{PE}[t-1]\right) + w_{PE}[t] \; Lab_{PE}[t] + B_{PE,BB}[t-1] \; \frac{(1+r_{BB,PE}[i,t-1])}{\pi[t]} + B_{BS,PE}[t-1] \; \frac{(1+r_{BS,PE}[t-1])}{\pi[t]} + I_{PE}[t]
$$

理解和替换相关变量

其中，
$Y_{PE}[t]$：房地产开发商的产出；
$B_{PE,BB}[t]$：房地产开发商从商业银行借款，在时期$t$；
$r_{BB,PE}[i,t]$：商业银行向房地产开发商的贷款利率；
$p_{PE}[t]$：房地产价格：
$B_{BS,PE}[t]$：房地产开发商向影子银行获取的贷款的数量；
$r_{BS,PE}[t]$：影子银行向房地产开发商的贷款利率；
$I_{PE}[t]$：房地产开发商的投资；
$\left(H_{PE}[t]-H_{PE}[t-1]\right)$：房地产流量，在当期的时候；
$w_{PE}[t]$：房地产开发商提供的支付单位工资，暨工资率，在时期$t$；
$Lab_{PE}[t]$：房地产商的劳动力资源要素，在时期$t$，体现为房地产开发商提供的工资率；

房地产开发企业总体信贷规模为 $B_{PE}[t] := B_{BS,PE}[t]+B_{PE,BB}[t]$。

房地产开发商的投资 $I_{PE}[t]$ 与资本存量 $K_{PE}[t]$ 之间存在如下关系:

$$
K_{PE}[t+1]=I_{PE}[t]+(1-\delta_{PE}) K_{PE}[t]
$$

该式表示的是房地产开发商资本存量的积累情况, $\delta_{PE}$ 表示资本折旧率。

> 本文借鉴
>
> [[Christensen I, Dib A, 2008. The Financial Accelerator in an Estimated New Keynesian Model[J]. Review of Economic Dynamics, 11(1): 155–178. DOI:[10.1016/j.red.2007.04.006](https://doi.org/10.1016/j.red.2007.04.006).]]
>
> [[Iacoviello M, 2005. House Prices, Borrowing Constraints, and Monetary Policy in the Business Cycle[J]. American Economic Review, 95(3): 739–764. DOI:[10.1257/0002828054201477](https://doi.org/10.1257/0002828054201477).]]
>
> 的研究，引入信贷约束机制

对于商业银行来说，由于存在信贷约束机制。通过引入信贷约束机制，房地产开发商将其持有的房地产抵押给商业银行获得抵押贷款，但是其所获得的抵押贷款的数量取决于其还款期抵押品的预期价值。假设 $\theta_{BB,PE}[t] \in (0,1)$ 为房地产开发商信贷约束比例，需满足:

$$
B_{PE,BB}[t] \leq \theta_{BB,PE}[t] \frac{\mathbb{E}_{t} \left[p_{PE}[t+1] \; H_{PE}[t] \; \pi[t+1]\right]}{r_{BB,PE}[i,t]}
$$

其中，
$\theta_{BB,PE}[t]$：为房地产开发商信贷约束比例；
$B_{PE,BB}[t]$：房地产开发商从商业银行借款，在时期$t$；
$r_{BB,PE}[i,t]$：商业银行向房地产开发商的贷款利率；
$H_{PE}[t]$：房地产部门整体存量，在当期的时候；











### 商业银行部门

英文全名：

Commercial Bank

变量名：

bank_commercial

数学符号：

$\Box_{BB}$



#### 银行部门各银行划分：



每个银行机构作为一个个体。个体之间的差异性通过数据或者参数设定体现。





#### 假定：

- 商业银行审查贷款用于生产部门企业，存在单位贷款供给成本率$c_{BB,P}$；
- TODO生产部门对商业银行的所有信贷需求都能得到满足；




#### TODO设定：

设定同期信贷资产调整成本$Adj_{BB,A}\left[Asset_{1},Asset_{2}\right]$存在函数关系式：


$$
Adj_{BB,A}\left[Asset_{1},Asset_{2}\right] := 
\frac{\beta}{2} \; \left(\frac{Asset_{1}}{Asset_{2}} - \frac{\bar{Asset}_{1}}{\bar{Asset}_{2}}  \right)^{2}
$$





#### TODO模块描述



#### TODO模块接口

商业银行部门$\mathbb{BB}$接受居民部门$\mathbb{H}$之存款资金，由以下构成：
$$
D_{H}[t] := \sum_{i=1}^{N_{BB}}{D_{HI}[i,t]}
$$



商业银行部门$\mathbb{BB}$提供贷款资本贷给居民部门$\mathbb{H}$，由以下构成：
$$
L_{BB,H}[t] := \sum_{i=1}^{N_{BB}}{L_{BB,HB}[i,t]}
$$



商业银行部门$\mathbb{BB}$提供贷款资本贷给生产商部门$\mathbb{P}$，由以下构成：
$$
L_{BB,P}[t] := \sum_{i=1}^{N_{BB}}{L_{BB,PG}[i,t]} + \sum_{i=1}^{N_{BB}}{L_{BB,PE}[i,t]}
$$



商业银行部门$\mathbb{BB}$之个体$i$接受居民部门$\mathbb{H}$之存款资金，由以下构成：
$$
D_{H}[i,t] := D_{HI}[i,t]
$$



商业银行部门$\mathbb{BB}$之个体$i$提供贷款资本贷给居民部门$\mathbb{H}$，由以下构成：
$$
L_{BB,H}[i,t] := L_{BB,HI}[i,t]
$$



商业银行部门$\mathbb{BB}$之个体$i$提供贷款资本贷给生产商部门$\mathbb{P}$，由以下构成：
$$
L_{BB,P}[i,t] := L_{BB,EG}[i,t] + L_{BB,PE}[i,t]
$$





商业银行部门$\mathbb{BB}$是否开展影子银行业务，由以下构成：
$$
is_{BS} := 1
$$









#### 行为：



对于单个商业银行$i$，有如下行为：

- 商业银行$i$从常规渠道获得资本，其融资来源：

  - 自有资本$K_{BB}[i,t]$；
  - 接受投资和储蓄型居民部门$\mathbb{HI}$整体存款资金$D_{HI}[\cdot,i,t]$至商业银行$i$；
  - 商业银行提供资金$D_{HI}[\cdot,i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需；
  - 银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$在拆借市场于时期$t$；
  - 向中央银行贴现$B_{BB,G}[i,t]$；
  - TODO偿还中央银行贴现$B_{BB,G}[i,t-1] \; (1+r_{G,BB}[i,t]) / \pi[t]$，并且考虑央行提供的利息和物价；

- 提供贷款服务：

  - 商业银行$i$提供贷款资本贷给消费品生产部门（非金融机构）：

    - 商业银行$i$提供贷款$L_{BB,PG}[i,t]$给消费品生产商部门$\mathbb{PG}$，在当期；
    - 商业银行$i$收回上一期贷款$L_{BB,PG}[i,t-1]$，其贷给消费品生产商部门$\mathbb{PG}$，并且需要考虑利息；
  - 商业银行$i$提供贷款资本贷给房地产开发商部门（非金融机构）：
    - 贷款$L_{BB,PE}[i,t]$给房地产开发商部门$\mathbb{PE}$，在当期；
    - 商业银行$i$收回上一期贷给房地产开发商部门$\mathbb{PE}$之贷款$L_{BB,PE}[i,t-1] \; (1+r_{BB,PE}[i,t-1]) / \pi[t]$；
  - 商业银行$i$提供贷款给借款型居民部门：

    - 商业银行$i$提供贷款$L_{BB,H}[i,t]$给借款型居民部门之居民$\mathbb{HB}$于当期$t$，以利率$r_{BB,HB}[i,t]$；

    - 商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,H}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$，从借款型居民部门之居民$\mathbb{HB}_{j}$；

- 如果商业银行部门$\mathbb{BB}$开展影子银行业务，则：

  - 商业银行$i$购买影子银行$j$提供的资管产品$ABS_{BS}[j,i,t-1]$；
  - 商业银行$i$赎回影子银行$j$提供的资管产品，以获得收益$(1+r_{BS,BB}[t-1]) \; ABS_{BS}[j,i,t-1]$；

- 股利分红$Dv_{BB}[t]$；

- 现有面临监管要求：

  - 贷存比监管$\check{\theta}_{CAR,BB}[i,t]$：

    不满足规定贷存比要求对应的惩罚函数$Pun_{LDR}[i,t,gap_[i,t]]$；

  - 资本充足率监管$\check{\theta}_{CAR,BB}[i,t]$：

    不满足规定资本充足率要求对应的惩罚函数$Pun_{CAR}[i,t]$；





#### 模型：



对于单个商业银行$i$，有如下行为：



商业银行资本更新：

商业银行$i$从常规渠道获得资本，其融资来源主要有：

- 自有资本更新；
- 接受居民存款；
- 同业拆借；



自有资本$K_{BB}[i,t]$更新：
$$
K_{BB}[i,t+1]=
\left(1-\delta_{BB}\right) K_{BB}[i,t] + (1-\theta_{BB,Dv}) \; Profit_{BB}[i,t]
$$

其中，
$Profit_{BB}[i,t]$：商业银行$i$当期经营利润；
$\theta_{BB,Dv}[i,t]$：商业银行$i$的当期分红策略（所得经营利润之分红比例）；
$\delta_{BB}$：折旧率之于商业银行资本；





接受居民存款$D_{HI}[t]$：

商业银行$i$获取投资和储蓄型居民部门$\mathbb{HI}$存款资金$D_{HI}[t]$，于当期。则该银行当期负债增加$Liability_{BB,HI}[i,t]$，同时当期资金流增加；

商业银行$i$提供资金$D_{HI}[i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需。则该银行当期负债$Liability_{BB,HI}[i,t]$减少；



向中央银行贴现：

商业银行$i$获取政府部门之中央银行$\mathbb{G}$贴现获得借款资金$B_{BB,G}[i,t]$，于当期。则该银行当期负债增加$Liability_{BB,G}[i,t]$，同时当期资金流增加；

商业银行$i$偿还上一期向政府部门之中央银行$\mathbb{G}$贴现资金$B_{BB,G}[i,t-1] \; (1+r_{G,BB}[i,t]) / \pi[t]$。则该银行当期负债$Liability_{BB,G}[i,t]$减少；



商业银行提供贷款服务：

商业银行$i$提供贷款$L_{BB,H}[i,t]$给借款型居民部门之居民$\mathbb{HB}$于当期$t$，以利率$r_{BB,HB}[i,t]$。则该银行当期资产$Asset_{BB,HB}[i,t]$增加，同时当期资金流减少；

商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,HB}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$。则该银行当期资产$Asset_{BB,HB}[i,t]$减少，同时当期资金流增加；

商业银行$i$提供贷款资本$L_{BB,PG}[i,t]$贷给消费品生产部门（非金融机构）$\mathbb{P}$，于当期。则该银行当期资产增加$Asset_{BB,PG}[i,t]$，同时当期资金流减少；

商业银行$i$收回上一期贷款$L_{BB,PG}[i,t-1] \; (1+r_{BB,PG}[i,t-1]) / \pi[t]$，其贷给消费品生产商部门$\mathbb{PG}$。则该银行当期资产减少$Asset_{BB,PG}[i,t-1]$，同时当期资金流增加；

商业银行$i$提供贷款资本$L_{BB,PE}[i,t]$贷给房地产开发商部门（非金融机构）。则该银行当期资产增加$Asset_{BB,PE}[i,t]$；

商业银行$i$收回上一期贷款$L_{BB,PE}[i,t-1] \; (1+r_{BB,PE}[i,t-1]) / \pi[t]$。则该银行当期资产$Asset_{BB,PE}[i,t]$减少，同时当期资金流增加；

商业银行为贷款给企业需要进行审查，其付出审查成本率$c_{BB,P}[t]$满足如下AR(1)过程：
$$
c_{BB,P}[t]:=\rho_{c_{BB,P}} \; c_{BB,P}[t-1] + \varepsilon_{c_{BB,P}}[t]
$$



对于商业银行调整其信贷资产比例，暨调整影子银行的ABS产品和商业银行传统贷款时，存在如下调整成本
$$
Adj_{BB,A}\left[ABS_{BS}[t],L_{BB,BK}[t]\right] := \frac{\beta_{BB}}{2} \; \left(\frac{ABS_{BS}[j,i,t]}{L_{BB,PG}[i,t]} - \frac{\bar{ABS}_{BS}[j,i,t]}{\bar{L}_{BB,PG}[i,t]}  \right)^{2}
$$

其中，
$\beta_{BB}$：商业银行调整信贷资产权重；





TODO设定生产部门对商业银行$i$的借款需求$\tilde{B}_{P,BB}[i,t]$满足函数关系：

$$
\tilde{B}_{P,BB}[i,t]=\left( \frac{r_{BB,P}[i,t]}{r_{BB,P}[t]} \right)^{-\xi_{P,BB}} \tilde{B}_{P,BB}[t]
$$

其中，
$\xi_{P,BB}$：生产部门对商业银行$i$的借款需求弹性，衡量商业银行$i$的垄断程度；
$r_{BB,P}[i,t]$：商业银行$i$对生产部门的贷款利率，暨生产部门对商业银行借款利率；
$\tilde{B}_{P,BB}[t]$：生产部门对商业银行整体借款需求；



TODO设定居民部门之借款型居民对商业银行$i$的借款需求$\tilde{B}_{HB,BB}[i,t]$满足函数关系：

$$
\tilde{B}_{HB,BB}[i,t]=\left( \frac{r_{BB,HB}[i,t]}{r_{BB,HB}[t]} \right)^{-\xi_{HB,BB}} \tilde{B}_{HB,BB}[t]
$$

其中，
$\xi_{H,BB}$：借款型居民对商业银行$i$的借款需求弹性，衡量商业银行$i$的垄断程度；
$r_{BB,HB}[i,t]$：商业银行$i$对借款型居民的贷款利率，暨借款型居民对商业银行借款利率；
$\tilde{B}_{H,BB}[t]$：借款型居民对商业银行整体借款需求；











如果商业银行部门$\mathbb{BB}$开展影子银行业务，则：


- 商业银行$i$购买影子银行$j$提供的资管产品$ABS_{BS}[j,i,t-1]$；
- 商业银行$i$赎回影子银行$j$提供的资管产品，以获得收益$(1+r_{BS,BB}[t-1]) \; ABS_{BS}[j,i,t-1]$；





股利分红：

商业银行对于最终经营收入按照比例$\theta_{BB,Dv}[i,t]$做股利分红$Dv_{BB}[i,t]$：
$$
Dv_{BB}[i,t] := \theta_{BB,Dv}[i,t] \; Profit_{BB}[i,t]
$$
由于我国国情，股利分红几乎可以忽略不计。





TODO银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$于时期$t$。银行间市场的内生性描述将在下文展开。在DSGE的构建方面我们考虑借鉴

> 王擎, 田娇, 2016. 银行资本监管与系统性金融风险传递——基于DSGE模型的分析[J]. 中国社会科学, 000(03): 99–122.

，将同业拆借造成的资金流变化情况纳入银行的资金流变化中。但是要将银行间市场更好地内生化考虑，需要








商业银行$i$面临广义政府部门监管要求：

- 贷存比监管$\check{\theta}_{CAR,BB}[i,t]$：

  不满足规定贷存比要求对应的惩罚函数$Pun_{LDR}[i,t,gap_[i,t]]$；

- 资本充足率监管$\check{\theta}_{CAR,BS}[i,t]$：

  不满足规定资本充足率要求对应的惩罚函数$Pun_{CAR}[i,t]$；

对于上述变量之定义，见广义政府部门描述部门。



~~由上述资金流变动情况，可得商业银行当期资金流变动公式：~~
$$
Cash_{BB}[i,t] := Cash_{}
$$







TODO银行接受贷存比约束监管：

> 借鉴
>
> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.
>
> 王擎, 田娇, 2016. 银行资本监管与系统性金融风险传递——基于DSGE模型的分析[J]. 中国社会科学, 000(03): 99–122.

$$
 \frac{L_{BB}[i,t]}{D_{BB,H}[i,t]} \leq \check{\theta}_{CAR,BB}[i,t] 
$$

其中，
$\check{\phi}_{CAR}$：商业银行资本充足率（Capital Adequacy Ratio）要求；





TODO银行接受资本充足率约束监管：

> 借鉴
>
> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.p31
>
> 田娇, 王擎, 2017. 系统性风险防范与多重金融政策搭配——基于DSGE模型的逆周期监管效应分析[J]. 财经研究, 07(v.31;No.246): 59–71.

$$
\check{\phi}_{CAR}[i,t] \geq \frac{{K}_{B}[i,t]}{ \sum_{}^{}{\left(\omega_{CAR,A}[i,t] \; Asset_{BB,A}[i,t]\right)}}
$$




#### 目标



> 借鉴
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.
>
> 的目标最优化函数。直接将商业银行跨期利润作为商业银行最优化目标之一。

对于单个商业银行$i$，其最优化目标有几个：商业信誉、利润。为了方便起见，我们主要以最大化跨期利润作为最优化目标的重点。

TODO最大化商业信誉：
$$
  Reputation_{BB}[i,t]:=
  \max
  商业信誉的度量
$$

2. 最大化跨期利润$Profit_{BB}[i,t]$：

$$
Profit_{BB}[i,t]
:=
\max _{
\left\{
\begin{array}{c}
r_{BB,HI}[i,t],r_{BB,HB}[i,t],\\
r_{BB,PG}[i,t],r_{BB,PE}[i,t],\\
D_{BB,HI}[i,t],L_{BB,HB}[i,t],\\
ABS_{BS}[j,i,t]
\end{array}
\right\}
}
\mathbb{E}_t \left[
\sum_{t=0}^{\infty} 
\left(\gamma_{BB}\right)^{t} 
\left(
\begin{align}&
D_{HI}[t]
-D_{HI}[i,t-1] \; \frac{(1+r_{BB,HI})}{\pi[t]}
\\&
+B_{BB,G}[i,t]
-B_{BB,G}[i,t-1] \; \frac{1+r_{G,BB}[i,t]}{\pi[t]}
\\&
+L_{BB,PG}[i,t-1] \; \frac{(1+r_{BB,PG}[i,t]-\delta_{PG})}{\pi[t]}
-L_{BB,PG}[i,t] \; (1+c_{BB,P}[t])
\\&
同业拆入+B_{}
\\&
同业拆出
\\&
- ABS_{BS}[j,i,t]
+ (1-\mathcal{Pr}_{def,BS}[t]) \; ABS_{BS}[j,i,t-1] \; \frac{(1+r_{BS,BB}[t-1])}{\pi[t]}
\\&
- Pun_{CAR}[i,t,gap[i,t]]
- Adj_{BB,A}\left[ABS_{BS}[t],L_{BB,BK}[t]\right]
\end{align}
\right)
\right]
\quad \quad \quad \quad \quad
\tag{BB_Goal}
$$

其中，
$D_{HI}[t]$：居民部门存款于商业银行$i$的资金；
$D_{HI}[i,t-1] \; (1+r_{BB,HI}) / \pi[t]$：提供资金以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需；
$B_{BB,G}[i,t]$：商业银行$i$获取政府部门之中央银行$\mathbb{G}$贴现获得借款资金$B_{BB,G}[i,t]$，于当期；
$B_{BB,G}[i,t-1] \; (1+r_{G,BB}[i,t]) / \pi[t]$：商业银行$i$偿还上一期向政府部门之中央银行$\mathbb{G}$贴现资金；
$L_{BB,PG}[i,t-1] \; (1+r_{BB,PG}[i,t]-\delta_{PG}) / \pi[t]$：收回上一期贷给消费品生产商部门$\mathbb{PG}$之贷款所获得的收入，与此同时考虑消费品生产商部门对商业银行个体$i$之违约概率$\mathcal{Pr}_{def,PG}[i,t]$，在当期；
$L_{BB,PG}[i,t] \; (1+c_{BB,P}[t])$：商业银行$i$贷款给消费品生产商部门，在当期，与此同时付出审查成本率$c_{BB,P}[t]$；
$ABS_{BS}[j,i,t-1]$：商业银行$i$购买影子银行$j$提供的资管产品，在上一期；
$\mathcal{Pr}_{def,BS}[j,i,t]$：影子银行$j$对商业银行$i$之违约概率，在时期$t$；
$(1-\mathcal{Pr}_{def,BS}[t]) \; ABS_{BS}[j,i,t-1] \; (1+r_{BS,BB}[t-1]) / \pi[t]$：商业银行$i$赎回影子银行$j$提供的购买资管产品所获得收益，于上一期。其中$r_{BS,BB}[t-1]$表示收益率，$\mathcal{Pr}_{def,BS}[t]$表示概率之于影子银行违约无法提供收益，在当期的时候；
$Pun_{CAR}[i,t,gap[i,t]]$：商业银行$i$面临不满足规定的资本充足率要求对应的惩罚函数，于时期$t$；
$Pun_{LDR}[i,t,gap_[i,t]]$：商业银行$i$面临不满足规定的贷存比要求对应的惩罚函数，于时期$t$；
$Adj_{BB,A}\left[ABS_{BS}[t],L_{BB,BK}[t]\right]$：同期信贷资产调整成本函数；



TODO同业拆借；









#### 约束条件：



商业银行$i$面临每一时期的资产负债表平衡约束。其资产负债表可表示为：

$$
Asset_{BB}[i,t] = Liability_{BB}[i,t] + Equity_{BB}[i,t]
$$
其中，
$Asset_{BB}[i,t]$：商业银行$i$之当期的总资产；
$Liability_{BB}[i,t]$：商业银行$i$之当期的总负债；
$Equity_{BB}[i,t]$：商业银行$i$之当期的总所有者权益；

对于商业银行$i$之当期总资产$Asset_{BB}[i,t]$，由如下构成：
$$
Asset_{BB}[i,t] = Asset_{BB,HB}[i,t] + Asset_{BB,PG}[i,t] + Asset_{BB,PE}[i,t] + Asset_{BB,BI}[i,t] + Asset_{BB,BS}[]
$$
对于商业银行对于商业银行$i$之当期总负债$Liability_{BB}[i,t]$，由如下构成：
$$
Liability_{BB}[i,t] = Liability_{BB,HI}[i,t] + Asset_{BB,BI}[i,t] + Asset_{BB,PE}[i,t] + Asset_{BB,BI}[i,t]
$$





商业银行$i$在同业拆借市场资产$Asset_{BB,PE}[i,t]$，由如下构成：
$$
Asset_{BB,BI}[i,t] = \sum_{j=1}^{N_{j}}{Asset_{BB,BI}[i,j,t]}
$$
其中，
$Asset_{BB,BI}[i,j,t]$：商业银行$i$拥有商业银行$j$之资金作为资产，在同业拆借市场中，在当期。






TODO商业银行$i$面临资金流约束：
$$
L_{BB,PE}[i,t] + L_{BB,PG}[i,t] + L_{BB,H}[i,t] = D_{HI}[\cdot,i,t] + D_{HI}[t] + B_{BI}[i,j,t] + K_{BB}[i,t]
$$











### 银行家TODO

TODO是否考虑银行家以分析道德风险？



部门构成：

- 银行家：
  - 英文全名：Banker
  - 









### 影子银行部门TODO

TODO

英文全名：

Shadow Bank

变量名：

bank_shadow

数学符号：

$\Box_{BS}$



##### 假设：

- 影子银行可以退出市场，当每期的影子银行产品到期兑付之后；
- 设定影子银行为多主体模型，与商业银行部门银行类似；
- 将每个影子银行$j$划分为具有2期生命周期的主体，以OLG结构的方式建模；



##### 行为：

- 销售理财产品给家庭部门；
- 接受资产转移从商业银行部门；
- 融资给生产部门；
- 影子银行可以退出市场，当每期的影子银行产品到期兑付之后；







##### 模型：

> 借鉴
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.
>
> 对影子银行的建模。

第一期，影子银行进入市场，融资，以发行资管产品ABS





> 林琳, 曹勇, 肖寒, 2016. 中国式影子银行下的金融系统脆弱性[J]. 经济学(季刊), (03 vo 15): 1113–1136.

影子银行净资产通过留存收益获得





### 银行间市场

TODO





### 广义政府部门

TODO



英文全名：

Government

变量名：

government

数学符号：

$\Box_{G}$







##### 假设：





##### 构成：

广义政府部门划分为：

- 政府运转部门；

  - 财政部门：提供政府融资、采购、消费等服务、税收；

  

- 中央银行：

  - 充当货币当局的角色，实施货币政策；

  - TODO向商业银行贴现；

    

- 银监会：

  - 宏观审慎政策、微观审慎政策；



##### 行为：



普通政府的行为：

- 财政政策；
- 税收；
- 居民福利转移；
- 调控房地产市场；

中央银行和监管当局的行为：

- 货币政策：

  - 相关的货币政策工具：
    - Taylor Rules，通过调控利率以调控投资。

- 公开市场操作：

- 控制商业银行的资本充足率要求；

  - 调控方式：

- 控制商业银行的存款准备金率$DR_{BB}[i,t]$以达到要求$\check{\theta}_{DR}[i,t]$；

- 贷款价值比（LTVs）；

- 控制影子银行的资本充足率要求；

- 贷存比要求；

  

  






##### 定义：

定义传统资本充足率要求：
$$
\phi_{CAR}[t]:=\check{CAR}[t]
$$



定义贷存比要求：
$$
\check{\phi}_{LDR}[t] := \check{LDR}
$$



##### 模型：








> 资本充足率监管惩罚函数，借鉴 GNSS模型
>
> Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.

TODO定义中央银行对商业银行$i$的资本充足率惩罚函数$Pun_{CAR}[i,t,gap_[i,t]]$：

$$
Pun_{CAR}[i,t,Gap_{CAR}[i,t]] := \frac{1}{2} \; \kappa_{CAR} \left(  \right)
$$



构建传统货币政策调控方式Talor Rule：
$$
\log \left(\frac{R_{t}}{R}\right)=\kappa_{r} \log \left(\frac{R_{t-1}}{R}\right)+\left(1-\kappa_{r}\right)\left[\kappa_{y} \log \left(\frac{Y_{t}}{Y}\right)+\kappa_{\pi} \log \left(\frac{\pi_{t}}{\pi}\right)\right]+\varepsilon_{t}^{r}
$$

贷存比要求：
$$
\check{\theta}_{LDR,BB}[i,t] := \frac{L_{BB}[i,t]}{D_{BB,H}[i,t]}
$$



TODO定义中央银行对商业银行$i$不满足规定的贷存比要求对应的惩罚函数，于时期$t$：
$$
Pun_{LDR}[i,t,Gap_{LDR}[i,t]] := \frac{1}{2} \;
$$





### 宏观经济处于理想均衡状态下的市场出清

TODO宏观经济处于理想均衡状态下的市场出清状态。

对于生产部门的劳动力投入要素$Lab_{\Box}[t]$，表示以居民部门的劳动时长。






## TODO DSGE模型框架方程组之于纳入计算的




借款型居民之优化目标(HB_goal)

借款型居民之预算约束(HB_st_budget)

借款型居民之信贷约束(HB_st_debt)

贷款型居民之优化目标(HI_goal)

贷款型居民之预算约束(HI_st_budget)



## DSGE模型框架方程组之于纳入计算均衡解的





## 参数校准和估计





考虑到中国股票市场较少分红的现实 ， 假设银行的利润用来分红的比例$1-\theta_{BB,s}=0$，即全部用来补充银行资本。



