# 系统性金融风险建模

> 系统性金融风险建模之方案\_020


[TOC]



## 总假设之于DSGE模型框架



- 考虑一个离散时间的、无限生命周期的经济体。
- 假设信贷市场属于标准的Dixit-Stiglitz模式。



## DSGE模型框架之调用模块




| 部门         | 模块                                                         | 备注 |
| ------------ | ------------------------------------------------------------ | ---- |
| 居民部门     | [模块之居民部门H020](../模型框架模块/模块之居民部门H020.mmd) |      |
| 消费品生产商 | [模块之消费品生产商PG020](../模型框架模块/模块之消费品生产商PG020.mmd) |      |
| 房地产开发商 | -                                                            |      |
| 商业银行部门 | [模块之商业银行BB120](../模型框架模块/模块之商业银行BB120.mmd) |      |
| 影子银行部门 | -                                                            |      |
| 广义政府部门 | [模块之广义政府部门G010](../模型框架模块/模块之广义政府部门G010.mmd) |      |
|              |                                                              |      |
|              |                                                              |      |

  






## DSGE模型框架之各部门描述



### 居民部门

居民部门构成：

一般划分：

- 借款型居民：

- 投资和储蓄型居民：

  

特殊角色：

- 银行家；

  

其中，成员的转换：

> 参照
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]
> 的做法

居民成员中特殊角色可相互转化，每期银行家的相互转化满足泊松过程，分别以固定的退出率（转换率） $1-\lambda_{b} , \lambda_{b} \in[0,1)$， 随机退出自己岗位转为其他角色。如果退出率为0，则居民成员的角色不相互转化。

> 居民的设置参照
>
> [[方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.]]
>
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]

假设：

- 假设居民部门所有成员生存周期无限；

- 为了保证稳态时，借款型居民是经济体的净借款方，因此设借款型居民的贴现因子应小于投资和储蓄型居民的贴现因子$\gamma_{HB}<\gamma_{HI}$。

- 居民个数为$N_{H}[t]$，其中借款型居民个数为$N_{HB}[t]$，储蓄与投资型居民个数为$N_{HI}[t]$。
  $$
  N_{H}[t]=N_{HB}[t]+N_{HI}[t]
  $$
  
- 假设居民成员工作于消费品中间品生产商、房地产开发商；

- 假设居民成员持有的资金全部用于消费、投资、储蓄，暨每个时期不存在闲置货币；

- 假设居民部门所有成员提供的劳动${Lab}_{H}[t]$是同质的，暨单位生产率是一样的，此时居民提供的劳动在时期$t$，可以用一个时期内的劳动时长${Hour}_{H}[t]$表示；



#### 借款型居民

一些文献描述借款型居民为非耐心居民。

英文全名：

Borrowing Household

变量名：

household_borrowing

数学符号：

$\Box_{HB}$

##### 行为：

- 向商业银行部门之零售贷款银行分支申请借款$L_{HB,t}$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,HB}[i,t]$；

- 消费产品$C_{HB,t}$；

  
##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有偏好之于消费行为对于不同的消费项目$\alpha_{H}$；



##### 模型：

###### 目标：

借款型居民部门的个体$i$的目标是最大化其效用${Utility}_{HB}$在当前时期$t$：

$$
{Utility}_{HB}[i,t] :=
\max \quad \mathbb{E}_{i,t=0} 
\left[ \sum_{t=0}^{\infty} 
(\gamma_{HB})^{t} \left(
\alpha_{HB,PG} \; \varepsilon_{HB,PG}[t] \; \log[C_{HB,PG}[t]] 
+ \alpha_{HB,PE} \; \varepsilon_{HB,PE}[t] \; \log C_{HB,PE}[t]
- \frac{\left(Hour_{HB}[i,t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
 \right)
\right]
\tag{HB_goal}
$$

其中，
$\gamma_{HB}$：借款型居民跨时期折现因子；
$\alpha_{HB,PG}$：借款型居民消费品消费行为偏好参数；
$\varepsilon_{HB,PG}[t]$：扰动项之于借款型居民之消费品消费，在时期$t$；
$C_{HB,PG}[t]$：借款型居民的消费品消费，在时期$t$；
$Hour_{HB}[i,t]$：借款型居民的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子。注意下标里的第一个$H$表示居民部门，第二个$H$表示居民工作时长；



对于借款型居民的工作时长，在时期$t$，由如下成分组成：
$$
Hour_{HB}[i,t] := {Hour}_{HB,PG}[t]
$$
其中，
${Hour}_{HB,PG}[t]$：借款型居民在消费品中间品生产商的工作时长，在时期$t$；



###### 约束条件：





对于借款型居民，存在预算约束：

预算约束：
$$
C_{HB,PG}[t] + p_{PE}[t] \; \Delta C_{HB,PE}[t] + B_{HB,BB}[i,t-1] \; \frac{(1 + r_{BB,HB}[i,t]) }{\pi[t]} = w_{PE}[t] \; {Hour}_{HB,PE}[t] + w_{PI}[t] \; {Hour}_{HB,PG}[t] + B_{HB,BB}[i,t]+{Trans}_{HB}[t]
\tag{HB_st_budget}
$$
其中，
$C_{HB,PG}[t]$：借款型居民的消费品消费，在时期$t$；
$p_{PE}[t] \; \Delta C_{HB,PE}[t]$：房地产价格$p_{PE}[t]$与借款型居民的住房偿还贷款变动量$\Delta C_{HB,PE}[t]$的乘积，在时期$t$；
$B_{HB,BB}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$：借款型居民偿还上一期的借款给商业银行部门于本期，以借款利率$r_{BB,HB}[i,t]$，考虑当前总通胀率$\pi[t]$的影响；
$w_{PE}[t]  \; {Hour}_{HB,PE}[t]$：借款型居民获得总收入，从房地产开发商。暨房地产开发商提供的工资率$w_{HB}[i,t]$，与在房地产开发商的工作时长${Hour}_{HB,PE}[t]$的乘积，在时期$t$；
$w_{PI}[t] \; {Hour}_{HB,PG}[t]$：借款型居民获得总收入，从消费品中间品生产商。暨消费品中间品生产商提供的工资率$w_{PI}[t]$，与在消费品中间品生产商的工作时长${Hour}_{HB,PG}[t]$的乘积，在时期$t$；
$(1+r_{BB,HI}[i,t-1]) \; D_{HB}[i,t-1] / \pi[t]$：借款型居民的上一期存款$D_{HB}[i,t-1]$于本期提现，以上一期的存款利率$r_{BB,HI}[i,t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$B_{HB,BB}[i,t]$：借款型居民对银行的借款，在当期$t$；
${Trans}_{HB}[t]$：借款型居民获得的转移支付，在时期$t$；



信贷抵押约束：
$$
\left(1+r_{BB,HB}[i,t] \right) B_{HB,BB}[i,t] \leq \theta_{BB,HB}[t] \; \mathbb{E}_{i,t} \left[ p_{PE}[t+1] \; \pi[t+1] \; C_{HB,PE}[t] \right]
\tag{HB_st_debt}
$$
其中，
$\theta_{BB,HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{BB,HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；
$B_{HB,BB}[i,t]$：借款型居民对银行的借款；
TODO$p_{PE}[t+1] \; \pi[t+1] \; C_{HB,PE}[t]$：信贷抵押约束中，；



#### 投资和储蓄型居民

一些文献描述投资和储蓄型居民为耐心居民。

英文全名：

Investment Household

变量名：

household_investment

数学符号：

$\Box_{HI}$



##### 假设：

- [ ] TODO假设考虑存款有两种类型：短期存款、长期存款。用以建模存款挤兑现象；



##### 行为：

- 向银行部门$i$存款$D_{HI}[i,t]$，以存款利率$r_{D,t}$；
- 消费大众商品$C_{HI,PG}[i,t]$；
- 住房消费$C_{HI,PE}[i,t]$；





##### 模型：



###### 目标：



投资和储蓄型居民部门的个体$i$的目标是最大化其效用${Utility}_{HI}$在当前时期$t$：
$$
{Utility}_{HI}[i,t]:=
\max \quad \mathbb{E}_{i,t=0} \left[ 
\sum_{t=0}^{\infty}
(\gamma_{HI})^{t} 
\left(
\alpha_{HI,PG} \; \varepsilon_{HI,PG}[t] \; \log[C_{HI,PG}[i,t]] 
+ \alpha_{HI,PE} \; \varepsilon_{HI,PE}[t] \; \log C_{HI,PE}[i,t]
- \frac{\left({Hour}_{HI}[t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
\right)
\right]
\tag{HI_goal}
$$

其中，
$\gamma_{HI}$：投资和储蓄型居民跨时期折现因子；
$\alpha_{HI,PG}$：投资和储蓄型居民消费品消费行为偏好参数；
$\varepsilon_{HI,PG}[t]$：扰动项之于投资和储蓄型居民之消费品消费，在时期$t$；
$C_{HI,PG}[i,t]$：投资和储蓄型居民的消费品消费，在时期$t$；
$\alpha_{HI,PE}$：投资和储蓄型居民住房消费行为偏好参数；
$\varepsilon_{HI,PE}[t]$：扰动项之于住房消费，在时期$t$；
$C_{HI,PE}[i,t]$：投资和储蓄型居民的住房消费，在时期$t$；
${Hour}_{HI}[t]$：投资和储蓄型居民的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；


对于投资和储蓄型居民的工作时长，在时期$t$，由如下成分组成：
$$
{Hour}_{HI}[t] := {Hour}_{HI,PI}[i,t] + {Hour}_{HI,PE}[i,t]
$$
其中，
${Hour}_{HI,PI}[i,t]$：投资和储蓄型居民在消费品中间品生产商的工作时长，在时期$t$；
${Hour}_{HI,PE}[i,t]$：投资和储蓄型居民在房地产开发商的工作时长，在时期$t$；



###### 约束条件：

对于投资和储蓄型居民，存在预算约束：

$$
C_{HI,PG}[i,t] + p_{PE}[t] \; \Delta C_{HI,PE}[i,t] + D_{HI}[i,t] = w_{HI}[i,t] \; {Hour}_{HI,PE}[i,t] + (1+r_{BB,HI}[i,t-1]) \; D_{HI}[i,t-1] / \pi[t] + {Trans}_{HI}[i,t])
\tag{HI_st_budget}
$$
其中，
$C_{HI,PG}[i,t]$：投资和储蓄型居民的消费品消费，在时期$t$；
$p_{PE}[t] \; \Delta C_{HI,PE}[i,t]$：住房价格$p_{PE}[t]$与投资和储蓄型居民的住房偿还贷款变动量$\Delta C_{HI,PE}[i,t]$的乘积，在时期$t$；
$D_{HI}[i,t]$：投资和储蓄型居民在银行的储蓄；
$w_{PE}[t]  \; {Hour}_{HI,PE}[i,t]$：投资和储蓄型居民获得总收入，从房地产开发商。暨房地产开发商提供的工资率$w_{PE}[t]$，与在房地产开发商的工作时长${Hour}_{HI,PE}[i,t]$的乘积，在时期$t$；
$w_{PI}[t] \; {Hour}_{HI,PI}[i,t]$：投资和储蓄型居民获得总收入，从消费品中间品生产商。暨消费品中间品生产商提供的工资率$w_{PI}[t]$，与在消费品中间品生产商的工作时长${Hour}_{HI,PI}[i,t]$的乘积，在时期$t$；
$(1+r_{BB,HI}[i,t-1]) \; D_{HI}[i,t-1] / \pi[t]$：投资和储蓄型居民提现之存款，其存于上一期，从商业银行部门整体，以上一期的存款利率$r_{BB,HI}[i,t-1]$，考虑当前总通胀率$\pi[t]$的影响；
${Trans}_{HI}[i,t]$：投资和储蓄型居民获得的转移支付，在时期$t$；





- [ ] #### 企业家





- [ ] #### 居民部门居民类型的转换



### 消费品生产部门



##### 参考：

生产部门融资部分参考：

> 郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产商的DSGE模型分析[J]. 南方经济, (08): 29–46.



生产部门的行为：

生产部门通过外部融资或者购买资本、雇佣劳动生产最终产品，以提供居民部门消费，同时支付工资、利息。其外部融资方式主要为从商业银行和影子银行获得。生产最终产品的过程涉及到生产中间品、生产资本品。此外在研究中，为了考虑房地产的影响，我们将房地产开发商纳入到生产部门。



生产部门构成：

- 消费品生产商；
  - 生产中间品的厂商；
  - 生产最终品的厂商；
  - 资本品生产商；
- 房地产开发商；



生产部门分类：

TODO分类针对消费品厂商的生产最终品的厂商、房地产开发商，分为：

- 竞争力充足的厂商；
- 竞争力不足的厂商；



##### 假设：

- 假设消费品厂商部门生产的产品在同一时期内都能被消费掉，即无库存；

- 假定对数形式的全要素生产率${TFP}_{\Box}[t]$服从AR(1)过程；

- 资本市场、劳动力市场是完全竞争的。则在消费品中间品生产商中的每一个都将接受给定的工资和资本租金水平；

- TODO

- 在资本品生产部门中，资本品生产商具有竞争性；

- 房地产开发商；

  




> 关于生产部门的划分，直接参考：

相关构成：

~~企业家：~~

- ~~英文全名：Entrepreneurs；~~
- ~~变量名：entrepreneurs；~~
- ~~数学符号：$\Box_{E}$；~~
- ~~行为：；~~
- ~~目标：~~
- ~~满足的约束条件：~~





#### 消费品生产商

消费品生产商由消费品中间品生产商、消费品最终品生产商构成。为了简化分析消费品生产商，我们将其合并说明。





##### 参考：

消费品中间品生产商构建部分：

> [[马勇, 2013. 植入金融因素的DSGE模型与宏观审慎货币政策规则[J]. 世界经济, (07 vo 36): 68–92.]]
>
> [[马勇, 陈雨露, 2013. 宏观审慎政策的协调与搭配:基于中国的模拟分析[J]. 金融研究, (08): 57–69.]]
>
> 
>
> 









#### 消费品最终品生产商

在一些文献中，消费品最终品生产商之作用，相当于零售商之作用。

英文全名：

Final Goods Producers

变量名：

producers_final

数学符号：

$\Box_{PF}$



##### 假设

- 假设生产消费品最终品的厂商之间是充分竞争的；



##### 行为：

- 接收中间品生产商生产有差别的中间产品，组装生产出无差别的有竞争性质的最终品。

  





##### 模型：



###### 决策目标：

最大化利润，在给定消费品最终品价格$p_{PF}[t]$和中间品价格$p_{PI}[i,t]$时：
$$
{Profit}_{PF}[t] := \max _{Y_{PI}[i,t]} p_{PF}[t] Y_{PF}[t] - \int_{0}^{1} p_{PI}[i, t] Y_{PI}[i, t] \; \mathbb{d} i
\tag{PF_goal}
$$



其中，
$Y_{PF}[t]$：消费品最终品产量；

满足的约束条件：
$$
Y_{PF}[t] := \left(\int_{0}^{1} (Y_{PI}[i,t])^{\frac{\alpha_{PF} - 1}{\alpha_{PF}}} \; \mathbb{d} i\right)^{\frac{\alpha_{PF}}{\alpha_{PF}-1}}
\tag{PF_st}
$$

其中，
$\alpha_{PF}$：替代指数，暨消费品最终品生产商对于不同的由消费品中间品生产商生产的产品的替代指数；

由上述式子可列出拉格朗日函数，通过一阶条件，求得消费品中间品生产商$i$的产出需求$Y_{PI}[i, t]$：
$$
Y_{PI}[i, t] = \left(\frac{p_{PF}[t]}{p_{PI}[i, t]} \right)^{\alpha_{PF}} Y_{PF}[t]
$$



#### 消费品中间品生产商：

英文全名：

Intermediate Goods Producers

变量名：

producers_intermediate

数学符号：

$\Box_{PI}$



##### 假设：

- 假设生产消费品中间品的厂商之间不考虑互相竞争的详细过程；
- 假设生产消费品中间品的厂商的产品是同种类的，具有要素替代性；
- 假设经济中存在一系列连续的消费品中间品生产商$i \in [0,1]$连续统，意味着每一个消费品中间品生产商对该消费品中间品市场的影响都是无穷小的；
- 假设消费品中间品生产商的定价规则遵循Calvo的定价机制。
- 假设每一期从未参与消费品中间品生产商随机抽取比例为 $1-\theta_{PI,p}$数量的厂商参与重新定价；
- 假设消费品中间品生产商$j$参与定价一次$\tilde {P}_{PI}[j,t]$之后，之后不再参与被随机抽取，暨之后不能最优地重新定价；
- 假设未能参与重新定价的消费品中间品生产商的价格根据过去的通胀水平确定其指数化了的价格；
- 假设所有参与重新定价的消费品中间品生产商厂商 $j \in \mathbb{PI_{1}}$  都选择同样的价格 $\tilde{P}_{PI}[t] \equiv \tilde{P}_{PI}[j,t]$；



##### 行为：

- 一个消费品中间品生产商$i$生产$Y_{PI}[i,t]$单位的产品$i$在$t$期，以供最终厂商打包生产最终品。这里的不同的产品$i$是有差别的；

- 获取劳动力要素，从居民部门$\mathbb{H}$；

- 获取资本要素投入，获取渠道为：

  - 自身资本积累；
  - 从资本品生产商$\mathbb{PK}$购买资本；

- 消费品中间品厂商制定最优价格或者调整价格以某种机制；

- 消费品中间品生产商存在信贷约束；

  

  - [ ] 信贷约束：

  $$
  B_{PI,BB}[t] \leq \phi_{BB,PI} E_{t}\left[q_{t+1} h_{t} \pi_{t+1} / R_{t}\right]
  $$

  



##### 模型：



> 根据
>
> [[Calvo G A, 1983. Staggered prices in a utility-maximizing framework[J]. Journal of Monetary Economics, 12(3): 383–398.]]
>
> 设定中间厂商定价机制。



> 详细的推导过程跳转：
>
> [推导消费品中间品生产商较详细的过程](./../详细推导过程/推导消费品中间品生产商.mmd)
>
> 。

假设消费品中间品生产商的个体$i_{PI}$构成的集合为$\mathbb{PI}$，数量为$N_{PI}$。

为了简化分析，在这里，假设消费品中间品厂商的定价机制遵循Calvo定价机制。在第$t$期，随机以一定数量比例$(1 - \theta_{PI,p})$选择生产商$j \in \mathbb{PI_{1}}$，它们在本期参与制定价格为$\tilde{P}_{PI}[j,t]$。假设所有参与重新定价的消费品中间品生产商厂商$j$都选择同样的价格 $\tilde{P}_{PI}[t] \equiv \tilde{P}_{PI}[j,t]$。在当期，其未被选中能够参与制定最优价格之其余厂商个体$k$，构成厂商集合$\mathbb{PI_{2}}$，此时有$k \in \mathbb{PI_{2}}$。未被选中能够参与制定最优价格的厂商$k$则调整价格，其调整价格以总通货膨胀率为基准。

此时中间品生产商的最优化问题中，即包含最大化收益，也包含最小化成本问题，因此分析时考虑分为两个阶段决策。

消费品中间品生产商决策目标分为两阶段：

1. 所有的消费品中间品厂商最小化其总成本；
1. 消费品中间品生产商其可以参与制定价格的，最大化其实际预期贴现利润；





阶段1：最小化总成本。

所有的消费品中间品生产商$i$最小化其总成本$TC_{PI}$，在时期$t$。

$$
{TC}_{PI}[i,t] := \min _{{Lab}_{PI}[i,t] , K_{PI}[i,t]}  w_{PI}[t] \; {Lab}_{PI}[i,t] + r_{PK,PI}[t] \; K_{PI}[i,t]
\tag{PI_goal_010}
$$
其中，
$w_{PI}[t]$：消费品中间品生产商对居民支付单位工资（工资率），在时期$t$；
${Lab}_{PI}[i,t]$：消费品中间品生产商$i$的劳动力要素，在时期$t$；
$r_{PK,PI}[t]$：消费品中间品生产商的消耗单位资本租金率，在时期$t$；
$K_{PI}[i,t]$：消费品中间品生产商$i$的资本，在时期$t$；

这里$K_{PI}[i,t]$的生成方式包括：

- 向资本品生产商购买资本，以价格$p_{PK}[t]$；
- 借款，从金融中介机构：
  - 商业银行部门；
  
    



- [ ] 向资本品生产商获取资本：



向商业银行部门借贷：

中间品生产商获得借款$B_{PI,BB}[j,t]$来自传统商业银行$j$；





- [ ] 因此，资本$K_{PI}[i,t]$累积方程表示为：

$$
K_{PI}[i,t] = (1-\delta_{PI}) \; K_{PI}[i,t-1] + B_{PI,BB}[j,t]
\tag{PI_st_K}
$$



对于整个消费品中间品生产商部门而言，
$$
{TC}_{PI}[t] := \sum_{i=1}^{N_{PF}} {TC}_{PI}[i,t]
$$



###### 约束条件：


最小化成本问题对应约束条件：

消费品中间品生产商之生产函数$F_{PI}[\cdot]$
$$
Y_{PI}[i,t] = F_{PI}[{TFP}_{PI}[t],K_{PI}[i,t],{Lab}_{PI}[i,t]] := {TFP}_{PI}[t] \; (K_{PI}[i,t])^{\alpha_{PI}} \; ({Lab}_{PI}[i,t])^{1-\alpha_{PI}}
$$
其中，
${TFP}_{PI}[t]$：消费品领域生产的全要素生产率（技术）在时期$t$；
$K_{PI}[i,t]$ ：消费品中间品生产商$i$的资本要素；
${Lab}_{PI}[i,t]$：消费品中间品生产商$i$的劳动要素；
$\alpha_{PI}$：消费品中间品生产商各生产要素的替代指数；

~~$\Phi$：消费品中间品生产商的固定生产成本。在稳态条件下，其值被设定为产生0利润；~~

假定全要素生产率 ${TFP}_{PI}[t]$ 服从如下形式的一阶自回归AR(1)过程：
$$
\log {TFP}_{PI}[t] = \rho_{A,PI} \log {TFP}_{PI}[t-1] + \varepsilon_{A,PI}[t]
$$

其中，
$\rho_{A,PI}$：消费品中间品生产商的全要素生产率${TFP}_{PI}[t]$对应的自回归过程的回归系数；
$\varepsilon_{A,PI}[t]$：消费品中间品生产商的全要素生产率对${TFP}_{PI}[t]$应的自回归过程的扰动项；



由最优化问题的一阶条件可以得出资本$K_{PI}[i,t]$和劳动${Lab}_{PI}[i,t]$的表达式，然后代入最小化总成本表达式、约束条件，即可得消费品中间品生产商$i$的实际总成本$TC_{PI}[t]$，然后可以得到消费品中间品生产商$i$共有的实际边际成本$MC_{PI}[t]$：
$$
MC_{PI}[t]
:= \frac{TC_{PI}[t]}{Y_{PI}[t]}
= \left( 1-\alpha_{PI} \right)^{\alpha_{PI} -1} \; (\alpha_{PI})^{-\alpha_{PI}} \; \frac{(w_{PI}[t])^{1-\alpha_{PI}} \; (r_{PK,PI}[t])^{\alpha_{PI}}}{{TFP}_{PI}[t]}
$$





> 企业收支平衡约束
> 借鉴：
> 林琳, 曹勇, 肖寒, 2016. 中国式影子银行下的金融系统脆弱性[J]. 经济学(季刊), (03 vo 15): 1113–1136.

- [ ] 消费品中间品生产商应满足收支平衡约束：
  $$
  B_{BS,PI}[t] + Y_{PI}[t] + B_{PI,BB}[t]=I_{t}+C_{t}^{f}+W_{t} N_{t}+\frac{R_{t-1}^{l} L_{t-1}}{\pi_{t}}+\frac{R_{t-1}^{s} S_{t-1}}{\pi_{t}}
  $$





阶段2：制定最优价格以最大化总利润。

基于时期$t$，参与制定最优价格的消费品中间品生产商$j \in \mathbb{PI_{1}}$，通过制定最优价格最大化其实际预期贴现利润在时期$t_{s}$，暨在时期$t+t_{s}, \quad t_{s} \in [t,\infty)$。

另外，未能参与制定最优价格$\tilde{P}_{PI}[j,t]$之消费品中间品生产商$k \in \mathbb{PI_{2}}$根据过去的通货膨胀率$\pi[t-1]$确定其指数化价格为
$$
p_{PI}[k,t]=(\pi[t-1])^{\chi_{p}} \; p_{PI}[i,t-1]
$$
其中，
$\chi_{p} \in[0,1]$ ：指数化程度参数；
$\pi[\cdot]$：通货膨胀率于特定时期，其定义为
$$
\pi[t] := \frac{P[t]}{P[t-1]}
$$

其中，
$P[\cdot]$：表示物价于特定时期；



因为对于未参与定价的消费品中间品生产商$k$，价格之调整以总通货膨胀率为基准，所以消费品最终品生产商的定价规则为
$$
p_{PF}[t] = \theta_{PI,p} \; \left( (\pi[t+t_{h}-1])^{\chi_{p}} \; p_{PF}[t-1] \right)   + (1-\theta_{PI,p}) \; p_{PI}[j,t]
$$

由于我们采用的Calvo定价规则，假设了在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取所占比例为 $(1-\theta_{PI,p})$数量的厂商参与重新定价。此时意味着在时期$t$，被随机抽取中参与重新定价的厂商的数量占比为$(1 - \theta_{PI,p})$。

假设消费品中间品生产商$j$参与定价一次$\tilde{P}_{PI}[j,t]$之后，之后不再参与被随机抽取，暨之后不能最优地重新定价，从而该消费品中间品生产商$j$的价格$p_{PI}[j,t+t_{s}]$在时期$t+t_{s} \quad t_{s} \in [t,\infty)$为

$$
p_{PI}[j,t+t_{s}] = \prod_{t_{h}=1}^{t_{s}} 
\left(
	(\pi[t+t_{h}-1])^{\chi_{p}} 
\right)	
\; \tilde{P}_{PI}[j,t]
$$

消费品中间品生产商个体$j$面临的最大化问题是：

$$
\begin{align*}
& \max _{\tilde{P}_{PI}[j,t]} {Profit}_{PI}[j,t] \\
:= & \max _{\tilde{P}_{PI}[j,t]} 
\mathbb{E}_{t} \sum_{t_{s}=0}^{\infty}
\left(
(\gamma_{PI})^{t_{s}} \; (\theta_{PI,p})^{t_{s}}
\; \left(\frac{p_{PF}[t+t_{s}]}{		
			\prod_{t_{h}=1}^{t_{s}} 
      \left(
      (\pi[t+t_{h}-1])^{\chi_{p}} 
      \right)	
			\; \tilde{P}_{PI}[j,t]
    } \right)^{\alpha_{PF}} Y_{PF}[t+t_{s}]
	\;
	\left(
		\prod_{t_{h}=1}^{t_{s}} 
		\left(
		(\pi[t+t_{h}-1])^{\chi_{p}} 
		\right)	
		\; \tilde{P}_{PI}[j,t]
		- MC_{PI}[t + t_{s}]
	\right)
\right)
\end{align*}
\tag{PG_goal}
$$

其中，
$\gamma_{PI}$：消费品中间品生产商之效用贴现因子；
$\theta_{PI,p}$：在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取一定数量的厂商以参与重新定价，剩余仍未被抽取中以参与重新定价的厂商数量所占的比例；
$\alpha_{PF}$：消费品中间品生产商不同的产品的替代弹性；


上述最优化问题对应的约束条件是消费品中间品生产商$i$的产量需求：

$$
\text { s. t. } 
\quad Y_{PI}[i,t+t_{s}] = 
\left(
	\prod_{t_{h}=1}^{t_{s}} \left( (\pi[t + t_{h} - 1])^{\chi_{p}} \right) \frac{\tilde{P}_{PI}[t]}{p_{PF}[t+t_{s}]}
\right)^{-\alpha_{PF}} 
\; Y_{PF}[t+t_{s}]
$$

产量需求的约束意味着消费品中间品生产商将在每一期中生产该期价格下所需求的全部产品。

最优化问题对应的一阶条件：
$$
\tilde{P}_{PI}[t] =
\frac{\alpha_{PF}}{\alpha_{PF}-1} 
\frac
{
\mathbb{E}_{t} 
\sum \limits_{t_{s}=0}^{\infty}
	\left(
		\left(\gamma_{PI} \; \theta_{PI,p} \right)^{t_{s}} \; p_{PF}[t+t_{s}] \; MC_{PI}[t+t_{s}] \; Y_{PF}[i, t+t_{s}]
	\right)
}
{
\mathbb{E}_{t} \sum \limits_{t_{s}=0}^{\infty}
	\left(
		\left(\gamma_{PI} \; \theta_{PI,p} \right)^{t_{s}} 
		\; \prod \limits_{t_{h}=1}^{t_{s}} 
			\left(  
				(\pi[t+t_{h}-1])^{\chi_{p}} 
			\right)  
		\; Y_{PI}[i, t+t_{s}]
	\right)
}
$$

其中，
$MC_{PI}[t+t_{s]}$：消费品中间品生产商的实际边际成本。

根据消费品中间品生产商的产量$Y_{PI}[i,t]$与$Y_{PF}[t]$的关系
$$
Y_{PI}[i, t] = \left(\frac{p_{PI}[i, t]}{p_{PF}[t]} \right)^{-\alpha_{PF}} Y_{PF}[t]
$$
，然后采用Uhlig提出的对数线性化的方法，经过推导，可得消费品中间品生产商之价格水平的时变表达式

$$
(p_{PF}[t])^{1-\alpha_{PF}}
= \theta_{PI,p} \; \left((\pi[t-1])^{\chi_{p}} \; P[t-1] \right)^{1-\alpha_{PF}} + (1-\theta_{PI,p}) \; \left(\tilde{P}_{PI}[t]\right)^{1-\alpha_{PF}}
$$

通过对数线性化上面两个式子，并采用差分方法消除对未来期望值的无穷加总项，经过推导，最终可以得到如下形式的混合型新凯恩斯菲利普斯曲线（hybrid NKPC）

$$
\hat{\pi}[t] =
\frac{\gamma_{PI}}{1+\gamma_{PI} \;\chi_{p}} \mathbb{E}_{t} \; \hat{\pi}[t+1]
+
\frac{\chi_{p}}{1+\gamma_{PI} \; \chi_{p}} \; \hat{\pi}[t-1]
+
\frac
{
\left( 1-\theta_{PI,p} \right) \; \left( 1-\gamma_{PI} \theta_{PI,p} \right)
}{
\theta_{PI,p}\left(1+\gamma_{PI} \theta_{PI,p}\right)
} 
\; \hat{MC}_{PI}[t]
$$

其中，
$\hat{\Box}$：上标带尖冒号表示相应变量偏离比例相对于其其稳态值；

特别地，当 $\chi_{p}=0$ 时，上式变成前瞻型的新凯恩斯菲利普斯曲线( forward-looking NKPC)。通过引入混合性的菲利普斯曲线,有利于更好地对真实的通货膨胀过程及其动态机制进行刻画。















#### TODO资本品生产商


英文全名：

Capital Goods Producers

变量名：

producers_capital

数学符号：

$\Box_{PK}$



>
> 资本品生产商的建模描述主要参考
>
> [[马勇, 2013. 植入金融因素的DSGE模型与宏观审慎货币政策规则[J]. 世界经济, (07 vo 36): 68–92.]]
>
> 其中，(马勇, 2013)参考了
>
> [[Faia E, Monacelli T, 2007. Optimal Interest Rate Rules, Asset Prices, and Credit Frictions[J]. Journal of Economic Dynamics and Control, 31(10): 3228–3254. DOI:[10.1016/j.jedc.2006.11.006](https://doi.org/10.1016/j.jedc.2006.11.006).]]



##### 引入原因

引入资本品生产商，用以引入资本调整成本，以相对方便处理的形式。



##### 行为：

- 具有竞争性的生产资本品生产商$i$利用投资和现有资本存量生产新的资本品，这样的生产将耗费一定的物质转换成本。
- 资本品生产商获取资本渠道：
  - 金融中介机构：
    - 商业银行部门；
  - 外部融资：
    - 通过证券市场融资；







##### 模型：



资本品生产商作为经济系统中投资的重要一个代表，其资本投资获取渠道如下：

- 信贷融资比例$\phi_{CF,PK}$，信贷总规模$CF_{PK}[t] = \phi_{CF,PK}[t] \; p_{PK}[t] \; L_{PK}[t]$；
  - 从政府信贷占比$\phi_{CF,G}[t]$，对应信贷规模$\phi_{CF,G}[t] \; \phi_{CF,PK}[t] \; p_{PK}[t] \; L_{PK}[t]=B_{G}[t]$；
  - 商业银行部门信贷占比$\phi_{CF,BB}[t]$，对应信贷规模$\phi_{CF,PK}[t] \; \phi_{CF,BB}[t] \; p_{PK}[t] \; L_{PK}[t] = B_{PK,BB}[t]$；
  
- 股票市场融资项目比例$(1-\phi_{CF,PK})$，对应信贷规模$D F_{PK}[t]=(1-\phi_{CF,PK}[t]) \; p_{PK}[t] \; L_{PK}[t]$；



银行存款的贷存比：
$$
d_{BB}[t] := \frac{deposit_{BB}[t]}{credit_{BB}[t]}
$$
资本比率：
$$
k_{BB}[t] := 1-d_{BB}[t] = \frac{credit_{BB}[t] - deposit_{BB}[t]}{credit_{BB}[t]} = \frac{equity_{BB}[t]}{credit_{BB}[t]}
$$


项目回报：
$$
\bar{R}=R_t^p+\varepsilon_t
$$




###### 目标：

资本生产部门的决策问题：

$$
{Profit}_{PK}[t] := \max _{I_{PK}[t]} \quad p_{PK}[t] \; F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right] \; K_{PK}[t]-p_{PF}[t] \; I_{PK}[t]
$$





###### 约束条件：

设定资本调整成本方程（capital adjustment cost function）$F_{PK}$形式为CRS（具有一次齐次假设的）：
$$
F_{PK}\left[\frac{I_{\mathbb{PI}}[t]}{K_{PI}[t]}\right] \; K_{PI}[t]
$$

> 根据（Gertler,2007）（Mimir,2010）等人研究，

设定为：
$$
F_{PK}\left[\frac{I_{\mathbb{PI}}[t]}{K_{PI}[t]}\right] := \frac{I_{\mathbb{PI}}[t]}{K_{PI}[t]} - \frac{\eta_{PK}}{2}\left(\frac{I_{\mathbb{PI}}[t]}{K_{PI}[t]}-\delta_{PK}\right)^{2}
$$
其中，
$\eta_{PK}$：资本调整成本参数；
$\delta_{PK}$：资本品折旧率；

则对应的时变的资本累积方程为
$$
K_{PK}[t+1]=(1-\delta_{PK}) K_{PK}[t]+F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right] K_{PK}[t]
$$



###### 求解：

其中一阶条件：
$$
p_{PK}[t] \; {F_{PK}}^{\prime} \left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]=p_{PF}[t]
$$

全要素生产率${TFP}_{PK}[t]$服从AR(1)过程：

$$
\log {TFP}_{PK}[t]=\rho_{A,PK} \log {TFP}_{PK}[t-1] + \varepsilon_{A,PK}[t]
$$

其中，$\varepsilon_{A,PK}[t]$ 服从标准差为$\sigma_{A,PK}$的i.i.d.冲击。

相邻时期持有单位资本的名义总回报率$r_{PK,n}[t]$的计算如下，

$$
\begin{align*}
r_{PK,n}[t] & := r_{PK,PI}[t] + p_{PF}[t] \; 
\frac
{
	\partial \; K_{PK}[t+1]
}{
	\partial \; K_{PK}[t]
}
\\
& = r_{PK,PI}[t] + p_{PF}[t] \left((1-\delta_{PK}) - F_{PK} \left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]   \; \frac{I_{PK}[t]}{K_{PK}[t]}+F_{PK}\left[\frac{I_{PK}[t]}{K_{PK}[t]}\right]\right)
\end{align*}
$$

> 
> TODO：如何求得均衡条件？

在均衡条件下，相邻时期持有单位资本的实际总回报率$r_{PK,e}[t]$将与银行从其贷款获得的实际总回报相等 :

$$
\frac{r_{PK,n}[t+1]}{p_{PK}[t]} \equiv \frac{r_{PK,e}[t+1]}{\pi[t+1]}
$$

















### 商业银行部门

英文全名：

Commercial Bank

变量名：

bank_commercial

数学符号：

$\Box_{BB}$



##### 银行部门各银行划分：





我国整体商业银行部门按照资本规模划分：

- 五大银行；
- 其它上市银行；
- 未上市银行；

按照所有制划分：

- 全民所有制；
- 私有制；
- 混合所有制；



##### 假定：





##### 设定：



- 商业银行审查贷款用于生产部门企业，存在单位贷款供给成本率$c_{BB,P}$；





##### 行为：



对于单个商业银行$i$，有如下行为：

- 商业银行$i$从常规渠道获得资本，其融资来源：

  - 自有资本$K_{BB}[i,t]$；
  - 接受投资和储蓄型居民部门$\mathbb{HI}$整体存款资金$D_{HI}[\cdot,i,t]$至商业银行$i$；
  - 商业银行提供资金$D_{HI}[\cdot,i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需；
  - 银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$于时期$t$；
  
- 提供贷款服务：

  - 商业银行$i$提供贷款资本贷给消费品生产部门（非金融机构）：

    - 商业银行$i$提供贷款$L_{BB,PG}[i,t]$给消费品生产商部门之资本品生产商$\mathbb{PK}$，在当期；
    - 商业银行$i$收回上一期贷款$L_{BB,PK}[i,t-1]$，其贷给消费品生产商部门之资本品生产商$\mathbb{PK}$；
  - 商业银行$i$提供贷款资本贷给房地产开发商部门（非金融机构）：
    - 贷款$L_{BB,PE}[i,t]$给房地产开发商部门$\mathbb{PE}$，在当期；
    - 商业银行$i$收回上一期贷给房地产开发商部门$\mathbb{PE}$之贷款$L_{BB,PE}[i,t-1] \; (1+r_{BB,PE}[i,t-1]) / \pi[t]$；
  - 商业银行$i$提供贷款给借款型居民部门：

    - 商业银行$i$提供贷款$L_{BB,H}[i,t]$给借款型居民部门之居民$\mathbb{HB}$于当期$t$，以利率$r_{BB,HB}[i,t]$；

    - 商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,H}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$，从借款型居民部门之居民$\mathbb{HB}_{j}$；
  
- 股利分红$Dv_{BB}[t]$；

- 现有面临监管要求：
  
  - 贷存比监管$\theta_{{LDR}}[t]$：
    
    不满足规定贷存比要求对应的惩罚函数$Pun_{{LDR}}[i,t,gap_[i,t]]$；
    
  - 资本充足率监管$\theta_{CAR}$：
  
    不满足规定资本充足率要求对应的惩罚函数$Pun_{CAR}[i,t]$；





##### 模型：



对于单个商业银行$i$，有如下行为：

商业银行资本更新：

商业银行$i$从常规渠道获得资本，其融资来源主要有：

自有资本$K_{BB}[i,t]$更新：
$$
K_{BB}[i,t+1]=
\left(1-\delta_{BB}\right) K_{BB}[i,t] + (1-\theta_{BB,Dv}) \; {Profit}_{BB}[i,t]
$$

其中，
${Profit}_{BB}[i,t]$：商业银行$i$当期经营利润；
$\theta_{BB,Dv}[i,t]$：商业银行$i$的当期分红策略（所得经营利润之分红比例）；
$\delta_{BB}$：折旧率之于商业银行资本；



商业银行$i$获取投资和储蓄型居民部门$\mathbb{HI}$存款资金$D_{HI}[i,t]$，于当期。则该银行当期负债增加${Liability}_{BB,HI}[i,t]$，同时当期资金流增加；

商业银行$i$提供资金$D_{HI}[i,t-1] \; (1+r_{BB,HI}) / \pi[t]$以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需。则该银行当期负债${Liability}_{BB,HI}[i,t]$减少；

商业银行提供贷款服务：

商业银行$i$提供贷款$L_{BB,H}[i,t]$给借款型居民部门之居民$\mathbb{HB}$于当期$t$，以利率$r_{BB,HB}[i,t]$。则该银行当期资产${Assets}_{BB,HB}[i,t]$增加，同时当期资金流减少；

商业银行$i$收回上一期贷给借款型居民部门$\mathbb{HB}$之贷款$L_{BB,HB}[i,t-1] \; \left(1 + r_{BB,HB}[i,t]\right) / \pi[t]$。则该银行当期资产${Assets}_{BB,HB}[i,t]$减少，同时当期资金流增加；

商业银行$i$提供贷款资本$L_{BB,PK}[i,t]$贷给消费品生产商部门之资本品生产商$\mathbb{PK}$，于当期，以利率$r_{BB,PK}[i,t]$。则该银行当期资产增加${Assets}_{BB,PK}[i,t]$，同时当期资金流减少；

商业银行$i$收回上一期贷款$L_{BB,PK}[i,t-1] \; (1+r_{BB,PK}[i,t-1]) / \pi[t]$，其贷给消费品生产商部门之资本品生产商$\mathbb{PK}$。则该银行当期资产减少${Assets}_{BB,PG}[i,t-1]$，同时当期资金流增加；

商业银行$i$提供贷款资本$L_{BB,PE}[i,t]$贷给房地产开发商部门（非金融机构）。则该银行当期资产增加${Assets}_{BB,PE}[i,t]$；

商业银行$i$收回上一期贷款$L_{BB,PE}[i,t-1] \; (1+r_{BB,PE}[i,t-1]) / \pi[t]$。则该银行当期资产${Assets}_{BB,PE}[i,t]$减少，同时当期资金流增加；







股利分红：

商业银行对于最终经营收入按照比例$\theta_{BB,Dv}[i,t]$做股利分红$Dv_{BB}[i,t]$：
$$
{Dv}_{BB}[i,t] := \theta_{BB,Dv}[i,t] \; {Profit}_{BB}[i,t]
$$
由于我国国情，股利分红几乎可以忽略不计。



银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$于时期$t$。具体将在下文描述。




商业银行$i$面临广义政府部门监管要求：

- 贷存比监管$\theta_{{LDR}}[t]$：

  不满足规定贷存比要求对应的惩罚函数$Pun_{{LDR}}[i,t,gap_[i,t]]$；

- 资本充足率监管$\theta_{CAR}$：

  不满足规定资本充足率要求对应的惩罚函数$Pun_{CAR}[i,t]$；





由上述资金流变动情况，可得商业银行当期资金流变动公式：
$$
Cash_{BB}[i,t] := Cash_{}
$$




###### 目标



> 借鉴
>
> 瞿凌云, 许文立, 钱国军, 2019. 宏观审慎框架下通道套利监管的有效性研究——基于动态随机一般均衡模型(DSGE)的分析[J]. 金融经济学研究, (05 vo 34): 10–22.
>
> 的目标最优化函数。

对于单个商业银行$i$，其最优化目标有几个：商业信誉、利润。为了方便起见，我们主要以最大化跨期利润作为最优化目标的重点。

最大化商业信誉：
$$
{Reputation}_{BB}[i,t]:=
\max
商业信誉的度量
$$

2. 最大化跨期利润${Profit}_{BB}[i,t]$：

$$
{Profit}_{BB}[i,t]
:=
\max _{
\left\{
\begin{array}{c}
r_{BB,HI}[i,t],r_{BB,HB}[i,t],r_{BB,PK}[i,t],r_{BB,PE}[i,t]\\
D_{BB,HI}[i,t],L_{BB,HB}[i,t]\\
\end{array}
\right\}
}
\mathbb{E}_t \left[
\sum_{t=0}^{\infty} 
\left(\gamma_{BB}\right)^{t} 
\left(
\begin{gather}
D_{HI}[i,t]
-D_{HI}[i,t-1] \; \frac{(1+r_{BB,HI})}{\pi[t]}
\\
+L_{BB,PK}[i,t-1] \; \frac{(1+r_{BB,PK}[i,t]-\delta_{PK})}{\pi[t]}
-L_{BB,PK}[i,t] \; (1+c_{BB,P}[t])
\\
-Pun_{CAR}[i,t,gap[i,t]]
\end{gather}
\right)
\right]
$$

其中，

$D_{HI}[i,t]$：居民部门存款于商业银行$i$的资金；

$D_{HI}[i,t-1] \; (1+r_{BB,HI}) / \pi[t]$：提供资金以供投资和储蓄型居民部门$\mathbb{HI}$提取上一期存款所需；

$\mathcal{Pr}_{def,BS}[t]$：影子银行当期违约概率；

$L_{BB,PK}[i,t-1] \; (1+r_{BB,PK}[i,t]-\delta_{PK}) / \pi[t]$：收回上一期贷给消费品生产商部门之资本品生产商部门$\mathbb{PK}$之贷款所获得的收入；

$L_{BB,PK}[i,t] \; (1+c_{BB,P}[t])$：商业银行$i$贷款给生产部门之消费品生产商的资本品生产商，在当期，与此同时付出审查成本率$c_{BB,P}[t]$；

$Pun_{CAR}[i,t,gap[i,t]]$：商业银行$i$面临不满足规定的资本充足率要求对应的惩罚函数，于时期$t$；

$Pun_{{LDR}}[i,t,gap_[i,t]]$：商业银行$i$面临不满足规定的贷存比要求对应的惩罚函数，于时期$t$；

TODO同业拆借；





TODO企业对银行$j$的贷款需求
$$
L^E_t[j]=\left( \frac{r^E_t[j]}{r^E_t} \right)^{-\varepsilon^E} L^E_t
$$

其中，$\varepsilon^E$表示企业家对银行$j$的贷款需求弹性，衡量银行$j$的垄断程度。


$$
b_{t}^{I}(j)=\left(\frac{r_{t}^{b H}(j)}{r_{t}^{b H}}\right)^{-\varepsilon_{t}^{b H}} b_{t}^{I}
$$


假设商业银行为贷款给企业，其付出审查成本率$c_{BB,P}[t]$满足如下AR(1)过程：
$$
c_{BB,P}[t]:=\rho_{c_{BB,P}} \; c_{BB,P}[t-1] + \varepsilon_{c_{BB,P}}[t]
$$







###### 约束条件：



商业银行$i$面临每一时期的资产负债表平衡约束。其资产负债表可表示为：

$$
{Assets}_{BB}[i,t] = {Liability}_{BB}[i,t] + {Equity}_{BB}[i,t]
$$
其中，
${Assets}_{BB}[i,t]$：商业银行$i$之当期的总资产；
${Liability}_{BB}[i,t]$：商业银行$i$之当期的总负债；
${Equity}_{BB}[i,t]$：商业银行$i$之当期的总所有者权益；

对于商业银行$i$之当期总资产${Assets}_{BB}[i,t]$，由如下构成：
$$
{Assets}_{BB}[i,t] := {Assets}_{BB,HB}[i,t] + {Assets}_{BB,PK}[i,t] + {Assets}_{BB,BI}[i,t]
$$
TODO对于商业银行对于商业银行$i$之当期总负债${Liability}_{BB}[i,t]$，由如下构成：
$$
{Liability}_{BB}[i,t] := {Liability}_{BB,HI}[i,t] + {Liability}_{BB,BI}[i,t] + {Assets}_{BB,BI}[i,t]
$$






商业银行$i$面临资产负债表平衡约束：
$$
L_{BB,PE}[i,t] + L_{BB,PK}[i,t] + L_{BB,H}[i,t] = D_{HI}[\cdot,i,t] + D_{HI}[i,t] + B_{BI}[i,j,t] + K_{BB}[i,t]
$$



监管之贷存比约束：
$$

$$

监管之资本充足率约束：

> 参考：
>
> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.p31





部门构成：

- 银行家：
  - 英文全名：Banker
  - 





### 银行家TODO

TODO











### 银行间市场

TODO





### 广义政府部门

TODO



英文全名：

Capital Goods Producers

变量名：

producers_capital

数学符号：

$\Box_{PK}$







##### 假设：





##### 构成：

广义政府部门划分为：

- 政府运转部门；

  - 财政部门：提供政府融资、采购、消费等服务；

  

- 中央银行和银监会：

  - 货币政策、宏观审慎政策、微观审慎政策；



##### 行为：



政府的行为：

- 财政政策；
- 税收；
- 居民福利转移；

中央银行和监管当局的行为：

- 货币政策：
  - 相关的货币政策工具：
    - Taylor Rules，通过调控利率以调控投资。

- 公开市场操作：

- 控制商业银行的资本充足率要求；

  - 调控方式：

- 控制商业银行的存款准备金率$\theta_{DR}$；

- 贷款价值比（LTVs）；

- 贷存比要求；

  

  






##### 定义：

定义传统资本充足率要求：
$$
\theta_{CAR}[t]:=\tilde{CAR}
$$



定义贷存比要求：
$$
\theta_{{LDR}}[t] := \tilde{{LDR}}
$$



##### 模型：








> 资本充足率监管惩罚函数，借鉴 GNSS模型
>
> Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.

定义中央银行对商业银行$i$的资本充足率惩罚函数$Pun_{CAR}[i,t,gap_[i,t]]$：
$$
Pun_{{CAR}}[i,t,Gap_{CAR}[i,t]] := \frac{1}{2} \; \kappa_{CAR} \left(  \right)
$$



构建传统货币政策调控方式Talor Rule：
$$
\log \left(\frac{R_{t}}{R}\right)=\kappa_{r} \log \left(\frac{R_{t-1}}{R}\right)+\left(1-\kappa_{r}\right)\left[\kappa_{y} \log \left(\frac{Y_{t}}{Y}\right)+\kappa_{\pi} \log \left(\frac{\pi_{t}}{\pi}\right)\right]+\varepsilon_{t}^{r}
$$


贷存比要求：
$$
\theta_{{LDR}}[t] := {L_t}/{\tilde{D}_{BB,H}[i,t]}
$$

定义中央银行对商业银行$i$不满足规定的贷存比要求对应的惩罚函数，于时期$t$：
$$
Pun_{{LDR}}[i,t,Gap_{{LDR}}[i,t]] := \frac{1}{2} \;
$$






### 宏观经济处于理想均衡状态下，市场出清





## DSGE模型框架方程组之于纳入计算的




借款型居民之优化目标(HB_goal)

借款型居民之预算约束(HB_st_budget)

借款型居民之信贷约束(HB_st_debt)

贷款型居民之优化目标(HI_goal)

贷款型居民之预算约束(HI_st_budget)



## DSGE模型框架方程组之于纳入计算均衡解的





## 参数校准和估计





考虑到中国股票市场较少分红的现实 ， 假设银行的利润用来分红的比例$1-\theta_{BB,s}=0$，即全部用来补充银行资本。