# 系统性金融风险建模

> 系统性金融风险建模之方案\_010


[TOC]



## 总假设之于DSGE模型框架



- 考虑一个离散时间的、无限生命周期的经济体。
- 假设信贷市场属于标准的Dixit-Stiglitz模式；
- 



## DSGE模型框架之调用模块




| 部门         | 模块  | 备注 |
| ------------ | ----- | ---- |
| 居民部门     | H020  |      |
| 消费品生产商 | PG010 |      |
| 房地产开发商 | PE010 |      |
| 商业银行部门 |       |      |
| 影子银行部门 |       |      |
| 广义政府部门 |       |      |
|              |       |      |
|              |       |      |

  






## DSGE模型框架之各部门描述



### 居民部门

居民部门构成：

一般划分：

- 借款型居民：

- 投资和储蓄型居民：

  

特殊角色：

- 银行家；

  

其中，成员的转换：

> 参照
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]
> 的做法

居民成员中特殊角色可相互转化，每期银行家的相互转化满足泊松过程，分别以固定的退出率（转换率） $1-\lambda_{b} , \lambda_{b} \in[0,1)$， 随机退出自己岗位转为其他角色。如果退出率为0，则居民成员的角色不相互转化。

> 居民的设置参照
>
> [[方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.]]
>
> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]

假设：

- 假设居民部门所有成员生存周期无限；

- 为了保证稳态时，借款型居民是经济体的净借款方，因此设借款型居民的贴现因子应小于投资和储蓄型居民的贴现因子$\gamma_{HB}<\gamma_{HI}$。

- 居民个数为$N_{H}[t]$，其中借款型居民个数为$N_{HB}[t]$，储蓄与投资型居民个数为$N_{HI}[t]$。
  $$
  N_{H}[t]=N_{HB}[t]+N_{HI}[t]
  $$
  
- 假设居民成员工作于消费品中间品生产商、房地产开发商；

- 假设居民成员持有的资金全部用于消费、投资、储蓄，暨每个时期不存在闲置货币；

- 假设居民部门所有成员提供的劳动${La}_{H}[i,t]$是同质的，暨单位生产率是一样的，此时居民成员个体$i$提供的劳动在时期$t$，可以用劳动时长$H_{H}[i,t]$表示；



#### 借款型居民

一些文献描述借款型居民为非耐心居民。

英文全名：

Borrowing Household

变量名：

household_borrowing

数学符号：

$\Box_{HB}$

##### 行为：

- 向商业银行部门之零售贷款银行分支申请借款$L_{HB,t}$，以商业银行对居民的贷款利率（等价于居民的借款利率）$r_{BB,H}[t]$；

- 消费产品$C_{HB,t}$；

  
  
##### 特点：

具有跨期折现偏好$\gamma_{H}$；

具有偏好之于消费行为对于不同的消费项目$\alpha_{H}$；



##### 模型：

###### 目标：

借款型居民部门的个体$i$的目标是最大化其效用$\mathrm{Utility}_{HB}$在当前时期$t$：

$$
\mathrm{Utility}_{HB}[i,t] :=
\max \quad \mathbb{E}_{i,t=0} 
\left[ \sum_{t=0}^{\infty} 
(\gamma_{HB})^{t} \left(
\alpha_{HB,c} \; \varepsilon_{HB,c}[t] \; \log[C_{HB,c}[i,t]] 
+ \alpha_{HB,h} \; \varepsilon_{HB,h}[t] \; \log C_{HB,h}[i,t]
- \frac{\left(H_{HB}[i,t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
 \right)
\right]
\tag{HB_goal}
$$

其中，
$\gamma_{HB}$：借款型居民跨时期折现因子；
$\alpha_{HB,c}$：借款型居民大众消费行为偏好参数；
$\varepsilon_{HB,c}[t]$：扰动项之于借款型居民之大众消费，在时期$t$；
$C_{HB,c}[i,t]$：借款型居民$i$的大众消费，在时期$t$；
$\alpha_{HB,h}$：借款型居民住房消费行为偏好参数；
$\varepsilon_{HB,h}[t]$：扰动项之于住房消费，在时期$t$；
$C_{HB,h}[i,t]$：借款型居民$i$的住房消费，在时期$t$；
$H_{HB}[i,t]$：借款型居民$i$的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；



对于借款型居民$i$的工作时长，在时期$t$，由如下成分组成：
$$
H_{HB}[i,t] := H_{HB,PI}[i,t] + H_{HB,PE}[i,t]
$$
其中，
$H_{HB,PI}[i,t]$：借款型居民$i$在消费品中间品生产商的工作时长，在时期$t$；
$H_{HB,PE}[i,t]$：借款型居民$i$在房地产开发商的工作时长，在时期$t$；



###### 约束条件：





对于借款型居民$i$，存在预算约束：

预算约束：
$$
C_{HB,c}[i,t] + p_{PE}[t] \; \Delta C_{HB,h}[i,t] + B_{BB,HB}[i,t-1] \; \frac{(1 + r_{b,HB}[t]) }{\pi[t]} = w_{PE}[i,t] \; h_{HB,PE}[i,t] + w_{PI}[i,t] \; h_{HB,PI}[i,t] + B_{BB,HB}[i,t]+tr_{HB}[i,t]
\tag{HB_st_budget}
$$
其中，
$C_{HB,c}[i,t]$：借款型居民$i$的大众消费，在时期$t$；
$p_{PE}[t] \; \Delta C_{HB,h}[i,t]$：房地产价格$p_{PE}[t]$与借款型居民$i$的住房偿还贷款变动量$\Delta C_{HB,h}[i,t]$的乘积，在时期$t$；
$B_{BB,HB}[i,t-1] \; \left(1 + r_{b,HB}[t]\right) / \pi[t]$：借款型居民$i$偿还上一期的借款给商业银行部门于本期，以借款利率$r_{b,HB}[t]$，考虑当前总通胀率$\pi[t]$的影响；
$w_{PE}[i,t]  \; h_{HB,PE}[i,t]$：借款型居民$i$获得总收入，从房地产开发商。暨房地产开发商提供的工资率$w_{HB}[i,t]$，与在房地产开发商的工作时长$H_{HB,PE}[i,t]$的乘积，在时期$t$；
$w_{PI}[i,t] \; h_{HB,PI}[i,t]$：借款型居民$i$获得总收入，从消费品中间品生产商。暨消费品中间品生产商提供的工资率$w_{PI}[i,t]$，与在消费品中间品生产商的工作时长$H_{HB,PI}[i,t]$的乘积，在时期$t$；
$(1+r_{d}[t-1]) \; D_{HB}[i,t-1] / \pi[t]$：借款型居民$i$的上一期存款$D_{HB}[i,t-1]$于本期提现，以上一期的存款利率$r_{d}[t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$B_{BB,HB}[i,t]$：借款型居民$i$对银行的借款，在当期$t$；
$tr_{HB}[i,t]$：借款型居民$i$获得的转移支付，在时期$t$；



信贷抵押约束：
$$
\left(1+r_{b,HB}[t] \right) B_{BB,HB}[i,t] \leq \theta_{HB}[t] \; \mathbb{E}_{i,t} \left[ p_{PE}[t+1] \; \pi[t+1] \; C_{HB,h}[t] \right]
\tag{HB_st_debt}
$$
其中，
$\theta_{HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；
$B_{BB,HB}[i,t]$：借款型居民$i$对银行的借款；
TODO$p_{PE}[t+1] \; \pi[t+1] \; C_{HB,h}[t]$：信贷抵押约束中，；



#### 投资和储蓄型居民

一些文献描述投资和储蓄型居民为耐心居民。

英文全名：

Investment Household

变量名：

household_investment

数学符号：

$\Box_{HI}$



##### 假设：

- 假设考虑存款有两种类型：短期存款、长期存款。用以建模存款挤兑现象；



##### 行为：

- 向银行部门的银行零售银行存款分支存款$D_{HI}[i,t]$，以存款利率$r_{D,t}$；
- 消费大众商品$C_{HI,c}[i,t]$；
- 住房消费$C_{HI,h}[i,t]$；





##### 模型：



###### 目标：



投资和储蓄型居民部门的个体$i$的目标是最大化其效用$\mathrm{Utility}_{HI}$在当前时期$t$：
$$
\mathrm{Utility}_{HI}[i,t]:=
\max \quad \mathbb{E}_{i,t=0} \left[ 
\sum_{t=0}^{\infty}
(\gamma_{HI})^{t} 
\left(
\alpha_{HI,c} \; \varepsilon_{HI,c}[t] \; \log[C_{HI,c}[i,t]] 
+ \alpha_{HI,h} \; \varepsilon_{HI,h}[t] \; \log C_{HI,h}[i,t]
- \frac{\left(H_{HI}[i,t]\right)^{1+\alpha_{H,H}}}{1+\alpha_{H,H}}
\right)
\right]
\tag{HI_goal}
$$

其中，
$\gamma_{HI}$：投资和储蓄型居民跨时期折现因子；
$\alpha_{HI,c}$：投资和储蓄型居民大众消费行为偏好参数；
$\varepsilon_{HI,c}[t]$：扰动项之于投资和储蓄型居民之大众消费，在时期$t$；
$C_{HI,c}[i,t]$：投资和储蓄型居民$i$的大众消费，在时期$t$；
$\alpha_{HI,h}$：投资和储蓄型居民住房消费行为偏好参数；
$\varepsilon_{HI,h}[t]$：扰动项之于住房消费，在时期$t$；
$C_{HI,h}[i,t]$：投资和储蓄型居民$i$的住房消费，在时期$t$；
$H_{HI}[i,t]$：投资和储蓄型居民$i$的工作时长，在时期$t$；
$\alpha_{H,H}$：居民工作时长对效用的指数因子；


对于投资和储蓄型居民$i$的工作时长，在时期$t$，由如下成分组成：
$$
H_{HI}[i,t] := H_{HI,PI}[i,t] + H_{HI,PE}[i,t]
$$
其中，
$H_{HI,PI}[i,t]$：投资和储蓄型居民$i$在消费品中间品生产商的工作时长，在时期$t$；
$H_{HI,PE}[i,t]$：投资和储蓄型居民$i$在房地产开发商的工作时长，在时期$t$；



###### 约束条件：

对于投资和储蓄型居民$i$，存在预算约束：

$$
C_{HI,c}[i,t] + p_{PE}[t] \Delta C_{HI,h}[i,t] + D_{HI}[i,t] = w_{HI}[i,t] C_{HI,h}[i,t] + (1+r_{d}[t-1]) D_{HI}[i,t-1] / \pi[t] + tr_{HI}[i,t])
\tag{HI_st_budget}
$$
其中，
$C_{HI,c}[i,t]$：投资和储蓄型居民$i$的大众消费，在时期$t$；
$p_{PE}[t] \; \Delta C_{HI,h}[i,t]$：住房价格$p_{PE}[t]$与投资和储蓄型居民$i$的住房偿还贷款变动量$\Delta C_{HI,h}[i,t]$的乘积，在时期$t$；
$D_{HI}[i,t]$：投资和储蓄型居民$i$在银行的储蓄；
$w_{PE}[i,t]  \; H_{HI,PE}[i,t]$：投资和储蓄型居民$i$获得总收入，从房地产开发商。暨房地产开发商提供的工资率$w_{PE}[i,t]$，与在房地产开发商的工作时长$H_{HI,PE}[i,t]$的乘积，在时期$t$；
$w_{PI}[i,t] \; H_{HI,PI}[i,t]$：投资和储蓄型居民$i$获得总收入，从消费品中间品生产商。暨消费品中间品生产商提供的工资率$w_{PI}[i,t]$，与在消费品中间品生产商的工作时长$H_{HI,PI}[i,t]$的乘积，在时期$t$；
$(1+r_{d}[t-1]) \; D_{HI}[i,t-1] / \pi[t]$：投资和储蓄型居民$i$提现之存款，其存于上一期，从商业银行部门整体，以上一期的存款利率$r_{d}[t-1]$，考虑当前总通胀率$\pi[t]$的影响；
$tr_{HI}[i,t]$：投资和储蓄型居民$i$获得的转移支付，在时期$t$；





### 生产部门



- [ ] ### 企业家（是否保留？）









### 消费品生产部门



##### 参考：



> 参考：
>
> 郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产商的DSGE模型分析[J]. 南方经济, (08): 29–46.



##### 行为：

消费品生产部门通过外部融资、雇佣劳动生产最终产品，以提供居民部门消费，同时支付工资、利息。其外部融资方式主要为从商业银行和影子银行获得。



##### 构成：

- 消费品生产商；

  



##### 分类：

无。



##### 假设：





- [ ] ##### 描述：













### 房地产开发商部门TODO

TODO

英文全名：

Real Estate Producers

变量名：

producers_estate

数学符号：

$\Box_{PE}$





##### 行为：

- 从商业银行获得贷款；
- 从影子银行部门获得融资；
- 采用资本、劳动、土地开发建设房地产；



> 房地产开发商部分参考
>
> [[郭娜, 马莹莹, 张宁, 2018. 我国影子银行对银行业系统性风险影响研究——基于内生化房地产开发商的DSGE模型分析[J]. 南方经济, (08): 29–46.]]
>
> 



##### 模型：

房地产开发商部门的生产函数$F_{PE}$符合规模报酬不变的特性。

对于整个房地产开发商部门来说，其生产函数$F_{PE}[\cdot]$：

$$
Y_{PE}[t] = F_{PE}[A_{PE}[t],K_{PE}[t],La_{PE}[t],H_{PE}[t]] := A_{PE}[t] \; (K_{PE}[t-1])^{\alpha_{PE,K}} (La_{PE}[t])^{\alpha_{PE,L}} (H_{PE}[t-1])^{\alpha_{PE,H}}
$$

其中，
$Y_{PE}[t]$：房地产开发商的最终产出；
$A_{PE}[t]$：房地产开发商的全要素生产率；
$K_{PE}[t-1]$：房地产开发商之资本存量，在上一时期；
$H_{PE}[t-1]$：房地产存量，在上一时期；
$La_{PE}[t]$：房地产商投入的劳动力要素；
$H_{PE}[t-1]$：房地产商投入的房地产商品存量，在上一时期；
$\alpha_{PE,K}$：房地产开发商投入资本要素所占的替代指数；
$\alpha_{PE,L}$：房地产开发商投入劳动要素所占的替代指数；
$\alpha_{PE,H}$：房地产开发商投入房地产要素所占的替代指数；

其中，满足

$$
\alpha_{PE,K}+\alpha_{PE,L}+\alpha_{PE,H}=1​
$$



###### 目标：


整体商地产开发商部门之目标在于最大化其消费：

$$
\max \mathbb{E}_{t} \sum_{t=0}^{\infty} \gamma_{PE} \; \ln C_{PE}[t]
$$

其中，
$C_{PE}[t]$：房地产开发商之消费；
$\gamma_{PE}$：贴现因子，$0<\gamma_{PE}<1$ 。



###### 约束条件：

房地产开发商所受现金流的约束条件如下:

$$
Y_{PE}[t] + B_{BB,PE}[t] + B_{BS,PE}[t] = C_{PE}[t] + p_{PE}[t] \; \left(H_{PE}[t] - H_{PE}[t-1]\right) + w_{PE}[t] \; La_{PE}[t] + B_{BB,PE}[t-1] \; \frac{(1+r_{BB,PE}[t-1])}{\pi[t]} + B_{BS,PE}[t-1] \; \frac{(1+r_{BS,PE}[t-1])}{\pi[t]} + I_{PE}[t]
$$

TODO理解和替换相关变量

其中，
$Y_{PE}[t]$：房地产开发商的产出；
$B_{BB,PE}[t]$：房地产开发商从商业银行借款，在时期$t$；
$r_{BB,PE}[t]$：商业银行向房地产开发商的贷款利率；
$p_{PE}[t]$：房地产价格：
$B_{BS,PE}[t]$：房地产开发商向影子银行获取的贷款的数量；
$r_{BS,PE}[t]$：影子银行向房地产开发商的贷款利率；
$I_{PE}[t]$：房地产开发商的投资；
$\left(H_{PE}[t]-H_{PE}[t-1]\right)$：房地产流量，在当期的时候；
$w_{PE}[t]$：房地产开发商提供的支付单位工资，暨工资率，在时期$t$；
$La_{PE}[t]$：房地产商的劳动力资源要素，在时期$t$，体现为房地产开发商提供的工资率；

房地产开发企业总体信贷规模为 $B_{PE}[t] := SH_{}[t]+B_{BB,PE}[t]$。

房地产开发商的投资 $I_{PE}[t]$ 与资本存量 $K_{PE}[t]^{h}$ 之间存在如下关系:

$$
(K_{PE}[t+1])^{h}=I_{PE}[t]+(1-\delta) (K_{PE}[t])^{h}
$$

该式表示的是房地产开发商资本存量的积累情况, $\delta$ 表示资本折旧率。

> 本文借鉴
>
> [[Christensen I, Dib A, 2008. The Financial Accelerator in an Estimated New Keynesian Model[J]. Review of Economic Dynamics, 11(1): 155–178. DOI:[10.1016/j.red.2007.04.006](https://doi.org/10.1016/j.red.2007.04.006).]]
>
> [[Iacoviello M, 2005. House Prices, Borrowing Constraints, and Monetary Policy in the Business Cycle[J]. American Economic Review, 95(3): 739–764. DOI:[10.1257/0002828054201477](https://doi.org/10.1257/0002828054201477).]]
>
> 的研究，引入信贷约束机制

对于商业银行来说，由于存在信贷约束机制。通过引入信贷约束机制，房地产开发商将其持有的房地产抵押给商业银行获得抵押贷款，但是其所获得的抵押贷款的数量取决于其还款期抵押品的预期价值。假设 $\theta_{PE} \in (0,1)$ 为房地产开发商信贷约束比例，需满足:

$$
B_{BB,PE}[t] \leq \theta_{PE} \frac{\mathbb{E}_{t} \left[p_{PE}[t+1] \; H_{PE}[t] \; \pi[t+1]\right]}{r_{BB,PE}[t]}
$$

其中，
$\theta_{PE}$：为房地产开发商信贷约束比例；
$B_{BB,PE}[t]$：房地产开发商从商业银行借款，在时期$t$；
$r_{BB,PE}[t]$：商业银行向房地产开发商的贷款利率；
$H_{PE}[t]$：房地产部门整体存量，在当期的时候；













### 商业银行部门

英文全名：

Commercial Bank

变量名：

bank_commercial

数学符号：

$\Box_{BB}$



##### 银行部门各银行划分：





我国整体商业银行部门按照资本规模划分：

- 五大银行；
- 其它上市银行；
- 未上市银行；





##### 假定：

- 当银行的风险加权资产比例$\left(K_{t}^{b} / \varpi_{t} L_{t}\right)$偏离监管机构的资本充足率要求$v_t$时，银行将付出监管成本；



##### 设定：



- 商业银行审查生产部门之企业用以贷款，存在单位贷款供给成本率$c_{BB,s}$；





##### 行为：

- [ ] 对于单个商业银行$i$，有如下行为：


- 从常规渠道获得资本，其融资来源：

  - 自有资本$K_{BB}[i,t]$更新自上一时期；
  - 居民部门整体存款资金$D_{H}[\cdot,i,t]$至商业银行$i$；
  - 银行部门同业拆借。暨商业银行$i$向商业银行$j$拆借资金$B_{BI}[i,j,t]$于时期$t$；

- 偿还借款：

  - 向居民部门

- 提供贷款服务：

  - 将资本贷给生产部门（非金融机构）；

  - 商业银行$i$提供贷款$B_{BB,HB}[i,j,t]$给居民部门之居民$H_j$于时间$t$，以利率$r_{BB,H}[t]$；

    

  







##### 模型：



> 参考：
>
> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.p31



- [ ] 企业对银行$j$的贷款需求

$$
L^E_t[j]=\left( \frac{r^E_t[j]}{r^E_t} \right)^{-\varepsilon^E} L^E_t
$$

其中，$\varepsilon^E$表示企业家对银行$j$的贷款需求弹性，衡量银行$j$的垄断程度。









部门构成：

- 银行家：
  - 英文全名：Banker
  - 





### 银行家TODO

TODO











### 影子银行部门TODO

TODO

英文全名：

Shadow Bank

变量名：

bank_shadow

数学符号：

$\Box_{BS}$



##### 假设：

- 影子银行可以退出市场，当每期的影子银行产品到期兑付之后；

- 设定影子银行为多主体模型，与商业银行部门银行类似；



##### 行为：

- 销售理财产品给家庭部门；
- 接受资产转移从商业银行部门；
- 融资给生产部门；
- 影子银行可以退出市场，当每期的影子银行产品到期兑付之后；







##### 模型：









### 银行间市场

TODO





### 广义政府部门

TODO



英文全名：

Capital Goods Producers

变量名：

producers_capital

数学符号：

$\Box_{PC}$







##### 假设：





##### 构成：

广义政府部门划分为：

- 政府运转部门；

  - 财政部门：提供政府融资、采购、消费等服务；

  

- 中央银行和银监会：

  - 货币政策、宏观审慎政策、微观审慎政策；



##### 行为：

中央银行的行为：

- 货币政策
  - 相关的货币政策工具：
    - 

- 控制商业银行的资本充足率要求；

  - 调控方式：

  

- 控制影子银行的资本充足率要求；

- 存贷比要求；

  





##### 模型：

定义传统资本充足率：
$$

$$


构建传统货币政策调控方式：
$$
\ln \left(\frac{R_{t}}{R}\right)=\kappa_{r} \ln \left(\frac{R_{t-1}}{R}\right)+\left(1-\kappa_{r}\right)\left[\kappa_{y} \ln \left(\frac{Y_{t}}{Y}\right)+\kappa_{\pi} \ln \left(\frac{\pi_{t}}{\pi}\right)\right]+\varepsilon_{t}^{r}
$$


存贷比要求：
$$
\eta_t \triangleq {L_t}/{D_t}
$$









- [ ] 
  ### 宏观经济处于理想均衡状态下，市场出清






- [ ] ## DSGE模型框架之方程组之于纳入计算的




借款型居民之优化目标(HB_goal)

借款型居民之预算约束(HB_st_budget)

借款型居民之信贷约束(HB_st_debt)

贷款型居民之优化目标(HI_goal)

贷款型居民之预算约束(HI_st_budget)



## DSGE模型框架之方程组之于纳入计算均衡解的

