"程序：定义模型agents变量AgentsVariables"

## 程序：定义模型agents变量AgentsVariables

##########################################
#状态/使用
# 备注：改成用字典表示
############

## 生成字典变量，通过命名元组变量
bankCommercial_dict = Dict(pairs(set_bankCommercialVariables))
bankInterbank_dict = Dict(pairs(set_interbankVariables))


## 生成字典变量  #TODO 如何实现自动生成字典变量？
# bankCommercial = @dict(
#     banks_id,
#     banks_abbr,
#     banks_name,
#     banks_A_all,
#     banks_A_BI_all,
#     banks_A_exBI,
#     banks_A_P,
#     banks_A_Q,
#     banks_A_R,
#     banks_A_other,
#     banks_Z_all,
#     banks_Z_BI_all,
#     banks_Z_exBI,
#     banks_Z_D,
#     banks_Z_other,
#     banks_E_all,
#     banks_T_all,
#     banks_Lo_all,
#     banks_Lo_BI_all,
#     banks_Lo_exBI,
#     banks_Lo_P,
#     banks_Li_all,
#     banks_Li_BI_all,
#     banks_Li_exBI,
#     banks_Li_P,
#     banks_Bi_all,
#     banks_Bi_BI_all,
#     banks_Bi_exBI,
#     banks_Bi_D,
#     banks_Bo_all,
#     banks_Bo_BI_all,
#     banks_Bo_exBI,
#     banks_Bo_D,
#     banks_Shock_t,
#     banks_Shock_s,
#     banks_Shock_def_t,
#     banks_Shock_def_s,
#     banks_Shock_run_t,
#     banks_Shock_run_s,
#     banks_Shock_exBI_t,
#     banks_Shock_exBI_s,
#     banks_Shock_P_run_s,
#     banks_Shock_P_def_t,
#     banks_Shock_D_def_s,
#     banks_Shock_D_run_t,
#     banks_Shock_B,
#     banks_Shock_B_A,
#     banks_Shock_B_Z,
#     banks_Shock_BI_s,
#     banks_Shock_BI_t,
#     banks_Shock_BI_def_s,
#     banks_Shock_BI_def_t,
#     banks_Shock_BI_run_s,
#     banks_Shock_BI_run_t,
#     banks_Shock_BI_run_ilq_s,
#     banks_Shock_BI_run_ilq_t,
#     banks_Shock_BI_run_br_s,
#     banks_Shock_BI_run_br_t,
#     banks_Loss_BI,
#     banks_Loss_BI_def_t,
#     banks_Loss_BI_run_t,
#     banks_on,
#     banks_off,
#     banks_hel,
#     banks_isv,
#     banks_ilq,
#     banks_br,
#     banks_nBoBI,
#     banks_eBoBI,
#     banks_nBoD,
#     banks_eBoD,
#     banks_nLiP,
#     banks_eLiP,
#     banks_isAllocatedShock,
#     banks_listOfExist,
#     banks_listOfInsolvent,
#     banks_listOfIlliquid,
#     banks_listOfBankrupt,
# )

# ## 生成字典变量  #TODO 如何实现自动生成字典变量？
# bankInterbank = @dict(
#     interbank_id,
#     interbank_A_BI,
#     interbank_Z_BI,
#     interbank_Lo_BI,
#     interbank_Li_BI,
#     interbank_Bo_BI,
#     interbank_Bi_BI,
#     interbank_Shock_BI,
#     interbank_Shock_BI_def,
#     interbank_Shock_BI_run,
#     interbank_Shock_BI_run_ilq,
#     interbank_Shock_BI_run_br,
#     interbank_Loss_BI,
#     interbank_Loss_BI_def,
#     interbank_Loss_BI_run,
#     # interbank_isExposure,
#     interbank_on,
#     interbank_off,
#     interbank_hel,
#     interbank_isv,
#     interbank_ilq,
#     interbank_br,
#     interbank_cre,
#     interbank_deb,
#     interbank_cre_isv,
#     interbank_deb_isv,
#     interbank_cre_ilq,
#     interbank_deb_ilq,
#     interbank_cre_br,
#     interbank_deb_br,
# )

