# 系统性金融风险建模



## 定义变量

TODO

$\gamma_{\Box}$：居民效用的跨期折现因子；

$a_{\Box}$：居民行为偏好参数；

$C_{\Box}[i,t]$：居民$i$的大众消费于时期$t$；

$H_{\Box}[i,t]$：居民$i$的住房消费于时期$t$；

$\varepsilon_{c}[t]$：扰动项之于大众消费于时期$t$；

$\varepsilon_{h}[t]$：扰动项之于住房消费于时期$t$；

$w_{\Box}[i,t]$：居民$i$的单位时长工资于时期$t$；

$h_{\Box}[i,t]$：居民$i$的工作时长于时期$t$；

$t_{\Box}[i,t]$：居民$i$获得的转移支付于时期$t$；

$\pi[t]$：通货膨胀于时期$t$，定义为
$$
\pi[t] := \frac{P[t]}{P[t-1]}
$$

其中，
$P[\Box]$：表示物价；

$C_{\Box}[i,t]$：投资和储蓄型居民$i$的大众消费于时期$t$；

$p_{h}[t]$：住房价格在时期$t$；

$D_{\Box}[i,t]$：居民$i$在银行的储蓄；

$w_{\Box}[i,t]$：居民$i$的单位工资于时期$t$；

$h_{\Box}[i,t]$：居民$i$的劳动时长；










## DSGE模型框架的各部门描述

#### 异质性的商业银行部门

部门构成：

- 银行家：
    - 英文全名：Banker
    - 

##### 银行间市场

- [ ] 

#### 广义政府部门

- [ ] 

#### 居民部门

居民部门构成：

- 耐心居民：
- 非耐心居民：

  

其中，成员的转换：

> 参照
> Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.
> 的做法

居民成员角色可相互转化，每期企业家和银行家的相互转化满足泊松过程，分别以固定退出率$1-\lambda e , \lambda e \in(0,1)$ 和 $1-\lambda b , \lambda b \in(0,1)$， 随机退出自己岗位转为其他角色。

> 居民的设置参照
> 方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.
>
> Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.

假设：

- 为了保证稳态时，借款型居民是经济体的净借款方，因此设借款型居民的贴现因子应小于投资和储蓄型居民的贴现因子$\gamma_{HB}<\gamma_{HI}$。
- 居民个数为$N_{H}$，其中借款型居民个数为$N_{HB}$，储蓄与投资型居民个数为$N_{HI}$。





##### 借款型居民

一些文献描述借款型居民为非耐心居民。

- 英文全名：Borrowing Household；

- 变量名：household_borrowing；

- 数学符号：$\Box_{HB}$；

- 行为：
  - 向银行部门之零售贷款银行分支借款$L_{HB,t}$，以银行的贷款利率（等价于居民的借款利率）$r_{b,t}$；
  
  - 消费产品$C_{HB,t}$；
  
- 目标：
	$$
	\max \mathbb{E_{i,t=0}} \left[ \sum_{t=0}^{\infty} 
(\gamma_{HB})^t \left(
  (1-\alpha_{HB}) \varepsilon_{c}[t] \log \left(C_{c,HB}[i,t]-\alpha_{HB} C_{c,HB}[t-1]\right) + \varepsilon_{h}[t] \log C_{h,HB}[i,t] - \frac{\left(h_{HB}[i,t]\right)^{1+\phi}}{1+\phi}
 \right)
 \right]
	$$

	其中，
  $\gamma_{HB}$：借款型居民的居民的跨期折现因子；
  $\alpha_{HB}$：借款型居民的行为偏好参数；
  $C_{c,HB}[i,t]$：借款型居民$i$的大众消费于时期$t$；
  $C_{c,HB}[t-1]$：投资和储蓄型居民的大众消费加总于时期$t-1$；
  $C_{h,HB}[i,t]$：借款型居民$i$的住房消费于时期$t$；
  $\varepsilon_{c}[t]$：扰动项之于大众消费于时期$t$；
  $\varepsilon_{h}[t]$：扰动项之于住房消费于时期$t$；
$h_{HB}[i,t]$：借款型居民$i$的工作时长于时期$t$；
	
	上式中，
	$$
	\varepsilon_{c}[t] \log \left(C_{c, H B}[i, t]-\alpha_{H B} C_{c, H B}[t-1]\right)=\log \frac{C_{c, H B}[i, t]^{\varepsilon_{c}[t]}}{\alpha_{H B} C_{c, H B}[t-1]^{\varepsilon_{c}[t]}}
	$$
	表示借款型居民$i$的大众消费需求。



  - 应满足约束条件：

    - 预算约束：
    	$$
    C_{c,HB}[i,t] + p_{h}[t] \Delta C_{h,HB}[i,t] + \left(1 + r_{b,HB}[t]\right) B_{HB}[i,t-1] / \pi_{t} = w_{HB}[i,t] h_{HB}[i,t] + B_{HB}[i,t]+t_{HB}[i,t]
    	$$
    	其中，
    	$C_{c,HB}[i,t]$：借款型居民$i$的大众消费于时期$t$；
    	$p_{h}[t] \Delta C_{h,HB}[i,t]$：住房价格$p_{h}[t]$与借款型居民$i$的住房偿还贷款变动量$\Delta C_{h,HB}[i,t]$的乘积于时期$t$；
    	$\left(1 + r_{b,HB}[t]\right) B_{HB}[i,t-1] / \pi_{t}$：借款型居民$i$偿还上一期的借款于本期，以借款利率$r_{b,HB}[t]$，考虑当前总通胀率$\pi_t$的影响；
    	$w_{HB}[i,t] h_{HB}[i,t]$：借款型居民$i$的单位工资$w_{HB}[i,t]$与劳动时长$h_{HB}[i,t]$的乘积于时期$t$；
    	$(1+r_{d}[t-1]) D_{HB}[i,t-1] / \pi[t]$：借款型居民$i$的上一期存款$D_{HB}[i,t-1]$于本期提现以上一期的存款利率$r_{d}[t-1]$，考虑当前总通胀率$\pi[t]$的影响；
    	$B_{HB}[i,t]$：借款型居民$i$对银行的借款；
    	$t_{HB}[i,t]$：借款型居民$i$获得的转移支付于时期$t$；
    	

      
    - 信贷抵押约束：
        $$
        \left(1+r_{b,HB}[t] \right) B_{HB}[i,t] \leqslant m_{HB}[t] \; \mathbb{E}_{i,t} \left[ 
        	\left(p_{h}[t+1] \pi[t+1] C_{h,HB}[t] \right) 
        \right]
        $$
        其中，
        $m_{HB}[t]$ ：针对贷款价值比例LTV于借款型居民用于抵押品。$(1-m_{HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本；
    
    

##### 投资和储蓄型居民

一些文献描述投资和储蓄型居民为耐心居民。

- 英文全名：Investment Household；

- 变量名：household_investment；

- 数学符号：$\Box_{HI}$；

- 行为：
  - 向银行部门的银行零售银行存款分支存款$D_{HI}[i,t]$，以存款利率$r_{D,t}$；
  - 消费大众商品$C_{c,HI}[i,t]$；
  - 住房消费$C_{h,HI}[i,t]$；
  
- 目标：
  $$
  \max \mathbb{E}_{i,t=0} \left[ 
  \sum_{t=0}^{\infty}
  (\gamma_{HI})^t
  \left(
  (1-\alpha_{HI}) \varepsilon_{c}[t] \log \left(C_{c,HI}[i,t]-\alpha_{HI} C_{c,HI}[t-1]\right) + \varepsilon_{h}[t] \log h_{HI}[i,t]-\frac{h_{HI}[i,t]^{1+\phi}}{1+\phi}
  \right)
  \right]
  $$
  其中，
  $\gamma_{HI}$：投资和储蓄型居民的居民的时期折现因子；
  $\alpha_{HI}$：投资和储蓄型居民的行为偏好参数；
  $C_{c,HI}[i,t]$：投资和储蓄型居民$i$的大众消费于时期$t$；
  $C_{c,HI}[t-1]$：投资和储蓄型居民的大众消费加总于时期$t-1$；
  $C_{h,HI}[i,t]$：投资和储蓄型居民$i$的住房消费于时期$t$；
  $\varepsilon_{c}[t]$：扰动项之于大众消费于时期$t$；
  $\varepsilon_{h}[t]$：扰动项之于住房消费于时期$t$；
  $h_{HI}[i,t]$：投资和储蓄型居民$i$的工作时长于时期$t$；
  
  上式中，
  $$
  \varepsilon_{c}[t] \log \left(C_{c, H I}[i, t]-\alpha_{H I} C_{c, H I}[t-1]\right)=\log \frac{C_{c, H I}[i, t]^{\varepsilon_{c}[t]}}{\alpha_{H I} C_{c, H I}[t-1]^{\varepsilon_{c}[t]}}
  $$
  表示投资和储蓄型居民$i$的大众消费需求。

  
  
- 应满足的约束条件：
  
  - 对于投资和储蓄型居民$i$，存在预算约束：
  
      $$
    C_{c,HI}[i,t] + p_{h}[t] \Delta C_{h,HI}[i,t] + D_{HI}[i,t] = w_{HI}[i,t] C_{h,HI}[i,t] + (1+r_{d}[t-1]) D_{HI}[i,t-1] / \pi[t] + t_{HI}[i,t])
    $$
    其中，
      $C_{c,HI}[i,t]$：投资和储蓄型居民$i$的大众消费于时期$t$；
      $p_{h}[t] \Delta C_{h,HI}[i,t]$：住房价格$p_{h}[t]$与投资和储蓄型居民$i$的住房偿还贷款变动量$\Delta C_{h,HI}[i,t]$的乘积于时期$t$；
      $D_{HI}[i,t]$：投资和储蓄型居民$i$在银行的储蓄；
      $w_{HI}[i,t] h_{HI}[i,t]$：投资和储蓄型居民$i$的单位工资$w_{HI}[i,t]$与劳动时长$h_{HI}[i,t]$的乘积于时期$t$；
      $(1+r_{d}[t-1]) D_{HI}[i,t-1] / \pi[t]$：投资和储蓄型居民$i$的上一期存款$D_{HI}[i,t-1]$于本期提现以上一期的存款利率$r_{d}[t-1]$，考虑当前总通胀率$\pi[t]$的影响；
      $t_{HI}[i,t]$：投资和储蓄型居民$i$获得的转移支付于时期$t$；









#### 生产部门

生产部门构成：

- 消费品生产商；
  - 生产中间品的厂商；
  - 生产最终品的厂商；
- 房地产开发商；



生产部门分类：

分类针对消费品厂商的生产最终品的厂商、房地产开发商；

- 竞争力充足的厂商；
- 竞争力不足的厂商；



假设：

- 生产消费品中间品的厂商之间不互相竞争；
- 生产消费品最终品的厂商之间存在互相竞争；
- 房地产开发商 TODO；
- 关于企业部门的建模时标准化的。假定经济中存在一系列连续的中间品厂商$i \in [0,1]$；



> 关于生产部门的划分，直接参考：
>

相关构成：

~~企业家：~~

- ~~英文全名：Entrepreneurs；~~
- ~~变量名：entrepreneurs；~~
- ~~数学符号：$\Box_{E}$；~~
- ~~行为：；~~
- ~~目标：~~
- ~~满足的约束条件：~~





##### 消费品生产商

消费品生产商由消费品中间品生产商与消费品最终品生产商构成。

##### 消费品中间品生产商：

- 英文全名：Intermediate Good Producers；

- 变量名：TODO；

- 数学符号：$\Box_{GI}$；

- 行为：

  - 在$t$期生产$Y[i,t]$单位的产品以供最终厂商生产最终品；

- 决策目标：

  - 第一阶段：消费品中间品厂商最小化总成本：
    $$
    总成本 := \min _{L_[i], K_{GI}[i,t]} W_{GI}[t] N_{GI}[i,t] + Z_{GI}[t] K_{GI}[i,t]
    $$
    其中，
    $W_{GI}[t]$：消费品中间品生产商的工资量，在时期$t$；
    $ N_{GI}[i,t] $：消费品中间品生产商$i$的劳动力要素，在时期$t$；
    $Z_{GI}[t]$：消费品中间品生产商的消耗单位资本租金率，在时期$t$；
    $K_{GI}[i,t]$：消费品中间品生产商$i$的资本，在时期$t$；

    

  - 满足的约束条件：

    - 生产函数之中间消费品
      $$
      Y_{GI}[t]=A[t] K_{GI}[i,t]^{\alpha} N_{GI}[i,t]^{1-\alpha} - \Phi
      $$
      其中，
      $A[t]$：全要素生产率；
      $K_{GI}[i,t]$ ：资本要素；
      $N_{GI}[i,t]$：劳动要素；
      $\Phi$：固定生产成本。在稳态条件下，其值被设定为产生0利润。

      假定对数形式的全要素生产率 $A[t]$ 服从如下形式的 AR(1)过程：
      $$
      \ln A[t] = \rho \ln A[t-1] + \varepsilon[t]
      $$
      

    



##### 最终品生产商

- 英文全名：Final Good Producers；
- 变量名：TODO；
- 数学符号：$\Box_{GF}$；
- 行为：
  - 接收中间品生产商，生产最终品



##### 资本品生产商



#### 市场出清

- [ ] 







