# 系统性金融风险建模



## 定义DSGE模型框架的变量

[定义DSGE模型框架的变量](./系统性金融风险建模_定义变量.mmd)



## 假设之于DSGE模型框架







## DSGE模型框架各模块

按照经济体部门划分模块：



#### 居民部门



##### 同质代表性居民部门模块H010

详细描述：

[模块之居民部门H010](./模型框架模块/模块之居民部门H010.mmd)







##### 异质代表性居民部门模块H020

异质代表性居民部门模块H020特点是居民最大化效用函数借鉴

> [[方意, 2016. 宏观审慎政策有效性研究[J]. 世界经济, 39(08): 25–49.]]

详细描述：

[模块之居民部门H020](./模型框架模块/模块之居民部门H020.mmd)





##### 异质代表性居民部门模块H021

异质代表性居民部门模块H021特点是居民最大化效用函数借鉴

> [[Gerali A, Neri S, Sessa L, 等, 2010. Credit and banking in a DSGE model of the Euro area[J]. Journal of money credit and banking, 42(s1): 107–141.]]

详细描述：

[模块之居民部门H021](./模型框架模块/模块之居民部门H021.mmd)





#### 生产部门



##### 同质代表性消费品生产商模块PG010

同质代表性消费品生产商模块PG010不区分消费品最终品生产商、消费品中间品生产商、资本品生产商。统一用只有一种产出品的完全竞争厂商代表企业部门。

详细描述：

[模块之消费品生产商PG010](./模型框架模块/模块之消费品生产商PG010.mmd)





##### 异质代表性消费品生产商模块PG020

异质代表性消费品生产商模块PG020

详细描述：

[模块之消费品生产商PG020](./模型框架模块/模块之消费品生产商PG020.mmd)





##### 同质代表性房地产开发商模块PE010

详细描述：

[模块之房地产开发商PE010](./模型框架模块/模块之房地产开发商PE010.mmd)





#### 银行部门





##### 同质代表性商业银行模块BB010

异质代表性商业银行模块BB010特点是整个银行部门作为一个代表性主体。

详细描述：

[模块之商业银行BB010](./模型框架模块/模块之商业银行BB010.mmd)



##### 异质代表性商业银行模块BB020

异质代表性商业银行模块BB020特点是按照职能划分为：银行批发部门、银行存款部门、银行贷款部门。

详细描述：

[模块之商业银行BB020](./模型框架模块/模块之商业银行BB020.mmd)



##### 异质代表性商业银行模块BB030

异质代表性商业银行模块BB030特点是按照资金规模划分为：资金净拆出银行（大银行、资本充裕）。

详细描述：

[模块之商业银行BB030](./模型框架模块/模块之商业银行BB030.mmd)



##### 异质性多主体商业银行模块BB120

异质性多主体商业银行模块BB120特点是每个银行机构作为一个个体。

详细描述：

[模块之商业银行BB120](./模型框架模块/模块之商业银行BB120.mmd)



##### 同质代表性影子银行模块BS010

详细描述：

[模块之影子银行BS010](./模型框架模块/模块之影子银行BS010.mmd)



##### 异质代表性影子银行模块BS020

详细描述：

[模块之影子银行BS020](./模型框架模块/模块之影子银行BS020.mmd)



##### 异质性多主体影子银行模块BS120

详细描述：

[模块之影子银行BS120](./模型框架模块/模块之影子银行BS120.mmd)







#### 央行和监管部门模块G1









## DSGE模型框架组装方案



### 方案1：



考虑一个离散时间的、无限生命周期的经济体。



详细描述：

[系统性金融风险建模之方案\_010](./系统性金融风险建模之方案_010.mmd)



### 方案2：

考虑一个离散时间的、无限生命周期的经济体。



详细描述：

[系统性金融风险建模之方案\_020](./系统性金融风险建模之方案_020.mmd)




