# 系统性金融风险建模



## 定义DSGE模型框架之全局的变量和参数



### 定义变量之数学符号

TODO

#### 标记：

$\bar{\Box}$：上标带横线号表示相关变量之稳态值；

$\hat{\Box}$：上标带尖冒号表示相关变量偏离比例相对于其稳态值；

$\tilde{\Box}$：上标带波浪号表示相关变量的特殊状态（具体情况具体定义）；

$\Box_{\Box}[\cdot]$：符号的主要部分表示各种变量的主体部分，符号的下标表示主体的类别，方括号内的部分表示自变量；

其中，

$\Box_{\Box}[i,t]$：表示个体$i$的某个变量，在时期$t$；

$\Box_{\Box}[t]$：表示加总的个体$i$在某部门的某个变量，在时期$t$；

$\Box_{\Box}[i]$：表示个体$i$的某个变量，可以不包含时期信息；

$\Box_{\Box}$：表示参数，无个体和时期信息；

$\mathcal{P}$：表示概率；





#### 主体：

$\Box_{H}$：整体居民部门；

- $\mathbb{H}$：集合，由整体居民部门个体构成；





$\Box_{P}$：整体生产部门；

- $\mathbb{P}$：集合，由整体生产部门个体构成；



$\Box_{HB}$：借款型居民；

- $i_{HB}$：单个个体之于借款型居民。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{HB}$：集合，由借款型居民个体构成；
- $N_{HB}$：数量之于借款型居民个体；



$\Box_{HI}$：投资和储蓄型居民；

- $i_{HI}$：单个个体之于投资和储蓄型居民。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{HI}$：集合，由投资和储蓄型居民个体构成；
- $N_{HI}$：数量之于投资和储蓄型居民个体；





$\Box_{PF}$：消费品最终品生产商；

- $i_{PF}$：单个个体之于消费品最终品生产商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PF}$：集合，由消费品最终品生产商个体构成；
- $N_{PF}$：数量之于消费品最终品生产商个体；



$\Box_{PI}$：消费品中间品生产商；

- $i_{PI}$：单个个体之于消费品中间品生产商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PI}$：集合，由消费品中间品生产商个体构成；
- ~~$N_{PI}$：数量之于消费品中间品生产商个体；~~
- $i_{PI,1}$：可以参与制定最优价格的单个个体之于消费品中间品生产商，在当期的时候。在已作出说明的情况下，可以用$j$表示；
- $\mathbb{PI_{1}}$：集合，由可以参与制定最优价格的消费品中间品生产商个体构成，在当期的时候；
- ~~$N_{PI,1}$：数量之于可以参与制定最优价格的消费品中间品生产商个体，在当期的时候；~~
- $i_{PI,2}$：不能参与制定最优价格的单个个体之于消费品中间品生产商，在当期的时候。在已作出说明的情况下，可以用$k$表示；
- $\mathbb{PI_{2}}$：集合，由不能参与制定最优价格的消费品中间品生产商个体构成，在当期的时候；
- ~~$N_{PI,2}$：数量之于不能参与制定最优价格的消费品中间品生产商个体，在当期的时候；~~






$\Box_{PK}$：资本品生产商；

- $i_{PK}$：单个个体之于资本品生产商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PK}$：集合，由资本品生产商个体构成；
- $N_{PK}$：数量之于资本品生产商个体；







$\Box_{PE}$：房地产开发商；

- $i_{PE}$：单个个体之于房地产开发商。在已作出说明的情况下，可以用$i$表示；
- $\mathbb{PE}$：集合，由房地产开发商个体构成；
- $N_{PE}$：数量之于房地产开发商个体；











#### 消费：

$C_{\Box}[i,t]$：个体$i$消费，在时期$t$；

$C_{\Box}[t]$：加总所有个体的消费，在时期$t$；

其中，各下标表示含义如下：

- $C_{HB,c}[i,t]$：借款型居民$i$之大众消费，在时期$t$；
- $C_{HB,h}[i,t]$：借款型居民$i$之房地产消费，在时期$t$；
- $C_{HI,c}[i,t]$：投资与储蓄型居民$i$之大众消费，在时期$t$；
- $C_{HI,h}[i,t]$：投资与储蓄型居民$i$之房地产消费，在时期$t$；



> 该参数在常见参数和变量提及。

$\alpha_{\Box,c}$：部门消费行为偏好参数；





#### 收入、回报、报酬





$w_{\Box}[i,t]$：居民$i$获得的单位工资，暨工资率。同时也是生产商支付给居民$i$的单位工资，在时期$t$；

其中，各下标含义表示如下：

- $w_{PI}[t]$：消费品中间品生产商支付单位工资给居民，在时期$t$；
- $w_{PE}[t]$：房地产开发商支付单位工资给居民部门，在时期$t$；



$tr_{\Box}[i,t]$：居民$i$获得的转移支付，在时期$t$；

$DI_{BB}[t]$：银行提供股利分红；



#### 劳动：



${La}_{H}[i,t]$：个体$i$于时期$t$之劳动变量；

$H_{\Box}[i,t]$：个体$i$工作时长，在时期$t$；

$H_{\Box}[t]$：加总个体居民工作时长，在时期$t$；

其中，各下标表示含义如下：

- $H_{H}[i,t]$：居民部门$H$之个体$i \in \{ \mathbb{HB}, \mathbb{HI} \}$之工作时长，在时期$t$；

- $H_{H,P}[i,t]$：居民部门$H$之个体$i \in \{ \mathbb{HB}, \mathbb{HI} \}$，在生产部门$\mathbb{P}$之子部门之一$\mathbb{P} = \{ {PI}, {PE} \}$之工作时长，在时期$t$；













#### 通货膨胀：

$\pi[t]$：通货膨胀率，在时期$t$；

定义为
$$
\pi[t] := \frac{P[t]}{P[t-1]}
$$

其中，
$P[t]$：表示物价，在时期$t$；





#### 生产要素：





$Y_{\Box}[\cdot]$：产出；

其中，各下标含义表示如下：

- $Y_{PF}[t]$：消费品最终品产量，在时期$t$；

- $Y_{PE}[t]$：房地产开发商的产出，在时期$t$；

- $Y_{PI}[i, t]$：消费品中间品生产商$i$的产出需求，在时期$t$；

  



$A[\cdot]$：全要素生产率；

其中，各下标含义表示如下：

- $\mathrm{TFP}_{PI}[t]$：消费品中间品生产商的全要素生产率，在时期$t$；

- $\mathrm{TFP}_{PK}[t]$：资本生产部门的全要素生产率，在时期$t$；

- $\mathrm{TFP}_{PE}[t]$：房地产开发商的全要素生产率，在时期$t$；

  

$K_{\Box}[i,t]$：各部门个体$i$之资本要素，在时期$t$；

$K_{\Box}[t]$：各部门总体之资本要素，在时期$t$；

其中，各下标含义表示如下：

- $K_{PE}[t]$：房地产开发商整体之资本存量，在时期$t$；
- $K_{PI}[i,t]$：消费品中间品生产商$i$的资本，在时期$t$；
- $K_{PK}[t]$：资本品生产商整体之资本，在时期$t$；
- $K_{BB}[t]$：商业银行部门整体之自有资本，在时期$t$；



$r_{PK,PI}[t]$：消费品中间品生产商的消耗单位资本租金率，在时期$t$。该费率制定者是资本品生产商；



$L_{\Box}[t]$：居民部门整体提供劳动给生产部门；

$L_{\Box}[i,t]$：居民部门个体$i$提供劳动给生产部门，在时期$t$；

其中，各下标含义表示如下：

- $L_{P}[i,t]$：生产部门$\mathbb{P}$个体$i \in \{ \mathbb{PI}, \mathbb{PE} \}$投入劳动要素，在时期$t$；

- $L_{P,H}[i,t]$：生产部门$\mathbb{P}$之个体$i = \{ \mathbb{PI}, \mathbb{PE} \}$，投入劳动要素，其劳动力从居民部门$H$之一$H = \{ {HB}, {HI} \}$在生产部门$P$之子部门之一获取，在时期$t$；







$I_{\Box}[\cdot]$：投资；

其中，各下标含义表示如下：

- $I_{PE}[t]$：房地产开发商的投资，在时期$t$；





#### 价格与工资：

$p_{\Box}[\cdot]$：消费者接受的价格；

其中，各下标含义表示如下：

- $p_{PE}[t]$：住房价格，在时期$t$；
- 



$p_{\Box}[\cdot]$：生产部门个体制定或者调整的价格；

其中，各下标含义表示如下：

- $p_{PF}[t]$：消费品最终品的价格，在时期$t$；
- $p_{PI}[j,t]$：价格，其由具有制定价格能力的消费品中间品生产商$j$制定；
- $\tilde{P}_{PI}[t]$：相同的价格之消费品中间品生产商总体制定的，于定价阶段，在时期$t$；
- $p_{PE}[t]$：房地产价格，在时期$t$；
- $p_{PK}[t]$：资本品生产部门制定的资本出售价格，在时期$t$；



$H_{\Box}[i,t]$：居民$i$的劳动时长，在时期$t$；

$\alpha_{H,H}$：居民工作时长对效用的指数因子；



#### 储蓄：

$D_{\Box}[i,t]$：个体$i$在银行的储蓄；

其中，各下标表示含义如下：

- 居民部门整体存款资金$D_{H}[\cdot,i,t]$至商业银行$i$；
- $r_{BB,D}[t]$：银行提供存款利率以供居民部门存款；





#### 借贷：



$B_{\Box}[i,t]$：商业银行部门个体$i$从商业银行获取的借款；

$B_{\Box}[t]$：部门整体从商业银行获取的借款；

其中，各下标表示含义如下：

- $B_{BB,HB}[t]$：借款型居民部门从商业银行借款，在时期$t$；

- $B_{BB,PE}[t]$：房地产开发商部门从商业银行借款，在时期$t$；

- $B_{BB,PK}[t]$：资本品生产商部门从商业银行借款，在时期$t$；

  





${Adj}_{BB,B}\left[\frac{\mathrm{ABS}_{BS}[t]}{B_{BB,BK}[t]}\right]$：同期信贷资产调整成本函数；



$$：银行杠杆率；



$\mathrm{ABS}_{BS}[j,i,t]$：商业银行$i$购买影子银行$j$提供的资管产品，在时期$t$；



#### 投资：







#### 违约：

$\mathcal{P}_{def,\Box}[t]$：违约概率，在时期$t$；

其中，各下标表示含义如下：

$\mathcal{P}_{def,BS}[t]$：影子银行违约概率，在时期$t$；



#### 利率：



TODO

$r_{\Box}[\cdot]$：利率；

$r_{macro}[t]$：宏观的无风险利率；

$r_{BB,HB}[t]$：商业银行对借款型居民部门的贷款利率，暨借款型居民从商业银行借款利率；

$r_{BB,D}[t]$：居民部门存款于商业银行，商业银行提供的存款利率；

$r_{BB,PK}[t]$：商业银行对资本品生产商的贷款利率，暨资本品生产商对商业银行借款利率；





#### 随机过程变量：





$\rho_{\Box}$：自回归过程的回归系数；

其中，各下标表示含义如下：

- $\rho_{A,\Box}$：生产部门各子部门的全要素生产率$\mathrm{TFP}_{\Box}[t]$对应的自回归过程的回归系数；
- $\rho_{A,PI}$：消费品中间品生产商的全要素生产率$\mathrm{TFP}_{PI}[t]$对应的自回归过程的回归系数；
- $\rho_{H,c}[t]$：扰动项之于居民部门之大众消费，在时期$t$；
- $\rho_{H,h}[t]$：扰动项之于居民部门之住房消费，在时期$t$；
- $\rho_{A,PK}$：消费品中间品生产商的全要素生产率$\mathrm{TFP}_{PK}[t]$对应的自回归过程的回归系数；
- $\rho_{c_{BB,P}}$：商业银行为贷款给企业付出审查成本率$c_{BB,P}[t]$对应的自回归过程的回归系数；





$\varepsilon_{\Box}[t]$：自回归过程的扰动项；

其中，各下标表示含义如下：

- $\varepsilon_{A,\Box}[t]$：扰动项之于自回归过程之于生产部门各子部门之全要素生产率$\mathrm{TFP}_{\Box}[t]$，在时期$t$；
- $\varepsilon_{A,PI}[t]$：扰动项之于自回归过程之于生产部门之消费品生产商之中间品生产商之全要素生产率$\mathrm{TFP}_{PI}[t]$，在时期$t$；
- $\varepsilon_{H,c}[t]$：扰动项之于居民部门之大众消费，在时期$t$；
- $\varepsilon_{H,h}[t]$：扰动项之于居民部门之住房消费，在时期$t$；
- $\varepsilon_{A,PK}[t]$：扰动项之于自回归过程之于生产部门之资本品生产商之全要素生产率$\mathrm{TFP}_{PK}[t]$，在时期$t$；
- $\varepsilon_{c_{BB,P}}[t]$：扰动项之于自回归过程之于商业银行为贷款给企业付出审查成本率$c_{BB,P}[t]$，在时期$t$；



$\sigma_{\Box}$：扰动变量对应的标准差，当其扰动项服从正态分布时；

其中，各下标含义表示如下：

- $\sigma_{A,PI}$：标准差之于扰动项之于消费品中间品生产商的生产技术，其服从正态分布；
- $\sigma_{H,c}[t]$：标准差之于扰动项之于居民部门之大众消费，在时期$t$；
- $\sigma_{H,h}[t]$：标准差之于扰动项之于居民部门之住房消费，在时期$t$；
- $\sigma_{A,PK}[t]$：标准差之于扰动项之于自回归过程之于生产部门之资本品生产商之全要素生产率$\mathrm{TFP}_{PK}[t]$，在时期$t$；
- $\sigma_{c_{BB,P}}[t]$：标准差之于扰动项之于自回归过程之于商业银行为贷款给企业付出审查成本率$c_{BB,P}[t]$，在时期$t$；



#### 监管：



$\Box_{CAR}$：商业银行资本充足率要求（Capital Adequacy Ratio）；

$Pun_{CAR}[i,t,gap_[i,t]]$：资本充足率要求对应的惩罚函数；



$\Box_{DR}$：商业银行存款准备金要求（Deposit Reserve）；

$\delta_{DR}$：存款准备金率；



#### 常见参数和变量

$λ_{\Box}$：居民成员角色中转换为普通居民的转换率（满足泊松过程）；

其中，各下标表示含义如下：

- ~~下标为$e$：企业家转换为普通居民的转换率；~~
- 下标为$b$：银行家转换为普通居民的转换率；



$\gamma_{\Box}$：效用的跨期贴现因子；

其中，各下标表示含义如下：

- $\gamma_{HB}$：借款型居民之效用贴现因子；
- $\gamma_{HI}$：投资于储蓄型居民之效用贴现因子；
- $\gamma_{PI}$：消费品中间品生产商之效用贴现因子；
- $\gamma_{PE}$：房地产开发商之效用贴现因子；



$\alpha_{\Box}$：替代指数、偏好参数；

其中，各下标表示含义如下：

- $\alpha_{HB,c}$：消费型居民大众消费行为偏好参数；
- $\alpha_{HI,c}$：投资和储蓄型居民大众消费行为偏好参数；
- $\alpha_{HB,h}$：消费型居民住房消费行为偏好参数；
- $\alpha_{HI,h}$：投资和储蓄型居民住房消费行为偏好参数；
- $\alpha_{PF}$：替代指数。消费品最终品生产商对于不同的由消费品中间品生产商生产的产品的替代指数；
- $\alpha_{PI}$：消费品中间品生产商的替代指数；
- $\alpha_{PE,K}$：房地产开发商投入资本要素所占的替代指数；
- $\alpha_{PE,L}$：房地产开发商投入劳动要素所占的替代指数；
- $\alpha_{PE,H}$：房地产开发商投入房地产要素所占的替代指数；







#### 其它：

$\chi_{p} \in[0,1]$ ：指数化程度参数，其为消费品中间品厂商为确定化其指数化价格所需；









$\theta_{\Box}$：比例；

其中，各下标表示含义如下：

- $\theta_{PI,p}$：在时期$t$，从曾经没有参与过重新定价的消费品中间品生产商$k \in \mathbb{PI_{2}}$当中，随机抽取一定数量的厂商以参与重新定价，剩余仍未被抽取中以参与重新定价的厂商数量所占的比例；

- $\theta_{PE}$：房地产开发商信贷约束比例；

- $\theta_{HB}[t]$ ：针对借款型居民用于住房消费抵押品之贷款价值比例LTV。$(1-\theta_{HB}[t])$意味着如果发生违约，银行按此比例收回抵押品，从而借款型居民为此付出的成本。LTV是广义政府部门可以进行宏观调控的政策工具，暨广义政府部门根据经济金融周期对其进行逆周期调整；

  

~~$\Phi$：消费品中间品生产商的固定生产成本。在稳态条件下，其值被设定为产生0利润；~~



$F_{\Box}$：生产函数；

其中，各下标表示含义如下：

- $F_{PI}[\mathrm{TFP}_{PI}[t],K_{PI}[i,t],La_{PI}[i,t]]$：消费品中间品生产商的生产函数；
- $F_{PK}$：资本品生产商的资本生产函数；
- $F_{PE}[\mathrm{TFP}_{PE}[t],K_{PE}[t],La_{PE}[t],H_{PE}[t]]$：房地产开发商的生产函数；



$I_{PK}$：资本品生产商的资本投资量；



$p_{PK}$：资本品生产商的资本品再出售价格；



$\delta$：资本品折旧率；







$\phi_{BB,\Box}$：信贷约束比例；

其中，各下标表示含义如下：

- $\phi_{BB,PI}$：商业银行部门向消费品中间品生产商贷款规定的信贷约束比例；



$c_{BB,s}$：商业银行审查贷款用于生产部门之企业，存在单位贷款供给成本率；









##  假设之于DSGE模型框架

假定

TODO



